// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { createPat, listPats } from '@/lib/api-platform/handlers/identity';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// List Personal Access Tokens for the calling user  (scope: keys:read, tier: FREE)
export const GET = withApiV1(listPats, { scope: 'keys:read' });

// Create a Personal Access Token  (scope: keys:write, tier: FREE)
export const POST = withApiV1(createPat, { scope: 'keys:write' });
