// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Identify the calling tenant  (scope: me:read, tier: FREE)
export const GET = withApiV1(async (_req, { ctx }) => {
  return NextResponse.json({
    tenant_id: ctx.tenantId,
    scopes: ctx.scopes,
    tier: ctx.tier,
  });
}, { scope: 'me:read' });
