"use client";

import {
  Activity,
  AlertTriangle,
  AtSign,
  BarChart3,
  BookOpen,
  Bot,
  Calendar,
  CalendarOff,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  Database,
  Eye,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Gauge,
  GitBranch,
  Globe,
  Heart,
  HeartHandshake,
  Inbox,
  Layers,
  LayoutGrid,
  LayoutPanelLeft,
  Library,
  ListChecks,
  MapPin,
  Megaphone,
  PhoneCall,
  PieChart,
  Plug,
  Plus,
  Puzzle,
  Repeat,
  Scale,
  Server,
  Settings,
  Settings2,
  Shapes,
  Share2,
  ShieldCheck,
  Siren,
  Slack,
  SmilePlus,
  Sparkles,
  Star,
  Tag,
  Timer,
  TrendingUp,
  Trophy,
  UserCheck,
  UserCog,
  UserMinus,
  Users,
  Webhook,
  Workflow,
  Wrench,
  Zap,
} from "lucide-react";

import { leaf, type SabAppSidebarConfig } from "./_shared";

export const SABDESK_SIDEBAR: SabAppSidebarConfig = {
  prefix: "/dashboard/sabdesk",
  heading: "SabDesk",
  caption: "Helpdesk & ticketing",
  build: (p) => [
    {
      id: "desk-tickets",
      label: "Tickets",
      items: [
        // exact: the module root would otherwise stay active on every route
        leaf("all", "All tickets", "/dashboard/sabdesk", Inbox, p, { exact: true }),
        leaf("new", "New ticket", "/dashboard/sabdesk/new", Plus, p),
        leaf("mine", "My tickets", "/dashboard/sabdesk/my-tickets", UserCheck, p),
        leaf("unassigned", "Unassigned", "/dashboard/sabdesk/unassigned", UserMinus, p),
        leaf("workspace", "Workspace", "/dashboard/sabdesk/workspace", LayoutPanelLeft, p),
        leaf("views", "Views", "/dashboard/sabdesk/views", Eye, p),
        leaf("social-inbox", "Social inbox", "/dashboard/sabdesk/social-inbox", AtSign, p),
        leaf("voice", "Voice center", "/dashboard/sabdesk/voice-center", PhoneCall, p),
      ],
    },
    {
      id: "desk-knowledge",
      label: "Knowledge & self-service",
      items: [
        leaf("kb-articles", "Knowledge base", "/dashboard/sabdesk/knowledge-base", BookOpen, p),
        leaf("kb-workspace", "KB workspace", "/dashboard/sabdesk/kb", Library, p),
        leaf("community", "Community", "/dashboard/sabdesk/community", Users, p),
        leaf("surveys", "Surveys", "/dashboard/sabdesk/surveys", ClipboardList, p),
      ],
    },
    {
      id: "desk-automation",
      label: "Automation",
      items: [
        leaf("macros", "Macros", "/dashboard/sabdesk/macros", Zap, p),
        leaf("triggers", "Triggers", "/dashboard/sabdesk/triggers", Workflow, p),
        leaf("routing", "Routing", "/dashboard/sabdesk/routing", GitBranch, p),
        leaf("reply-templates", "Reply templates", "/dashboard/sabdesk/reply-templates", FileText, p),
        leaf("custom-forms", "Custom forms", "/dashboard/sabdesk/custom-forms", ListChecks, p),
        leaf("types", "Ticket types", "/dashboard/sabdesk/types", Shapes, p),
        leaf("tags", "Tags", "/dashboard/sabdesk/tags", Tag, p),
      ],
    },
    {
      id: "desk-ai",
      label: "AI Copilot",
      items: [
        leaf("ai-replies", "Suggested replies", "/dashboard/sabdesk/ai-copilot/suggested-replies", Sparkles, p),
        leaf("ai-summaries", "Ticket summarization", "/dashboard/sabdesk/ai-copilot/ticket-summarization", FileText, p),
        leaf("ai-sentiment", "Sentiment analysis", "/dashboard/sabdesk/ai-copilot/sentiment-analysis", SmilePlus, p),
        leaf("ai-training", "Training data", "/dashboard/sabdesk/ai-copilot/training-data", Database, p),
        leaf("ai-settings", "AI settings", "/dashboard/sabdesk/ai-copilot/ai-settings", Bot, p),
      ],
    },
    {
      id: "desk-analytics",
      label: "Analytics",
      items: [
        leaf("an-overview", "Overview", "/dashboard/sabdesk/analytics/overview", BarChart3, p),
        leaf("an-volume", "Ticket volume", "/dashboard/sabdesk/analytics/ticket-volume", TrendingUp, p),
        leaf("an-resolution", "Resolution times", "/dashboard/sabdesk/analytics/resolution-times", Timer, p),
        leaf("an-sla", "SLA compliance", "/dashboard/sabdesk/analytics/sla-compliance", ShieldCheck, p),
        leaf("an-csat", "Customer satisfaction", "/dashboard/sabdesk/analytics/customer-satisfaction", Heart, p),
        leaf("an-agents", "Agent performance", "/dashboard/sabdesk/analytics/agent-performance", UserCheck, p),
        leaf("an-channels", "Channel metrics", "/dashboard/sabdesk/analytics/channel-metrics", PieChart, p),
        leaf("an-deflection", "AI deflection", "/dashboard/sabdesk/analytics/ai-deflection", Bot, p),
        leaf("an-live", "Live dashboards", "/dashboard/sabdesk/analytics/live-dashboards", Activity, p),
        leaf("an-reports", "Custom reports", "/dashboard/sabdesk/analytics/custom-reports", FileSpreadsheet, p),
      ],
    },
    {
      id: "desk-team",
      label: "Team & quality",
      items: [
        leaf("teams", "Teams", "/dashboard/sabdesk/teams", Users, p),
        leaf("groups", "Ticket groups", "/dashboard/sabdesk/groups", Layers, p),
        leaf("agent-groups", "Agent groups", "/dashboard/sabdesk/agent-groups", UserCog, p),
        leaf("gamification", "Gamification", "/dashboard/sabdesk/gamification", Trophy, p),
        leaf("announcements", "Announcements", "/dashboard/sabdesk/announcements", Megaphone, p),
        leaf("qa-evaluations", "QA evaluations", "/dashboard/sabdesk/quality-assurance/evaluations", ClipboardCheck, p),
        leaf("qa-scorecards", "Scorecards", "/dashboard/sabdesk/quality-assurance/scorecards", Star, p),
        leaf("qa-calibration", "Calibration", "/dashboard/sabdesk/quality-assurance/calibration", Scale, p),
        leaf("qa-disputes", "Disputes", "/dashboard/sabdesk/quality-assurance/disputes", AlertTriangle, p),
        leaf("qa-settings", "QA settings", "/dashboard/sabdesk/quality-assurance/qa-settings", Settings2, p),
      ],
    },
    {
      id: "desk-ops",
      label: "Workforce & operations",
      items: [
        leaf("wf-scheduling", "Scheduling", "/dashboard/sabdesk/workforce/scheduling", Calendar, p),
        leaf("wf-forecast", "Forecast", "/dashboard/sabdesk/workforce/forecast", TrendingUp, p),
        leaf("wf-attendance", "Attendance", "/dashboard/sabdesk/workforce/attendance", Clock, p),
        leaf("wf-time-off", "Time off", "/dashboard/sabdesk/workforce/time-off", CalendarOff, p),
        leaf("wf-shift-swaps", "Shift swaps", "/dashboard/sabdesk/workforce/shift-swaps", Repeat, p),
        leaf("incidents", "Incident management", "/dashboard/sabdesk/incident-mgmt", Siren, p),
        leaf("itsm", "ITSM", "/dashboard/sabdesk/itsm", Server, p),
        leaf("field-service", "Field service", "/dashboard/sabdesk/field-service", MapPin, p),
        leaf("customer-success", "Customer success", "/dashboard/sabdesk/customer-success", HeartHandshake, p),
      ],
    },
    {
      id: "desk-integrations",
      label: "Integrations",
      items: [
        leaf("app-directory", "App directory", "/dashboard/sabdesk/integrations/app-directory", LayoutGrid, p),
        leaf("active-apps", "Active apps", "/dashboard/sabdesk/integrations/active-apps", Puzzle, p),
        leaf("custom-apps", "Custom apps", "/dashboard/sabdesk/integrations/custom-apps", Wrench, p),
        leaf("slack", "Slack", "/dashboard/sabdesk/integrations/slack", Slack, p),
        leaf("jira", "Jira", "/dashboard/sabdesk/integrations/jira", Plug, p),
        leaf("salesforce", "Salesforce", "/dashboard/sabdesk/integrations/salesforce", Plug, p),
        leaf("hubspot", "HubSpot", "/dashboard/sabdesk/integrations/hubspot", Plug, p),
        leaf("zapier", "Zapier", "/dashboard/sabdesk/integrations/zapier", Plug, p),
        leaf("webhooks", "Webhooks", "/dashboard/sabdesk/integrations/webhooks", Webhook, p),
        leaf("api-logs", "API logs", "/dashboard/sabdesk/integrations/api-logs", FileSearch, p),
      ],
    },
    {
      id: "desk-settings",
      label: "Settings",
      items: [
        // exact: keeps "General" inactive on /settings/sla-policies
        leaf("general", "General", "/dashboard/sabdesk/settings", Settings, p, { exact: true }),
        // canonical settings entry; legacy /sla stays routable for back-compat
        leaf("sla", "SLA policies", "/dashboard/sabdesk/settings/sla-policies", Gauge, p),
        leaf("channels", "Channels", "/dashboard/sabdesk/channels", Share2, p),
        leaf("localization", "Localization", "/dashboard/sabdesk/localization", Globe, p),
        leaf("billing", "Billing", "/dashboard/sabdesk/billing", CreditCard, p),
      ],
    },
  ],
};
