// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Delete a template  (scope: templates:write, tier: FREE)
export const DELETE = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/wachat/templates/${encodeURIComponent(String((params as Record<string, string>).templateId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'DELETE',
    },
  );
  return NextResponse.json(data);
}, { scope: 'templates:write' });

// Fetch one template  (scope: templates:read, tier: FREE)
export const GET = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/wachat/templates/${encodeURIComponent(String((params as Record<string, string>).templateId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'GET',
    },
  );
  return NextResponse.json(data);
}, { scope: 'templates:read' });
