// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.
/* eslint-disable */

import catalog from '../../_data/catalog.json';
import { notFound } from 'next/navigation';
import {
  Breadcrumb,
  ZoruBreadcrumbList,
  ZoruBreadcrumbItem,
  ZoruBreadcrumbLink,
  ZoruBreadcrumbSeparator,
  ZoruBreadcrumbPage,
  PageHeader,
  ZoruPageHeading,
  ZoruPageTitle,
  ZoruPageDescription,
  Table,
  ZoruTableHeader,
  ZoruTableHead,
  ZoruTableBody,
  ZoruTableRow,
  ZoruTableCell,
} from '@/components/zoruui';

export const revalidate = 3600;
export const dynamicParams = true;

interface Row {
  module: string;
  slug: string;
  method: string;
  path: string;
  summary: string;
  scope: string;
  tier: string;
}

const rows = catalog as Row[];

export async function generateStaticParams() {
  const modules = new Set(rows.map((r) => r.module));
  return Array.from(modules).map((module) => ({ module }));
}

function MethodBadge({ method }: { method: string }) {
  const colors: Record<string, string> = {
    GET: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    POST: 'bg-green-500/20 text-green-300 border-green-500/40',
    PATCH: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    PUT: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    DELETE: 'bg-red-500/20 text-red-300 border-red-500/40',
  };
  const cls = colors[method] ?? 'bg-zinc-500/20 text-zinc-300 border-zinc-500/40';
  return (
    <span className={'inline-block text-[10px] font-bold px-1.5 py-0.5 rounded border w-14 text-center ' + cls}>
      {method}
    </span>
  );
}

export default async function Page({ params }: { params: Promise<{ module: string }> }) {
  const { module } = await params;
  const moduleRows = rows
    .filter((r) => r.module === module)
    .sort((a, b) => (a.path + a.method).localeCompare(b.path + b.method));
  if (moduleRows.length === 0) notFound();

  return (
    <div className="zoruui min-h-screen bg-zoru-bg text-zoru-ink">
      <div className="max-w-5xl mx-auto px-6 py-8">
        <div className="flex flex-col gap-6">
          <Breadcrumb>
            <ZoruBreadcrumbList>
              <ZoruBreadcrumbItem>
                <ZoruBreadcrumbLink href="/api/docs/modules">All modules</ZoruBreadcrumbLink>
              </ZoruBreadcrumbItem>
              <ZoruBreadcrumbSeparator />
              <ZoruBreadcrumbItem>
                <ZoruBreadcrumbPage className="capitalize">{module}</ZoruBreadcrumbPage>
              </ZoruBreadcrumbItem>
            </ZoruBreadcrumbList>
          </Breadcrumb>

          <PageHeader>
            <ZoruPageHeading>
              <ZoruPageTitle className="capitalize">{module}</ZoruPageTitle>
              <ZoruPageDescription>
                {moduleRows.length} endpoint{moduleRows.length === 1 ? '' : 's'}. Click any row for
                the deep page with code samples in 15+ languages and a live test runner.
              </ZoruPageDescription>
            </ZoruPageHeading>
          </PageHeader>

          <div className="rounded-[var(--zoru-radius)] border border-zoru-line overflow-hidden">
            <Table>
              <ZoruTableHeader>
                <ZoruTableRow>
                  <ZoruTableHead className="w-20">Method</ZoruTableHead>
                  <ZoruTableHead>Path</ZoruTableHead>
                  <ZoruTableHead className="hidden md:table-cell">Summary</ZoruTableHead>
                </ZoruTableRow>
              </ZoruTableHeader>
              <ZoruTableBody>
                {moduleRows.map((r) => (
                  <ZoruTableRow
                    key={r.slug}
                    className="cursor-pointer hover:bg-zoru-surface-2 transition-colors"
                    onClick={undefined}
                  >
                    <ZoruTableCell>
                      <a
                        href={'/api/docs/modules/' + module + '/' + r.slug}
                        className="flex items-center gap-3 w-full"
                        tabIndex={-1}
                      >
                        <MethodBadge method={r.method} />
                      </a>
                    </ZoruTableCell>
                    <ZoruTableCell>
                      <a href={'/api/docs/modules/' + module + '/' + r.slug} className="block w-full">
                        <code className="font-mono text-sm text-zoru-ink">{r.path}</code>
                      </a>
                    </ZoruTableCell>
                    <ZoruTableCell className="hidden md:table-cell text-zoru-ink-muted text-xs">
                      <a href={'/api/docs/modules/' + module + '/' + r.slug} className="block w-full">
                        {r.summary}
                      </a>
                    </ZoruTableCell>
                  </ZoruTableRow>
                ))}
              </ZoruTableBody>
            </Table>
          </div>
        </div>
      </div>
    </div>
  );
}
