// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.
/* eslint-disable */

import catalog from '../../_data/catalog.json';
import { notFound } from 'next/navigation';

// Render on-demand and cache for an hour. Pre-rendering all 11k+
// endpoints at build time is wasteful; rendering on first request +
// caching keeps the build fast and the page fresh.
export const revalidate = 3600;
export const dynamicParams = true;

interface Row {
  module: string;
  slug: string;
  method: string;
  path: string;
  summary: string;
  scope: string;
  tier: string;
}

const rows = catalog as Row[];

export async function generateStaticParams() {
  const modules = new Set(rows.map((r) => r.module));
  return Array.from(modules).map((module) => ({ module }));
}

function MethodBadge({ method }: { method: string }) {
  const colors: Record<string, string> = {
    GET: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    POST: 'bg-green-500/20 text-green-300 border-green-500/40',
    PATCH: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    PUT: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    DELETE: 'bg-red-500/20 text-red-300 border-red-500/40',
  };
  const cls = colors[method] ?? 'bg-zinc-500/20 text-zinc-300 border-zinc-500/40';
  return <span className={'inline-block text-[10px] font-bold px-1.5 py-0.5 rounded border ' + cls + ' w-14 text-center'}>{method}</span>;
}

export default async function Page({ params }: { params: Promise<{ module: string }> }) {
  const { module } = await params;
  const moduleRows = rows
    .filter((r) => r.module === module)
    .sort((a, b) => (a.path + a.method).localeCompare(b.path + b.method));
  if (moduleRows.length === 0) notFound();

  return (
    <div className="max-w-5xl mx-auto px-6 py-8 text-zinc-100">
      <header className="mb-6">
        <a href="/api/docs/modules" className="text-xs text-amber-300 hover:text-amber-200">
          ← All modules
        </a>
        <h1 className="text-3xl font-bold mt-2 capitalize">{module}</h1>
        <p className="text-sm text-zinc-400 mt-1">
          {moduleRows.length} endpoint{moduleRows.length === 1 ? '' : 's'}. Click any row for the
          deep page with code samples in 15+ languages and a live test runner.
        </p>
      </header>

      <ul className="rounded-md border border-zinc-800 divide-y divide-zinc-800">
        {moduleRows.map((r) => (
          <li key={r.slug}>
            <a
              href={'/api/docs/modules/' + module + '/' + r.slug}
              className="flex items-center gap-3 px-3 py-2 hover:bg-zinc-900/50 transition"
            >
              <MethodBadge method={r.method} />
              <code className="font-mono text-sm text-zinc-200 flex-1 truncate">{r.path}</code>
              <span className="text-xs text-zinc-500 hidden md:block truncate max-w-[40%]">
                {r.summary}
              </span>
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}
