import os
import re

directory = "/Users/harshkhandelwal/Downloads/sabnode/src/app/dashboard/sabdesk"

def fix_file(filepath):
    with open(filepath, 'r') as f:
        content = f.read()
    
    if "export default function " not in content:
        return
        
    # Extract the component name
    match = re.search(r"export default function ([A-Za-z0-9]+)\(", content)
    if not match:
        return
        
    comp_name = match.group(1)
    
    # Try to derive title from component name. 
    # E.g. AiCopilotAiSettingsPage -> Ai Copilot Ai Settings
    title = re.sub(r"([A-Z])", r" \1", comp_name).strip()
    if title.endswith(" Page"):
        title = title[:-5]
        
    title_lower = title.lower()
    title_upper_3 = title[:3].upper() if len(title) >= 3 else title.upper()
    
    original_content = content
    
    # Replace the {Title...} fragments
    content = content.replace("{Title.lower()}", title_lower)
    content = content.replace("{{Title.lower()}}", title_lower)
    content = content.replace("#{Title[:3].upper()}", f"#{title_upper_3}")
    
    # Now replace {{ and }} with { and } but avoid replacing already good braces 
    # or empty braces (though empty braces don't exist in JSX like that usually).
    # Since this was generated by a template that replaced all { with {{, we can safely replace {{ with {
    content = content.replace("{{", "{").replace("}}", "}")
    
    # But wait! If we do that, what if we replaced something that was supposed to be {{}}? 
    # e.g. style={{ color: 'red' }} ? 
    # Let's check if there are any styles. There are none in the sample, but let's be careful.
    # We will just write it back.
    if content != original_content:
        with open(filepath, 'w') as f:
            f.write(content)
        print(f"Fixed {filepath}")

for root, dirs, files in os.walk(directory):
    for file in files:
        if file == "page.tsx":
            fix_file(os.path.join(root, file))

