import type { LucideIcon } from 'lucide-react';
import {
  Inbox,
  MessageSquare,
  Instagram,
  Mail,
  MessageCircle,
  Clock,
  Reply,
  Tag,
  Workflow,
  Bot,
  Brain,
  Zap,
  GitBranch,
  Calendar,
  Users2,
  Filter,
  Layers,
  Database,
  Shield,
  Send,
  FileText,
  TrendingUp,
  Globe,
  Image as ImageIcon,
  LineChart,
  Activity,
  Star,
  Download,
  Target,
  Eye,
  DollarSign,
  BadgeCheck,
  Hash,
  Sparkles,
} from 'lucide-react';
import type { FeatureIconKey } from './types';

export const FEATURE_ICONS: Record<FeatureIconKey, LucideIcon> = {
  inbox: Inbox,
  whatsapp: MessageSquare,
  instagram: Instagram,
  email: Mail,
  webchat: MessageCircle,
  clock: Clock,
  reply: Reply,
  tag: Tag,
  workflow: Workflow,
  bot: Bot,
  brain: Brain,
  zap: Zap,
  gitBranch: GitBranch,
  calendar: Calendar,
  users: Users2,
  filter: Filter,
  layers: Layers,
  database: Database,
  shield: Shield,
  send: Send,
  fileText: FileText,
  trendingUp: TrendingUp,
  globe: Globe,
  image: ImageIcon,
  lineChart: LineChart,
  activity: Activity,
  star: Star,
  download: Download,
  target: Target,
  eye: Eye,
  dollar: DollarSign,
  badge: BadgeCheck,
  hash: Hash,
  sparkles: Sparkles,
};
