// @generated by tools/api-codegen - DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.
/* eslint-disable */

import catalog from '../../../_data/catalog.json';
import { notFound } from 'next/navigation';
import { CodeSamplesTabs } from '../../../_components/CodeSamplesTabs';
import { TestEndpointRunner } from '../../../_components/TestEndpointRunner';
import { buildSamples } from '@/lib/api-platform/sample-builder';
import {
  Badge,
  Breadcrumb,
  BreadcrumbList,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbPage,
  BreadcrumbSeparator,
  PageHeader,
  PageHeaderHeading,
  PageTitle,
  PageDescription,
  Table,
  THead,
  TBody,
  Tr,
  Th,
  Td,
  type BadgeTone,
} from '@/components/sabcrm/20ui';

// Render on-demand and cache for an hour. Pre-rendering all 11k+
// endpoints at build time is wasteful; rendering on first request +
// caching keeps the build fast and the page fresh.
export const revalidate = 3600;
export const dynamicParams = true;

interface Row {
  module: string;
  slug: string;
  method: string;
  path: string;
  summary: string;
  description: string | null;
  scope: string;
  tier: string;
  credits: number | null;
  idempotent: boolean;
  emits: string[];
  pathParams: Array<{ name: string; type: string; description: string }>;
  queryParams: Array<{ name: string; type: string; required: boolean; description: string }>;
  hasBody: boolean;
}

const rows = catalog as Row[];

export async function generateStaticParams() {
  // For 11k+ endpoints we render on-demand and let Next.js cache after
  // first hit (`dynamicParams = true`).
  return [];
}

const METHOD_TONE: Record<string, BadgeTone> = {
  GET: 'info',
  POST: 'success',
  PATCH: 'warning',
  PUT: 'warning',
  DELETE: 'danger',
};

function MethodBadge({ method }: { method: string }) {
  return (
    <Badge tone={METHOD_TONE[method] ?? 'neutral'} kind="soft">
      {method}
    </Badge>
  );
}

function ParamTable({
  title,
  rows: r,
}: {
  title: string;
  rows: Array<{ name: string; type: string; required?: boolean; description: string }>;
}) {
  if (!r.length) return null;
  return (
    <div className="my-3">
      <div className="text-xs font-semibold text-[var(--st-text)] mb-1">{title}</div>
      <Table density="compact" className="text-xs">
        <THead>
          <Tr>
            <Th>Name</Th>
            <Th>Type</Th>
            <Th>Req.</Th>
            <Th>Description</Th>
          </Tr>
        </THead>
        <TBody>
          {r.map((p) => (
            <Tr key={p.name}>
              <Td>
                <code className="font-mono text-[var(--st-accent)]">{p.name}</code>
              </Td>
              <Td>
                <code className="font-mono text-[var(--st-text-secondary)]">{p.type}</code>
              </Td>
              <Td>
                {p.required ? (
                  <span className="text-[var(--st-status-ok)]" aria-label="Required">
                    Yes
                  </span>
                ) : (
                  <span className="text-[var(--st-text-tertiary)]" aria-label="Optional">
                    No
                  </span>
                )}
              </Td>
              <Td>
                <span className="text-[var(--st-text)]">{p.description}</span>
              </Td>
            </Tr>
          ))}
        </TBody>
      </Table>
    </div>
  );
}

export default async function Page({
  params,
}: {
  params: Promise<{ module: string; endpoint: string }>;
}) {
  const { module, endpoint } = await params;
  const e = rows.find((r) => r.module === module && r.slug === endpoint);
  if (!e) notFound();

  // Build samples on-demand from the slim catalog row. The builder lives
  // under `src/lib/api-platform/sample-builder.ts` so the docs page
  // never needs to reach into `tools/` (Turbopack production builds
  // don't include code outside `src/`).
  const samples = buildSamples({
    module: e.module,
    method: e.method,
    path: e.path,
    hasBody: e.hasBody,
    idempotent: e.idempotent,
    pathParams: e.pathParams,
    queryParams: e.queryParams,
  });

  return (
    <div className="max-w-5xl mx-auto px-6 py-8 text-[var(--st-text)]">
      <Breadcrumb className="mb-4">
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink href="/api/docs/modules">All modules</BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbLink href={'/api/docs/modules/' + module} className="capitalize">
              {module}
            </BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage className="truncate">
              {e.method} {e.path}
            </BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>

      <PageHeader className="mb-6">
        <PageHeaderHeading>
          <div className="flex items-center gap-2 mb-2">
            <MethodBadge method={e.method} />
            <code className="text-sm font-mono text-[var(--st-text)]">{e.path}</code>
          </div>
          <PageTitle>{e.summary}</PageTitle>
          {e.description ? <PageDescription>{e.description}</PageDescription> : null}
        </PageHeaderHeading>
      </PageHeader>

      <div className="flex flex-wrap gap-2 mb-6 text-xs">
        <Badge tone="neutral" kind="outline">
          Scope: <code className="ml-1 font-mono text-[var(--st-accent)]">{e.scope}</code>
        </Badge>
        <Badge tone="neutral" kind="outline">
          Tier: {e.tier}
        </Badge>
        {e.credits ? (
          <Badge tone="neutral" kind="outline">
            {e.credits} credit{e.credits === 1 ? '' : 's'}
          </Badge>
        ) : null}
        {e.idempotent ? (
          <Badge tone="neutral" kind="outline">
            Idempotent
          </Badge>
        ) : null}
        {e.emits.map((ev) => (
          <Badge key={ev} tone="neutral" kind="outline">
            emits <code className="ml-1 font-mono text-[var(--st-accent)]">{ev}</code>
          </Badge>
        ))}
      </div>

      <ParamTable title="Path parameters" rows={e.pathParams.map((p) => ({ ...p, required: true }))} />
      <ParamTable title="Query parameters" rows={e.queryParams} />
      {e.hasBody ? (
        <p className="text-xs text-[var(--st-text-secondary)] my-2">
          Request body: <span className="font-mono">application/json</span>
        </p>
      ) : null}

      <section className="mt-8">
        <h2 className="text-sm font-semibold text-[var(--st-text)] mb-2">Code samples</h2>
        <CodeSamplesTabs samples={samples} />
      </section>

      <section className="mt-8">
        <h2 className="text-sm font-semibold text-[var(--st-text)] mb-2">Try it</h2>
        <TestEndpointRunner
          method={e.method}
          path={e.path}
          pathParams={e.pathParams}
          queryParams={e.queryParams}
          hasBody={e.hasBody}
        />
      </section>
    </div>
  );
}
