// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

import catalog from '../../../_data/catalog.json';
import { notFound } from 'next/navigation';
import { CodeSamplesTabs } from '../../../_components/CodeSamplesTabs';
import { TestEndpointRunner } from '../../../_components/TestEndpointRunner';
import { buildSamples } from '@/lib/api-platform/sample-builder';
import { OpenApiExportButton } from './export-button';
import {
  Breadcrumb,
  ZoruBreadcrumbList,
  ZoruBreadcrumbItem,
  ZoruBreadcrumbLink,
  ZoruBreadcrumbSeparator,
  ZoruBreadcrumbPage,
  PageHeader,
  ZoruPageHeading,
  ZoruPageTitle,
  ZoruPageDescription,
  Table,
  ZoruTableHeader,
  ZoruTableHead,
  ZoruTableBody,
  ZoruTableRow,
  ZoruTableCell,
} from '@/components/zoruui';

export const revalidate = 3600;
export const dynamicParams = true;

interface Row {
  module: string;
  slug: string;
  method: string;
  path: string;
  summary: string;
  description: string | null;
  scope: string;
  tier: string;
  credits: number | null;
  idempotent: boolean;
  emits: string[];
  pathParams: Array<{ name: string; type: string; description: string }>;
  queryParams: Array<{ name: string; type: string; required: boolean; description: string }>;
  hasBody: boolean;
}

const rows = catalog as Row[];

export async function generateStaticParams() {
  // Pre-build the most common API endpoints for faster docs loading
  return rows.slice(0, 50).map((r) => ({
    module: r.module,
    endpoint: r.slug,
  }));
}

function MethodBadge({ method }: { method: string }) {
  const colors: Record<string, string> = {
    GET: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    POST: 'bg-green-500/20 text-green-300 border-green-500/40',
    PATCH: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    PUT: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/40',
    DELETE: 'bg-red-500/20 text-red-300 border-red-500/40',
  };
  const cls = colors[method] ?? 'bg-zinc-500/20 text-zinc-300 border-zinc-500/40';
  return (
    <span className={'inline-block text-xs font-bold px-2 py-0.5 rounded border ' + cls}>
      {method}
    </span>
  );
}

function ParamTable({
  title,
  rows: r,
}: {
  title: string;
  rows: Array<{ name: string; type: string; required?: boolean; description: string }>;
}) {
  if (!r.length) return null;
  return (
    <div className="my-4">
      <p className="text-xs font-semibold text-zoru-ink mb-2">{title}</p>
      <div className="rounded-[var(--zoru-radius)] border border-zoru-line overflow-hidden">
        <Table>
          <ZoruTableHeader>
            <ZoruTableRow>
              <ZoruTableHead>Name</ZoruTableHead>
              <ZoruTableHead>Type</ZoruTableHead>
              <ZoruTableHead>Req.</ZoruTableHead>
              <ZoruTableHead>Description</ZoruTableHead>
            </ZoruTableRow>
          </ZoruTableHeader>
          <ZoruTableBody>
            {r.map((p) => (
              <ZoruTableRow key={p.name}>
                <ZoruTableCell className="font-mono text-xs text-amber-400">{p.name}</ZoruTableCell>
                <ZoruTableCell className="font-mono text-xs text-zoru-ink-muted">{p.type}</ZoruTableCell>
                <ZoruTableCell className="text-xs text-zoru-ink-muted">{p.required ? '✓' : ''}</ZoruTableCell>
                <ZoruTableCell className="text-xs text-zoru-ink">{p.description}</ZoruTableCell>
              </ZoruTableRow>
            ))}
          </ZoruTableBody>
        </Table>
      </div>
    </div>
  );
}

export default async function Page({
  params,
}: {
  params: Promise<{ module: string; endpoint: string }>;
}) {
  const { module, endpoint } = await params;
  const e = rows.find((r) => r.module === module && r.slug === endpoint);
  if (!e) notFound();

  const samples = buildSamples({
    module: e.module,
    method: e.method,
    path: e.path,
    hasBody: e.hasBody,
    idempotent: e.idempotent,
    pathParams: e.pathParams,
    queryParams: e.queryParams,
  });

  return (
    <div className="zoruui min-h-screen bg-zoru-bg text-zoru-ink">
      <div className="max-w-5xl mx-auto px-6 py-8">
        <div className="flex flex-col gap-6">
          <Breadcrumb>
            <ZoruBreadcrumbList>
              <ZoruBreadcrumbItem>
                <ZoruBreadcrumbLink href="/api/docs/modules">All modules</ZoruBreadcrumbLink>
              </ZoruBreadcrumbItem>
              <ZoruBreadcrumbSeparator />
              <ZoruBreadcrumbItem>
                <ZoruBreadcrumbLink href={'/api/docs/modules/' + module} className="capitalize">
                  {module}
                </ZoruBreadcrumbLink>
              </ZoruBreadcrumbItem>
              <ZoruBreadcrumbSeparator />
              <ZoruBreadcrumbItem>
                <ZoruBreadcrumbPage className="truncate max-w-[200px]">
                  {e.method} {e.path}
                </ZoruBreadcrumbPage>
              </ZoruBreadcrumbItem>
            </ZoruBreadcrumbList>
          </Breadcrumb>

          <PageHeader>
            <div className="flex justify-between items-start gap-4">
              <ZoruPageHeading>
                <div className="flex items-center gap-2 mb-1">
                  <MethodBadge method={e.method} />
                  <code className="text-sm font-mono text-zoru-ink">{e.path}</code>
                </div>
                <ZoruPageTitle>{e.summary}</ZoruPageTitle>
                {e.description ? (
                  <ZoruPageDescription>{e.description}</ZoruPageDescription>
                ) : null}
              </ZoruPageHeading>
              <div className="shrink-0 mt-2">
                <OpenApiExportButton endpoint={e} />
              </div>
            </div>
          </PageHeader>

          <div className="flex flex-wrap gap-2">
            <span className="text-xs px-2 py-0.5 rounded border border-zoru-line bg-zoru-surface text-zoru-ink-muted">
              Scope: <code className="font-mono text-amber-400">{e.scope}</code>
            </span>
            <span className="text-xs px-2 py-0.5 rounded border border-zoru-line bg-zoru-surface text-zoru-ink-muted">
              Tier: {e.tier}
            </span>
            {e.credits ? (
              <span className="text-xs px-2 py-0.5 rounded border border-zoru-line bg-zoru-surface text-zoru-ink-muted">
                {e.credits} credit{e.credits === 1 ? '' : 's'}
              </span>
            ) : null}
            {e.idempotent ? (
              <span className="text-xs px-2 py-0.5 rounded border border-zoru-line bg-zoru-surface text-zoru-ink-muted">
                Idempotent
              </span>
            ) : null}
            {e.emits.map((ev) => (
              <span key={ev} className="text-xs px-2 py-0.5 rounded border border-zoru-line bg-zoru-surface text-zoru-ink-muted">
                emits <code className="font-mono text-amber-400">{ev}</code>
              </span>
            ))}
          </div>

          <ParamTable title="Path parameters" rows={e.pathParams.map((p) => ({ ...p, required: true }))} />
          <ParamTable title="Query parameters" rows={e.queryParams} />
          {e.hasBody ? (
            <p className="text-xs text-zoru-ink-muted">
              Request body: <span className="font-mono">application/json</span>
            </p>
          ) : null}

          <section className="space-y-2">
            <h2 className="text-sm font-semibold text-zoru-ink">Code samples</h2>
            <CodeSamplesTabs samples={samples} />
          </section>

          <section className="space-y-2">
            <h2 className="text-sm font-semibold text-zoru-ink">Try it</h2>
            <TestEndpointRunner
              method={e.method}
              path={e.path}
              pathParams={e.pathParams}
              queryParams={e.queryParams}
              hasBody={e.hasBody}
            />
          </section>
        </div>
      </div>
    </div>
  );
}
