'use client';

import { use, useEffect, useState } from 'react';
import { Loader2 } from 'lucide-react';

export default function PrintAuditPage({ params }: { params: Promise<{ projectId: string }> }) {
    const { projectId } = use(params);
    const [audit, setAudit] = useState<any>(null);

    useEffect(() => {
        // Fetch data client-side for simplicity in print view
        // In real app, perform server fetch
        fetch(`/api/v1/seo/audit?projectId=${projectId}`, { headers: { 'Authorization': 'Bearer test' } })
            .then(res => res.json())
            .then(data => setAudit(data));
    }, [projectId]);

    if (!audit) return <div className="flex items-center justify-center h-screen"><Loader2 className="animate-spin" /> Generating Report...</div>;

    return (
        <div className="p-8 bg-white text-black max-w-[210mm] mx-auto min-h-screen">
            <header className="border-b pb-4 mb-8">
                <h1 className="text-3xl font-bold">SEO Audit Report</h1>
                <p className="text-gray-500">Generated for Project: {projectId}</p>
                <p className="text-sm text-gray-400">{new Date().toLocaleDateString()}</p>
            </header>

            <section className="mb-8">
                <h2 className="text-xl font-bold mb-4 border-l-4 border-blue-600 pl-3">Executive Summary</h2>
                <div className="grid grid-cols-3 gap-4">
                    <div className="p-4 bg-gray-100 rounded">
                        <div className="text-2xl font-bold">{audit.score || 85}/100</div>
                        <div className="text-sm">Health Score</div>
                    </div>
                    <div className="p-4 bg-gray-100 rounded">
                        <div className="text-2xl font-bold">{audit.urlCount || 0}</div>
                        <div className="text-sm">Pages Crawled</div>
                    </div>
                    <div className="p-4 bg-gray-100 rounded">
                        <div className="text-2xl font-bold text-red-600">{audit.issues?.length || 0}</div>
                        <div className="text-sm">Critical Issues</div>
                    </div>
                </div>
            </section>

            <section>
                <h2 className="text-xl font-bold mb-4 border-l-4 border-red-600 pl-3">Top Issues</h2>
                <div className="space-y-2">
                    {/* Mock Issues if audit.issues is empty */}
                    {(audit.issues || []).length === 0 ? <p>No major issues found.</p> : (
                        (audit.issues || []).map((issue: any, i: number) => (
                            <div key={i} className="p-3 border rounded flex justify-between">
                                <span>{issue.message}</span>
                                <span className="font-bold text-red-500">{issue.severity}</span>
                            </div>
                        ))
                    )}
                </div>
            </section>

            <footer className="mt-12 pt-4 border-t text-center text-sm text-gray-400">
                Generated by Project Titan SEO Platform
            </footer>
        </div>
    );
}
