import { type ZoruSidebarGroup } from '@/components/sabcrm/20ui/zoru';
import {
  Activity,
  BarChart,
  Bolt,
  BookCopy,
  Bot,
  Briefcase,
  CalendarClock,
  ClipboardList,
  CreditCard,
  Files,
  GitFork,
  Inbox,
  Key,
  LayoutDashboard,
  ListChecks,
  MessageSquare,
  Phone,
  PhoneCall,
  QrCode,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Tags,
  Timer,
  Users,
  Webhook,
  } from "lucide-react";

/**
 * Wachat sidebar — grouped menu configuration.
 *
 * Drives the per-section nav inside the wachat shell. All hrefs live
 * under `/wachat/*`.
 *
 * Returned shape matches `ZoruSidebarGroup` so the wachat layout can
 * pass it straight to `<ZoruHomeShell sidebarGroups={…} />`.
 */
import * as React from "react";

export function buildWachatSidebarGroups(
  pathname: string | null,
): ZoruSidebarGroup[] {
  const isActive = (href: string, exact = false) => {
    if (!pathname) return false;
    if (exact) return pathname === href;
    return pathname === href || pathname.startsWith(`${href}/`);
  };

  return [
    {
      id: "overview",
      label: "Overview",
      defaultOpen: true,
      items: [
        {
          id: "wachat-root",
          label: "All Projects",
          icon: React.createElement(Briefcase),
          href: "/wachat",
          active: isActive("/wachat", true),
        },
        {
          id: "overview",
          label: "Dashboard",
          icon: React.createElement(LayoutDashboard),
          href: "/wachat/overview",
          active: isActive("/wachat/overview"),
        },
        {
          id: "analytics",
          label: "Analytics",
          icon: React.createElement(BarChart),
          href: "/wachat/analytics",
          active: isActive("/wachat/analytics"),
        },
        {
          id: "health",
          label: "Account Health",
          icon: React.createElement(Activity),
          href: "/wachat/health",
          active: isActive("/wachat/health"),
        },
      ],
    },
    {
      id: "inbox",
      label: "Inbox",
      defaultOpen: true,
      items: [
        {
          id: "live-chat",
          label: "Live Chat",
          icon: React.createElement(MessageSquare),
          href: "/wachat/chat",
          active: isActive("/wachat/chat"),
        },
        {
          id: "kanban",
          label: "Conversation Kanban",
          icon: React.createElement(ListChecks),
          href: "/wachat/conversation-kanban",
          active: isActive("/wachat/conversation-kanban"),
        },
        {
          id: "search",
          label: "Conversation Search",
          icon: React.createElement(Inbox),
          href: "/wachat/conversation-search",
          active: isActive("/wachat/conversation-search"),
        },
        {
          id: "filters",
          label: "Saved Filters",
          icon: React.createElement(Files),
          href: "/wachat/conversation-filters",
          active: isActive("/wachat/conversation-filters"),
        },
        {
          id: "assignments",
          label: "Assignments",
          icon: React.createElement(Users),
          href: "/wachat/assignments",
          active: isActive("/wachat/assignments"),
        },
        {
          id: "agent-availability",
          label: "Agent Availability",
          icon: React.createElement(ShieldCheck),
          href: "/wachat/agent-availability",
          active: isActive("/wachat/agent-availability"),
        },
      ],
    },
    {
      id: "contacts",
      label: "Contacts",
      defaultOpen: false,
      items: [
        {
          id: "contacts",
          label: "Contacts",
          icon: React.createElement(Users),
          href: "/wachat/contacts",
          active: isActive("/wachat/contacts"),
        },
        {
          id: "groups",
          label: "Contact Groups",
          icon: React.createElement(Users),
          href: "/wachat/contact-groups",
          active: isActive("/wachat/contact-groups"),
        },
        {
          id: "blacklist",
          label: "Blacklist",
          icon: React.createElement(ShieldCheck),
          href: "/wachat/contact-blacklist",
          active: isActive("/wachat/contact-blacklist"),
        },
        {
          id: "blocked",
          label: "Blocked Contacts",
          icon: React.createElement(ShieldCheck),
          href: "/wachat/blocked-contacts",
          active: isActive("/wachat/blocked-contacts"),
        },
        {
          id: "import-history",
          label: "Import History",
          icon: React.createElement(Files),
          href: "/wachat/contact-import-history",
          active: isActive("/wachat/contact-import-history"),
        },
        {
          id: "merge",
          label: "Merge Duplicates",
          icon: React.createElement(Users),
          href: "/wachat/contact-merge",
          active: isActive("/wachat/contact-merge"),
        },
        {
          id: "notes",
          label: "Contact Notes",
          icon: React.createElement(BookCopy),
          href: "/wachat/contact-notes",
          active: isActive("/wachat/contact-notes"),
        },
        {
          id: "timeline",
          label: "Contact Timeline",
          icon: React.createElement(CalendarClock),
          href: "/wachat/contact-timeline",
          active: isActive("/wachat/contact-timeline"),
        },
      ],
    },
    {
      id: "broadcasts",
      label: "Broadcasts",
      defaultOpen: false,
      items: [
        {
          id: "campaigns",
          label: "Campaigns",
          icon: React.createElement(Send),
          href: "/wachat/broadcasts",
          active: isActive("/wachat/broadcasts"),
        },
        {
          id: "history",
          label: "Broadcast History",
          icon: React.createElement(Files),
          href: "/wachat/broadcast-history",
          active: isActive("/wachat/broadcast-history"),
        },
        {
          id: "scheduler",
          label: "Scheduler",
          icon: React.createElement(CalendarClock),
          href: "/wachat/broadcast-scheduler",
          active: isActive("/wachat/broadcast-scheduler"),
        },
        {
          id: "broadcast-cron",
          label: "Broadcast Cron",
          icon: React.createElement(Timer),
          href: "/wachat/broadcast-cron",
          active: isActive("/wachat/broadcast-cron"),
        },
        {
          id: "segments",
          label: "Audience Segments",
          icon: React.createElement(Users),
          href: "/wachat/broadcast-segments",
          active: isActive("/wachat/broadcast-segments"),
        },
        {
          id: "ab-test",
          label: "A/B Testing",
          icon: React.createElement(Sparkles),
          href: "/wachat/campaign-ab-test",
          active: isActive("/wachat/campaign-ab-test"),
        },
        {
          id: "scheduled",
          label: "Scheduled Messages",
          icon: React.createElement(CalendarClock),
          href: "/wachat/scheduled-messages",
          active: isActive("/wachat/scheduled-messages"),
        },
        {
          id: "bulk",
          label: "Bulk Send",
          icon: React.createElement(Send),
          href: "/wachat/bulk",
          active: isActive("/wachat/bulk"),
        },
        {
          id: "bulk-messaging",
          label: "Bulk Messaging",
          icon: React.createElement(Send),
          href: "/wachat/bulk-messaging",
          active: isActive("/wachat/bulk-messaging"),
        },
      ],
    },
    {
      id: "templates",
      label: "Templates & Messages",
      defaultOpen: false,
      items: [
        {
          id: "templates",
          label: "Templates",
          icon: React.createElement(BookCopy),
          href: "/wachat/templates",
          active: isActive("/wachat/templates"),
        },
        {
          id: "library",
          label: "Template Library",
          icon: React.createElement(BookCopy),
          href: "/wachat/message-templates-library",
          active: isActive("/wachat/message-templates-library"),
        },
        {
          id: "template-builder",
          label: "Template Builder",
          icon: React.createElement(BookCopy),
          href: "/wachat/template-builder",
          active: isActive("/wachat/template-builder"),
        },
        {
          id: "template-analytics",
          label: "Template Analytics",
          icon: React.createElement(BarChart),
          href: "/wachat/template-analytics",
          active: isActive("/wachat/template-analytics"),
        },
        {
          id: "saved-replies",
          label: "Saved Replies",
          icon: React.createElement(MessageSquare),
          href: "/wachat/saved-replies",
          active: isActive("/wachat/saved-replies"),
        },
        {
          id: "canned",
          label: "Canned Messages",
          icon: React.createElement(MessageSquare),
          href: "/wachat/canned-messages",
          active: isActive("/wachat/canned-messages"),
        },
        {
          id: "quick-reply-categories",
          label: "Quick Reply Categories",
          icon: React.createElement(Tags),
          href: "/wachat/quick-reply-categories",
          active: isActive("/wachat/quick-reply-categories"),
        },
        {
          id: "interactive",
          label: "Interactive Messages",
          icon: React.createElement(Sparkles),
          href: "/wachat/templates/interactive-message-builder",
          active: isActive("/wachat/templates/interactive-message-builder"),
        },
        {
          id: "tags",
          label: "Message Tags",
          icon: React.createElement(Tags),
          href: "/wachat/message-tags",
          active: isActive("/wachat/message-tags"),
        },
      ],
    },
    {
      id: "automation",
      label: "Automation",
      defaultOpen: false,
      items: [
        {
          id: "auto-reply",
          label: "Auto Reply",
          icon: React.createElement(MessageSquare),
          href: "/wachat/auto-reply",
          active: isActive("/wachat/auto-reply"),
        },
        {
          id: "auto-reply-rules",
          label: "Auto Reply Rules",
          icon: React.createElement(ListChecks),
          href: "/wachat/auto-reply-rules",
          active: isActive("/wachat/auto-reply-rules"),
        },
        {
          id: "automation",
          label: "Conversational AI",
          icon: React.createElement(Bot),
          href: "/wachat/automation",
          active: isActive("/wachat/automation"),
        },
        {
          id: "chatbot",
          label: "Chatbot",
          icon: React.createElement(Bot),
          href: "/wachat/chatbot",
          active: isActive("/wachat/chatbot"),
        },
        {
          id: "greeting",
          label: "Greeting Messages",
          icon: React.createElement(Sparkles),
          href: "/wachat/greeting-messages",
          active: isActive("/wachat/greeting-messages"),
        },
        {
          id: "away",
          label: "Away Messages",
          icon: React.createElement(MessageSquare),
          href: "/wachat/away-messages",
          active: isActive("/wachat/away-messages"),
        },
        {
          id: "business-hours",
          label: "Business Hours",
          icon: React.createElement(CalendarClock),
          href: "/wachat/business-hours",
          active: isActive("/wachat/business-hours"),
        },
        {
          id: "flow-builder",
          label: "Flow Builder",
          icon: React.createElement(GitFork),
          href: "/wachat/flow-builder",
          active: isActive("/wachat/flow-builder"),
        },
        {
          id: "meta-flows",
          label: "Meta Flows",
          icon: React.createElement(GitFork),
          href: "/wachat/flows",
          active: isActive("/wachat/flows"),
        },
      ],
    },
    {
      id: "reports",
      label: "Reports",
      defaultOpen: false,
      items: [
        {
          id: "msg-analytics",
          label: "Message Analytics",
          icon: React.createElement(BarChart),
          href: "/wachat/message-analytics",
          active: isActive("/wachat/message-analytics"),
        },
        {
          id: "msg-stats",
          label: "Message Statistics",
          icon: React.createElement(BarChart),
          href: "/wachat/message-statistics",
          active: isActive("/wachat/message-statistics"),
        },
        {
          id: "delivery",
          label: "Delivery Reports",
          icon: React.createElement(ClipboardList),
          href: "/wachat/delivery-reports",
          active: isActive("/wachat/delivery-reports"),
        },
        {
          id: "response-time",
          label: "Response Time",
          icon: React.createElement(Activity),
          href: "/wachat/response-time-tracker",
          active: isActive("/wachat/response-time-tracker"),
        },
        {
          id: "csat",
          label: "Customer Satisfaction",
          icon: React.createElement(Sparkles),
          href: "/wachat/customer-satisfaction",
          active: isActive("/wachat/customer-satisfaction"),
        },
        {
          id: "team",
          label: "Team Performance",
          icon: React.createElement(Users),
          href: "/wachat/team-performance",
          active: isActive("/wachat/team-performance"),
        },
        {
          id: "link-tracking",
          label: "Link Tracking",
          icon: React.createElement(BarChart),
          href: "/wachat/link-tracking",
          active: isActive("/wachat/link-tracking"),
        },
      ],
    },
    {
      id: "growth",
      label: "Growth Tools",
      defaultOpen: false,
      items: [
        {
          id: "catalog",
          label: "Catalog",
          icon: React.createElement(ShoppingBag),
          href: "/wachat/catalog",
          active: isActive("/wachat/catalog"),
        },
        {
          id: "whatsapp-pay",
          label: "WhatsApp Pay",
          icon: React.createElement(CreditCard),
          href: "/wachat/whatsapp-pay",
          active: isActive("/wachat/whatsapp-pay"),
        },
        {
          id: "qr-codes",
          label: "QR Codes",
          icon: React.createElement(QrCode),
          href: "/wachat/qr-codes",
          active: isActive("/wachat/qr-codes"),
        },
        {
          id: "wa-link-gen",
          label: "Link Generator",
          icon: React.createElement(Sparkles),
          href: "/wachat/whatsapp-link-generator",
          active: isActive("/wachat/whatsapp-link-generator"),
        },
        {
          id: "whatsapp-ads",
          label: "WhatsApp Ads",
          icon: React.createElement(Sparkles),
          href: "/wachat/whatsapp-ads",
          active: isActive("/wachat/whatsapp-ads"),
        },
        {
          id: "post-generator",
          label: "Post Generator",
          icon: React.createElement(Sparkles),
          href: "/wachat/post-generator",
          active: isActive("/wachat/post-generator"),
        },
      ],
    },
    {
      id: "phone",
      label: "Calling & Numbers",
      defaultOpen: false,
      items: [
        {
          id: "numbers",
          label: "Numbers",
          icon: React.createElement(Phone),
          href: "/wachat/numbers",
          active: isActive("/wachat/numbers"),
        },
        {
          id: "phone-settings",
          label: "Phone Number Settings",
          icon: React.createElement(Settings),
          href: "/wachat/phone-number-settings",
          active: isActive("/wachat/phone-number-settings"),
        },
        {
          id: "two-line",
          label: "Two-Line",
          icon: React.createElement(Phone),
          href: "/wachat/two-line",
          active: isActive("/wachat/two-line"),
        },
        {
          id: "calls",
          label: "Calls",
          icon: React.createElement(PhoneCall),
          href: "/wachat/calls",
          active: isActive("/wachat/calls"),
        },
        {
          id: "media-library",
          label: "Media Library",
          icon: React.createElement(Files),
          href: "/wachat/media-library",
          active: isActive("/wachat/media-library"),
        },
      ],
    },
    {
      id: "engagement",
      label: "Engagement",
      defaultOpen: false,
      items: [
        {
          id: "chat-export",
          label: "Chat Export",
          icon: React.createElement(Files),
          href: "/wachat/chat-export",
          active: isActive("/wachat/chat-export"),
        },
        {
          id: "chat-labels",
          label: "Chat Labels",
          icon: React.createElement(Tags),
          href: "/wachat/chat-labels",
          active: isActive("/wachat/chat-labels"),
        },
        {
          id: "chat-ratings",
          label: "Chat Ratings",
          icon: React.createElement(Sparkles),
          href: "/wachat/chat-ratings",
          active: isActive("/wachat/chat-ratings"),
        },
        {
          id: "chat-transfer",
          label: "Chat Transfer",
          icon: React.createElement(Users),
          href: "/wachat/chat-transfer",
          active: isActive("/wachat/chat-transfer"),
        },
        {
          id: "conv-summary",
          label: "Conversation Summary",
          icon: React.createElement(BookCopy),
          href: "/wachat/conversation-summary",
          active: isActive("/wachat/conversation-summary"),
        },
        {
          id: "opt-out",
          label: "Opt-out",
          icon: React.createElement(ShieldCheck),
          href: "/wachat/opt-out",
          active: isActive("/wachat/opt-out"),
        },
      ],
    },
    {
      id: "settings",
      label: "Settings",
      defaultOpen: false,
      items: [
        {
          id: "general",
          label: "General Settings",
          icon: React.createElement(Settings),
          href: "/wachat/settings/general",
          active: isActive("/wachat/settings/general"),
        },
        {
          id: "agents",
          label: "Agents & Roles",
          icon: React.createElement(Users),
          href: "/wachat/settings/agents",
          active: isActive("/wachat/settings/agents"),
        },
        {
          id: "attributes",
          label: "User Attributes",
          icon: React.createElement(Key),
          href: "/wachat/settings/attributes",
          active: isActive("/wachat/settings/attributes"),
        },
        {
          id: "canned-settings",
          label: "Canned Settings",
          icon: React.createElement(BookCopy),
          href: "/wachat/settings/canned",
          active: isActive("/wachat/settings/canned"),
        },
        {
          id: "webhooks",
          label: "Webhooks",
          icon: React.createElement(Webhook),
          href: "/wachat/webhooks",
          active: isActive("/wachat/webhooks"),
        },
        {
          id: "webhook-logs",
          label: "Webhook Logs",
          icon: React.createElement(ClipboardList),
          href: "/wachat/webhook-logs",
          active: isActive("/wachat/webhook-logs"),
        },
        {
          id: "integrations",
          label: "Integrations",
          icon: React.createElement(Bolt),
          href: "/wachat/integrations",
          active: isActive("/wachat/integrations"),
        },
      ],
    },
  ];
}
