// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { createContact, listContacts } from './_handlers';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// List contacts (cursor paginated)  (scope: contacts:read, tier: FREE)
export const GET = withApiV1(listContacts, { scope: 'contacts:read' });

// Create a contact  (scope: contacts:write, tier: FREE)
export const POST = withApiV1(createContact, { scope: 'contacts:write' });
