// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Read the contacts kanban board  (scope: contacts:read, tier: FREE)
export const GET = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/contacts/kanban${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'GET',
    },
  );
  return NextResponse.json(data);
}, { scope: 'contacts:read' });
