//! Wire-format DTOs for the SabChat AI copilot endpoints.
//!
//! Every request / response uses `#[serde(rename_all = "camelCase")]` to
//! match the JSON shape the Next.js side already speaks.
//!
//! Each LLM-backed response carries the model name and token usage so
//! the agent UI can display a "powered by …" footer and so we can wire
//! up billing / quota reporting once a real provider replaces the
//! stub.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use utoipa::ToSchema;

// ---------------------------------------------------------------------------
// `POST /v1/sabchat/ai/copilot/draft`
// ---------------------------------------------------------------------------

/// Body for `POST /draft`. The optional `hint` lets the agent steer the
/// suggestion (e.g. "ask for the order id", "be apologetic").
#[derive(Debug, Clone, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct DraftRequest {
    /// Hex `ObjectId` string identifying the target conversation.
    pub conversation_id: String,
    /// Optional natural-language steer for the LLM.
    #[serde(default)]
    pub hint: Option<String>,
}

/// Response for `POST /draft`.
#[derive(Debug, Clone, Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct DraftResponse {
    /// Suggested reply body. Plain text — the agent UI is responsible
    /// for any markdown / mention parsing.
    pub draft: String,
    /// Model identifier returned by the LLM client (e.g. `stub-v0`,
    /// `gpt-4o-mini`, `claude-3-5-sonnet`).
    pub model: String,
    /// Tokens read by the model on this call.
    pub tokens_in: u32,
    /// Tokens generated by the model on this call.
    pub tokens_out: u32,
}

// ---------------------------------------------------------------------------
// `POST /v1/sabchat/ai/copilot/summarize`
// ---------------------------------------------------------------------------

/// Body for `POST /summarize`.
#[derive(Debug, Clone, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SummarizeRequest {
    pub conversation_id: String,
}

/// Response for `POST /summarize`.
#[derive(Debug, Clone, Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SummarizeResponse {
    /// Free-form short summary of the conversation.
    pub summary: String,
    pub model: String,
    pub tokens_in: u32,
    pub tokens_out: u32,
}

// ---------------------------------------------------------------------------
// `POST /v1/sabchat/ai/copilot/suggest-actions`
// ---------------------------------------------------------------------------

/// Body for `POST /suggest-actions`.
#[derive(Debug, Clone, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SuggestActionsRequest {
    pub conversation_id: String,
}

/// Suggested operational action returned by the copilot. The kind
/// taxonomy is small on purpose — the agent UI maps these to existing
/// buttons / shortcuts.
#[derive(Debug, Clone, Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SuggestedAction {
    /// `label` | `escalate` | `resolve` | `reply`.
    pub kind: String,
    /// Short human-readable title for the suggestion (e.g. "Apply
    /// `vip` label", "Send a closing thanks").
    pub title: String,
    /// Action-specific payload. For `label` this is `{ label: "vip" }`,
    /// for `reply` `{ draft: "..." }`, for `escalate`
    /// `{ team: "billing" }`, for `resolve` `{}`. Kept opaque so the
    /// taxonomy can grow without breaking the schema.
    #[serde(default)]
    #[schema(value_type = Object)]
    pub payload: Value,
}

/// Response for `POST /suggest-actions`.
#[derive(Debug, Clone, Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct SuggestActionsResponse {
    pub actions: Vec<SuggestedAction>,
}

// ---------------------------------------------------------------------------
// `POST /v1/sabchat/ai/copilot/wrap-up`
// ---------------------------------------------------------------------------

/// Body for `POST /wrap-up`.
#[derive(Debug, Clone, Deserialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct WrapUpRequest {
    pub conversation_id: String,
}

/// Response for `POST /wrap-up`. The note is intended for the internal
/// audit trail — the calling UI is responsible for persisting it onto
/// the conversation if the agent accepts the suggestion.
#[derive(Debug, Clone, Serialize, ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct WrapUpResponse {
    pub note: String,
}
