import "server-only";

import { Collection, ObjectId } from "mongodb";
import { connectToDatabase } from "@/lib/mongodb";

// PORT-NOTE: Translated from TypeORM entity (Postgres) to MongoDB document type.
// Original indexes:
//   UQ_upgrade_migration_instance: unique on (name, attempt) where workspaceId IS NULL
//   UQ_upgrade_migration_workspace: unique on (name, attempt, workspaceId) where workspaceId IS NOT NULL
//   IDX_UPGRADE_MIGRATION_WORKSPACE_ID_NAME_ATTEMPT: on (workspaceId, name, attempt) where workspaceId IS NOT NULL
// Collection name: sabcrm_upgradeMigration

export type UpgradeMigrationStatus = "completed" | "failed";

export type UpgradeMigrationDocument = {
  _id?: ObjectId;
  /** UUID string — generated by caller */
  id: string;
  name: string;
  status: UpgradeMigrationStatus;
  /** default: 1 */
  attempt: number;
  executedByVersion: string;
  errorMessage: string | null;
  /** default: false — when true this record represents an "initial" activation, not execution progress */
  isInitial: boolean;
  /** null for instance-scoped records */
  workspaceId: string | null;
  createdAt: Date;
};

const COLLECTION_NAME = "sabcrm_upgradeMigration";

export async function getUpgradeMigrationCollection(): Promise<
  Collection<UpgradeMigrationDocument>
> {
  const { db } = await connectToDatabase();
  return db.collection<UpgradeMigrationDocument>(COLLECTION_NAME);
}

/** Call once at application bootstrap to ensure required indexes exist. */
export async function ensureUpgradeMigrationIndexes(): Promise<void> {
  const col = await getUpgradeMigrationCollection();

  await col.createIndex(
    { name: 1, attempt: 1 },
    {
      unique: true,
      partialFilterExpression: { workspaceId: null },
      name: "UQ_upgrade_migration_instance",
    },
  );

  await col.createIndex(
    { name: 1, attempt: 1, workspaceId: 1 },
    {
      unique: true,
      partialFilterExpression: { workspaceId: { $ne: null } },
      name: "UQ_upgrade_migration_workspace",
    },
  );

  await col.createIndex(
    { workspaceId: 1, name: 1, attempt: 1 },
    {
      partialFilterExpression: { workspaceId: { $ne: null } },
      name: "IDX_UPGRADE_MIGRATION_WORKSPACE_ID_NAME_ATTEMPT",
    },
  );
}
