/**
 * Structural drift tests for the developer-API codegen.
 *
 * Runs with `tsx --test` (no DB / Redis required). Three things are
 * checked:
 *
 *   1. Every manifest endpoint has a corresponding `route.ts` on disk.
 *   2. Every `route.ts` under `src/app/api/v1/**` that carries the
 *      `@generated` header maps back to a manifest entry — so deletions
 *      and renames in the manifest don't leave orphan routes behind.
 *   3. Every generated `route.ts` exports the right HTTP method symbols
 *      and uses `withApiV1` — guards against accidental hand-edits.
 *
 * Hand-written routes that PREDATE the manifest are recognised by the
 * absence of the `@generated` header and are skipped — that lets the
 * 13 legacy `/api/v1/*` routes coexist with the generated 4 during the
 * Phase 0 → Phase 1 migration window.
 */

import { readFileSync, readdirSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { test } from 'node:test';
import assert from 'node:assert/strict';

import { manifest } from '../../api-manifest/index';
import type { EndpointSpec } from '../../api-manifest/types';
import { pathToFolder } from '../util';

const REPO_ROOT = resolve(new URL('../../..', import.meta.url).pathname);
const V1_ROOT = resolve(REPO_ROOT, 'src/app/api/v1');
const GENERATED_MARKER = '// @generated by tools/api-codegen';

/* ── Filesystem walk ────────────────────────────────────────────────────── */

function findRouteFiles(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = resolve(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) findRouteFiles(full, out);
    else if (entry === 'route.ts') out.push(full);
  }
  return out;
}

const allRouteFiles = findRouteFiles(V1_ROOT);
const generatedRouteFiles = allRouteFiles.filter((p) =>
  readFileSync(p, 'utf8').startsWith(GENERATED_MARKER),
);

/* ── Helpers ────────────────────────────────────────────────────────────── */

function expectedRoutePathFor(spec: EndpointSpec): string {
  return resolve(V1_ROOT, pathToFolder(spec.path), 'route.ts');
}

function specsByFolder(): Map<string, EndpointSpec[]> {
  const m = new Map<string, EndpointSpec[]>();
  for (const spec of manifest.endpoints) {
    const folder = pathToFolder(spec.path);
    const existing = m.get(folder);
    if (existing) existing.push(spec);
    else m.set(folder, [spec]);
  }
  return m;
}

/* ── Test cases ─────────────────────────────────────────────────────────── */

test('every manifest endpoint has a generated route file', () => {
  for (const spec of manifest.endpoints) {
    const expected = expectedRoutePathFor(spec);
    assert.ok(
      generatedRouteFiles.includes(expected),
      `Missing generated route file for ${spec.method} ${spec.path} ` +
        `(expected ${expected}). Run \`pnpm api:gen\`.`,
    );
  }
});

test('every generated route file maps back to a manifest entry', () => {
  const folders = specsByFolder();
  for (const routeFile of generatedRouteFiles) {
    const rel = routeFile.slice(V1_ROOT.length + 1).replace(/\/route\.ts$/, '');
    assert.ok(
      folders.has(rel),
      `Generated route file at ${routeFile} has no matching manifest entry. ` +
        'Either remove the file or restore the spec in tools/api-manifest/.',
    );
  }
});

test('every generated route uses withApiV1 + has the right method exports', () => {
  const folders = specsByFolder();
  for (const routeFile of generatedRouteFiles) {
    const body = readFileSync(routeFile, 'utf8');
    assert.match(
      body,
      /from '@\/lib\/api-platform'/,
      `${routeFile}: missing import from @/lib/api-platform`,
    );
    assert.match(body, /withApiV1\(/, `${routeFile}: must call withApiV1`);
    assert.match(
      body,
      /export const runtime = 'nodejs'/,
      `${routeFile}: must declare runtime = 'nodejs'`,
    );

    const folder = routeFile.slice(V1_ROOT.length + 1).replace(/\/route\.ts$/, '');
    const specs = folders.get(folder) ?? [];
    for (const spec of specs) {
      const re = new RegExp(`export const ${spec.method}\\s*=`);
      assert.match(
        body,
        re,
        `${routeFile}: missing export for ${spec.method} (manifest declares it)`,
      );
    }
  }
});

test('the generated openapi-paths.ts is up to date', () => {
  const generatedPath = resolve(REPO_ROOT, 'src/lib/api-platform/_generated/openapi-paths.ts');
  const body = readFileSync(generatedPath, 'utf8');
  assert.ok(body.startsWith(GENERATED_MARKER), 'openapi-paths.ts missing @generated header');
  // Spot-check: every manifest path is present somewhere in the dumped JSON.
  for (const spec of manifest.endpoints) {
    const openApiKey = spec.path.replace(/\[([^\]]+)\]/g, '{$1}');
    assert.ok(
      body.includes(`"${openApiKey}"`),
      `openapi-paths.ts is missing path '${openApiKey}'. Run \`pnpm api:gen\`.`,
    );
  }
});
