/**
 * WhatsApp broadcast surface. Forwards to the `wachat-broadcast` crate.
 */

import type { EndpointSpec } from '../types';

export const broadcastsEndpoints: ReadonlyArray<EndpointSpec> = [
  {
    module: 'broadcasts',
    resource: 'broadcasts',
    verb: 'custom',
    path: '/broadcasts/start',
    method: 'POST',
    scope: 'broadcasts:write',
    tier: 'PRO',
    summary: 'Start a broadcast campaign',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Broadcast queued', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/broadcast/api-start', method: 'POST' },
    emits: ['wachat.broadcast.started'],
    idempotent: true,
  },
  {
    module: 'broadcasts',
    resource: 'broadcasts',
    verb: 'custom',
    path: '/broadcasts/bulk-start',
    method: 'POST',
    scope: 'broadcasts:write',
    tier: 'PRO',
    summary: 'Start multiple broadcasts in one call',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Bulk queued', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/broadcast/bulk-start', method: 'POST' },
    emits: ['wachat.broadcast.started'],
    idempotent: true,
  },
  {
    module: 'broadcasts',
    resource: 'broadcasts',
    verb: 'get',
    path: '/broadcasts/[broadcastId]',
    method: 'GET',
    scope: 'broadcasts:read',
    tier: 'FREE',
    summary: 'Fetch a broadcast',
    pathParams: [{ name: 'broadcastId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Broadcast', schema: { type: 'object' } },
      '401': { description: 'Missing or invalid API key' },
      '404': { description: 'Not found' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/broadcast/{broadcastId}', method: 'GET' },
  },
  {
    module: 'broadcasts',
    resource: 'broadcasts',
    verb: 'list',
    path: '/broadcasts/[broadcastId]/logs',
    method: 'GET',
    scope: 'broadcasts:read',
    tier: 'FREE',
    summary: 'List per-recipient delivery logs for a broadcast',
    pathParams: [{ name: 'broadcastId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Log page', schema: { type: 'object' } },
      '401': { description: 'Missing or invalid API key' },
      '404': { description: 'Not found' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/broadcast/{broadcastId}/logs', method: 'GET' },
  },
  {
    module: 'broadcasts',
    resource: 'broadcasts',
    verb: 'custom',
    path: '/broadcasts/[broadcastId]/requeue',
    method: 'POST',
    scope: 'broadcasts:write',
    tier: 'PRO',
    summary: 'Requeue failed recipients for delivery retry',
    pathParams: [{ name: 'broadcastId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Requeued', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '401': { description: 'Missing or invalid API key' },
      '404': { description: 'Not found' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/broadcast/{broadcastId}/requeue', method: 'POST' },
  },
  {
    module: 'broadcasts',
    resource: 'broadcasts',
    verb: 'custom',
    path: '/broadcasts/[broadcastId]/stop',
    method: 'POST',
    scope: 'broadcasts:write',
    tier: 'PRO',
    summary: 'Stop a running broadcast',
    pathParams: [{ name: 'broadcastId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Stopped', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '401': { description: 'Missing or invalid API key' },
      '404': { description: 'Not found' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/broadcast/{broadcastId}/stop', method: 'POST' },
    emits: ['wachat.broadcast.stopped'],
  },
];
