/**
 * CRM sales & procurement surface — quotations, invoices, sales orders,
 * purchase orders, receipts, notes (credit/debit), payouts, bills, RFQs,
 * vendor bids, GRNs, proforma invoices, delivery challans, contracts,
 * coupons, gift cards, loyalty programs, subscriptions, vendors.
 */

import type { EndpointSpec } from '../types';
import { crudResource } from '../crud-template';

export const crmSalesEndpoints: ReadonlyArray<EndpointSpec> = [
  ...crudResource({
    module: 'crm',
    resource: 'quotations',
    basePath: '/crm/quotations',
    rustPath: '/v1/crm/quotations',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    emits: { create: 'crm.quotation.created' },
  }),
  ...crudResource({
    module: 'crm',
    resource: 'invoices',
    basePath: '/crm/invoices',
    rustPath: '/v1/crm/invoices',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    emits: { create: 'crm.invoice.created', update: 'crm.invoice.updated' },
  }),
  ...crudResource({
    module: 'crm',
    resource: 'proforma-invoices',
    basePath: '/crm/proforma-invoices',
    rustPath: '/v1/crm/proforma-invoices',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'proformaInvoiceId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'sales-orders',
    basePath: '/crm/sales-orders',
    rustPath: '/v1/crm/sales-orders',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'salesOrderId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'purchase-orders',
    basePath: '/crm/purchase-orders',
    rustPath: '/v1/crm/purchase-orders',
    scopeRead: 'crm:purchases:read',
    scopeWrite: 'crm:purchases:write',
    idParam: 'purchaseOrderId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'payment-receipts',
    basePath: '/crm/payment-receipts',
    rustPath: '/v1/crm/payment-receipts',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'paymentReceiptId',
    emits: { create: 'crm.payment.received' },
  }),
  ...crudResource({
    module: 'crm',
    resource: 'credit-notes',
    basePath: '/crm/credit-notes',
    rustPath: '/v1/crm/credit-notes',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'creditNoteId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'debit-notes',
    basePath: '/crm/debit-notes',
    rustPath: '/v1/crm/debit-notes',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'debitNoteId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'payouts',
    basePath: '/crm/payouts',
    rustPath: '/v1/crm/payouts',
    scopeRead: 'crm:accounting:read',
    scopeWrite: 'crm:accounting:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'bills',
    basePath: '/crm/bills',
    rustPath: '/v1/crm/bills',
    scopeRead: 'crm:purchases:read',
    scopeWrite: 'crm:purchases:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'rfqs',
    basePath: '/crm/rfqs',
    rustPath: '/v1/crm/rfqs',
    scopeRead: 'crm:purchases:read',
    scopeWrite: 'crm:purchases:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'vendor-bids',
    basePath: '/crm/vendor-bids',
    rustPath: '/v1/crm/vendor-bids',
    scopeRead: 'crm:purchases:read',
    scopeWrite: 'crm:purchases:write',
    idParam: 'vendorBidId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'grns',
    basePath: '/crm/grns',
    rustPath: '/v1/crm/grns',
    scopeRead: 'crm:purchases:read',
    scopeWrite: 'crm:purchases:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'delivery-challans',
    basePath: '/crm/delivery-challans',
    rustPath: '/v1/crm/delivery-challans',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'deliveryChallanId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'service-contracts',
    basePath: '/crm/service-contracts',
    rustPath: '/v1/crm/service-contracts',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
    idParam: 'serviceContractId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'contracts',
    basePath: '/crm/contracts',
    rustPath: '/v1/crm/contracts',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'coupons',
    basePath: '/crm/coupons',
    rustPath: '/v1/crm/coupons',
    scopeRead: 'crm:marketing:read',
    scopeWrite: 'crm:marketing:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'gift-cards',
    basePath: '/crm/gift-cards',
    rustPath: '/v1/crm/gift-cards',
    scopeRead: 'crm:marketing:read',
    scopeWrite: 'crm:marketing:write',
    idParam: 'giftCardId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'loyalty-programs',
    basePath: '/crm/loyalty-programs',
    rustPath: '/v1/crm/loyalty-programs',
    scopeRead: 'crm:marketing:read',
    scopeWrite: 'crm:marketing:write',
    idParam: 'loyaltyProgramId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'subscriptions',
    basePath: '/crm/subscriptions',
    rustPath: '/v1/crm/subscriptions',
    scopeRead: 'crm:sales:read',
    scopeWrite: 'crm:sales:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'vendors',
    basePath: '/crm/vendors',
    rustPath: '/v1/crm/vendors',
    scopeRead: 'crm:purchases:read',
    scopeWrite: 'crm:purchases:write',
  }),
];
