/**
 * CRM performance + projects + content — appraisals, goals, OKRs, KPIs,
 * 1-on-1s, succession, awards, tasks, subtasks, tickets, SLAs, KB
 * articles, forms, form submissions, careers pages, portal users,
 * announcements, dashboards.
 */

import type { EndpointSpec } from '../types';
import { crudResource } from '../crud-template';

export const crmPerformanceEndpoints: ReadonlyArray<EndpointSpec> = [
  ...crudResource({
    module: 'crm',
    resource: 'appraisals',
    basePath: '/crm/appraisals',
    rustPath: '/v1/crm/appraisals',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'goals',
    basePath: '/crm/goals',
    rustPath: '/v1/crm/goals',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'okrs',
    basePath: '/crm/okrs',
    rustPath: '/v1/crm/okrs',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
    idParam: 'okrId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'kpis',
    basePath: '/crm/kpis',
    rustPath: '/v1/crm/kpis',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
    idParam: 'kpiId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'one-on-ones',
    basePath: '/crm/one-on-ones',
    rustPath: '/v1/crm/one-on-ones',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
    idParam: 'oneOnOneId',
    display: '1-on-1 meetings',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'succession',
    basePath: '/crm/succession',
    rustPath: '/v1/crm/succession',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
    idParam: 'successionId',
    display: 'succession plans',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'awards',
    basePath: '/crm/awards',
    rustPath: '/v1/crm/awards',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'tasks',
    basePath: '/crm/tasks',
    rustPath: '/v1/crm/tasks',
    scopeRead: 'crm:projects:read',
    scopeWrite: 'crm:projects:write',
    emits: { create: 'crm.task.created', update: 'crm.task.updated' },
  }),
  ...crudResource({
    module: 'crm',
    resource: 'tickets',
    basePath: '/crm/tickets',
    rustPath: '/v1/crm/tickets',
    scopeRead: 'crm:support:read',
    scopeWrite: 'crm:support:write',
    emits: { create: 'crm.ticket.created', update: 'crm.ticket.updated' },
  }),
  ...crudResource({
    module: 'crm',
    resource: 'slas',
    basePath: '/crm/slas',
    rustPath: '/v1/crm/slas',
    scopeRead: 'crm:support:read',
    scopeWrite: 'crm:support:write',
    idParam: 'slaId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'kb-articles',
    basePath: '/crm/kb-articles',
    rustPath: '/v1/crm/kb-articles',
    scopeRead: 'crm:content:read',
    scopeWrite: 'crm:content:write',
    idParam: 'kbArticleId',
    display: 'knowledge base articles',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'forms',
    basePath: '/crm/forms',
    rustPath: '/v1/crm/forms',
    scopeRead: 'crm:content:read',
    scopeWrite: 'crm:content:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'form-submissions',
    basePath: '/crm/form-submissions',
    rustPath: '/v1/crm/form-submissions',
    scopeRead: 'crm:content:read',
    scopeWrite: 'crm:content:write',
    idParam: 'formSubmissionId',
    verbs: ['list', 'get'],
  }),
  ...crudResource({
    module: 'crm',
    resource: 'portal-users',
    basePath: '/crm/portal-users',
    rustPath: '/v1/crm/portal-users',
    scopeRead: 'crm:portal:read',
    scopeWrite: 'crm:portal:write',
    idParam: 'portalUserId',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'announcements',
    basePath: '/crm/announcements',
    rustPath: '/v1/crm/announcements',
    scopeRead: 'crm:content:read',
    scopeWrite: 'crm:content:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'dashboards',
    basePath: '/crm/dashboards',
    rustPath: '/v1/crm/dashboards',
    scopeRead: 'crm:analytics:read',
    scopeWrite: 'crm:analytics:write',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'disciplinary',
    basePath: '/crm/disciplinary',
    rustPath: '/v1/crm/disciplinary',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
    idParam: 'disciplinaryId',
    display: 'disciplinary actions',
  }),
  ...crudResource({
    module: 'crm',
    resource: 'exits',
    basePath: '/crm/exits',
    rustPath: '/v1/crm/exits',
    scopeRead: 'crm:hr:read',
    scopeWrite: 'crm:hr:write',
  }),
];
