/**
 * Wachat "completion + growth" surface — the eight finished Rust crates that
 * back the link-generator, chat-widget tracking, OAuth integrations hub,
 * Razorpay payments, the ads-integration roadmap, the AI post-generator, the
 * setup knowledge base, and contacts export/sync.
 *
 * Every endpoint is a pure passthrough via `rust-fwd` (forwarded as the
 * authenticated user through `rustFetchAsUser`), exactly like
 * `wachat-extras.ts`. The public `path` mirrors the Rust mount path minus the
 * leading `/v1` — e.g. the link-generator crate mounted at
 * `/v1/wachat/link-generator` is exposed at `/wachat/link-generator`.
 *
 * Scopes are reused from the existing `wachat:*` / `contacts:*` sets — no new
 * scope is introduced (that would mutate the generated `OAuthScope` union).
 * GETs take a `:read` scope; mutations take a `:write` scope. Sensitive
 * mutations (Razorpay payment-links) are gated at tier `PRO`, mirroring the
 * sibling `pay`/`catalog` examples.
 */

import type { EndpointSpec } from '../types';

const generic2xx = { description: 'OK', schema: { type: 'object' as const } };
const auth = {
  '401': { description: 'Missing or invalid API key' },
  '429': { description: 'Rate limit exceeded' },
};

export const wachatCompletionGrowthEndpoints: ReadonlyArray<EndpointSpec> = [
  /* ── Link generator (/v1/wachat/link-generator) ───────────────────────── */
  {
    module: 'wachat',
    resource: 'link-generator',
    verb: 'custom',
    path: '/wachat/link-generator/shorten',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Shorten a wa.me / arbitrary link via the internal shortener',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/link-generator/shorten', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'link-generator',
    verb: 'list',
    path: '/wachat/link-generator/projects/[projectId]/links',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List saved WhatsApp links for a project',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/link-generator/projects/{projectId}/links', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'link-generator',
    verb: 'create',
    path: '/wachat/link-generator/projects/[projectId]/links',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Save a WhatsApp link for a project',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/link-generator/projects/{projectId}/links', method: 'POST' },
  },

  /* ── Chat-widget tracking (/v1/wachat/widget) ─────────────────────────── */
  {
    module: 'wachat',
    resource: 'widget',
    verb: 'get',
    path: '/wachat/widget/[projectId]/stats',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Read chat-widget analytics (loads / opens / clicks) for a project',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/widget/{projectId}/stats', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'widget',
    verb: 'custom',
    path: '/wachat/widget/[projectId]/track',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Record a chat-widget event (load / open / click)',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/widget/{projectId}/track', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'widget',
    verb: 'update',
    path: '/wachat/widget/[projectId]/advanced-settings',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update advanced chat-widget behaviour settings for a project',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/widget/{projectId}/advanced-settings', method: 'PUT' },
  },

  /* ── Integrations hub (/v1/wachat/integrations) ───────────────────────── */
  {
    module: 'wachat',
    resource: 'integrations',
    verb: 'list',
    path: '/wachat/integrations/oauth',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List connected OAuth providers for the tenant',
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/integrations/oauth', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'integrations',
    verb: 'custom',
    path: '/wachat/integrations/oauth/[provider]/connect',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Record an OAuth provider connection for the tenant',
    pathParams: [{ name: 'provider', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/integrations/oauth/{provider}/connect', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'integrations',
    verb: 'delete',
    path: '/wachat/integrations/oauth/[provider]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Disconnect an OAuth provider for the tenant',
    pathParams: [{ name: 'provider', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/integrations/oauth/{provider}', method: 'DELETE' },
  },

  /* ── Razorpay (/v1/wachat/razorpay) ───────────────────────────────────── */
  {
    module: 'wachat',
    resource: 'razorpay',
    verb: 'get',
    path: '/wachat/razorpay/projects/[id]/settings',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Read a project\'s Razorpay settings (key secret masked)',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/razorpay/projects/{id}/settings', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'razorpay',
    verb: 'update',
    path: '/wachat/razorpay/projects/[id]/settings',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'PRO',
    summary: 'Upsert a project\'s Razorpay credentials',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/razorpay/projects/{id}/settings', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'razorpay',
    verb: 'list',
    path: '/wachat/razorpay/projects/[id]/logs/transactions',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List a project\'s Razorpay payment transactions',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/razorpay/projects/{id}/logs/transactions', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'razorpay',
    verb: 'list',
    path: '/wachat/razorpay/projects/[id]/logs/payment-links',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List a project\'s Razorpay payment links',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/razorpay/projects/{id}/logs/payment-links', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'razorpay',
    verb: 'create',
    path: '/wachat/razorpay/projects/[id]/payment-links',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'PRO',
    summary: 'Create a Razorpay payment link for a project',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/razorpay/projects/{id}/payment-links', method: 'POST' },
  },

  /* ── Ads-integration roadmap (/v1/wachat/ads-roadmap) ─────────────────── */
  {
    module: 'wachat',
    resource: 'ads-roadmap',
    verb: 'list',
    path: '/wachat/ads-roadmap/phases',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List ads-integration roadmap phases with aggregated votes',
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ads-roadmap/phases', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'ads-roadmap',
    verb: 'custom',
    path: '/wachat/ads-roadmap/phases/[phase]/vote',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Upvote an ads-roadmap phase (idempotent per user)',
    pathParams: [{ name: 'phase', schema: { type: 'string' } }],
    requestBody: { required: false, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ads-roadmap/phases/{phase}/vote', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'ads-roadmap',
    verb: 'custom',
    path: '/wachat/ads-roadmap/sync',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Trigger an ads-roadmap sync',
    requestBody: { required: false, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ads-roadmap/sync', method: 'POST' },
  },

  /* ── Post generator (/v1/wachat/post-generator) ───────────────────────── */
  {
    module: 'wachat',
    resource: 'post-generator',
    verb: 'list',
    path: '/wachat/post-generator/drafts',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List saved post drafts for a project',
    queryParams: [{ name: 'projectId', schema: { type: 'string' }, required: true }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/post-generator/drafts', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'post-generator',
    verb: 'create',
    path: '/wachat/post-generator/drafts',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Save a post draft',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/post-generator/drafts', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'post-generator',
    verb: 'delete',
    path: '/wachat/post-generator/drafts/[id]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete a post draft',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/post-generator/drafts/{id}', method: 'DELETE' },
  },
  {
    module: 'wachat',
    resource: 'post-generator',
    verb: 'custom',
    path: '/wachat/post-generator/publish/facebook',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'PRO',
    summary: 'Publish a generated post to the connected Facebook Page',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/post-generator/publish/facebook', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'post-generator',
    verb: 'custom',
    path: '/wachat/post-generator/publish/whatsapp-status',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'PRO',
    summary: 'Publish a generated post as a WhatsApp status',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/post-generator/publish/whatsapp-status', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'post-generator',
    verb: 'list',
    path: '/wachat/post-generator/publish-log',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List post-publish log entries for a project',
    queryParams: [{ name: 'projectId', schema: { type: 'string' }, required: true }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/post-generator/publish-log', method: 'GET' },
  },

  /* ── Setup knowledge base (/v1/wachat/setup-kb) ───────────────────────── */
  {
    module: 'wachat',
    resource: 'setup-kb',
    verb: 'list',
    path: '/wachat/setup-kb/articles',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Search setup / troubleshooting knowledge-base articles',
    queryParams: [
      { name: 'q', schema: { type: 'string' } },
      { name: 'category', schema: { type: 'string' } },
      { name: 'sort', schema: { type: 'string' } },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/setup-kb/articles', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'setup-kb',
    verb: 'create',
    path: '/wachat/setup-kb/articles',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Create a knowledge-base article',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/setup-kb/articles', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'setup-kb',
    verb: 'update',
    path: '/wachat/setup-kb/articles/[articleId]',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update a knowledge-base article',
    pathParams: [{ name: 'articleId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/setup-kb/articles/{articleId}', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'setup-kb',
    verb: 'delete',
    path: '/wachat/setup-kb/articles/[articleId]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete a knowledge-base article',
    pathParams: [{ name: 'articleId', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/setup-kb/articles/{articleId}', method: 'DELETE' },
  },

  /* ── Contacts export + sync (/v1/wachat/contacts-export-sync) ─────────── */
  {
    module: 'wachat',
    resource: 'contacts-export-sync',
    verb: 'list',
    path: '/wachat/contacts-export-sync/export',
    method: 'GET',
    scope: 'contacts:read',
    tier: 'FREE',
    summary: 'Export matching contacts as a CSV stream',
    queryParams: [
      { name: 'projectId', schema: { type: 'string' }, required: true },
      { name: 'phoneNumberId', schema: { type: 'string' } },
      { name: 'tagIds', schema: { type: 'string' } },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/contacts-export-sync/export', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'contacts-export-sync',
    verb: 'custom',
    path: '/wachat/contacts-export-sync/sync/vcard',
    method: 'POST',
    scope: 'contacts:write',
    tier: 'PRO',
    summary: 'Parse a vCard and bulk-upsert contacts',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/contacts-export-sync/sync/vcard', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'contacts-export-sync',
    verb: 'custom',
    path: '/wachat/contacts-export-sync/sync/google',
    method: 'POST',
    scope: 'contacts:write',
    tier: 'PRO',
    summary: 'Sync contacts from Google Contacts',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/contacts-export-sync/sync/google', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'contacts-export-sync',
    verb: 'custom',
    path: '/wachat/contacts-export-sync/sync/shopify',
    method: 'POST',
    scope: 'contacts:write',
    tier: 'PRO',
    summary: 'Sync contacts from Shopify Customers',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/contacts-export-sync/sync/shopify', method: 'POST' },
  },
];
