/**
 * WhatsApp Cloud (Wachat) send + chat surface.
 *
 * Forwards through the existing `wachat-send-router` Rust crate which
 * shares state with the `MessageSender` library. Every endpoint here is a
 * passthrough — the manifest exists so developers get OpenAPI + a stable
 * `/api/v1/wachat/*` namespace independent of the Rust route layout.
 */

import type { EndpointSpec } from '../types';

export const wachatEndpoints: ReadonlyArray<EndpointSpec> = [
  /* ── Sends ────────────────────────────────────────────────────────────── */
  {
    module: 'wachat',
    resource: 'messages',
    verb: 'custom',
    path: '/wachat/messages/send',
    method: 'POST',
    scope: 'messages:write',
    tier: 'FREE',
    summary: 'Send a WhatsApp message (text or media)',
    description: 'Generic send dispatch — `kind` decides the body schema (text/image/video/document/audio).',
    requestBody: { required: true, schema: { $ref: '#/components/schemas/WachatSendBody' } },
    responses: {
      '2xx': { description: 'Send accepted', schema: { $ref: '#/components/schemas/SendAck' } },
      '400': { description: 'Validation failed' },
      '401': { description: 'Missing or invalid API key' },
      '403': { description: 'Missing required scope' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/messages/send', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },
  {
    module: 'wachat',
    resource: 'messages',
    verb: 'custom',
    path: '/wachat/messages/cta-url',
    method: 'POST',
    scope: 'messages:write',
    tier: 'FREE',
    summary: 'Send a call-to-action URL message',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Send accepted', schema: { $ref: '#/components/schemas/SendAck' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/messages/cta-url', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },
  {
    module: 'wachat',
    resource: 'messages',
    verb: 'custom',
    path: '/wachat/messages/location-request',
    method: 'POST',
    scope: 'messages:write',
    tier: 'FREE',
    summary: 'Send a location-request prompt',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Send accepted', schema: { $ref: '#/components/schemas/SendAck' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/messages/location-request', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },
  {
    module: 'wachat',
    resource: 'messages',
    verb: 'custom',
    path: '/wachat/messages/catalog',
    method: 'POST',
    scope: 'messages:write',
    tier: 'PRO',
    summary: 'Send a catalog message',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Send accepted', schema: { $ref: '#/components/schemas/SendAck' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/messages/catalog', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },
  {
    module: 'wachat',
    resource: 'messages',
    verb: 'custom',
    path: '/wachat/messages/order-details',
    method: 'POST',
    scope: 'messages:write',
    tier: 'PRO',
    summary: 'Send order-details message',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Send accepted', schema: { $ref: '#/components/schemas/SendAck' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/messages/order-details', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },
  {
    module: 'wachat',
    resource: 'messages',
    verb: 'custom',
    path: '/wachat/messages/order-status',
    method: 'POST',
    scope: 'messages:write',
    tier: 'PRO',
    summary: 'Send order-status update',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Send accepted', schema: { $ref: '#/components/schemas/SendAck' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/messages/order-status', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },

  /* ── Contacts (project-scoped) ────────────────────────────────────────── */
  {
    module: 'wachat',
    resource: 'contacts',
    verb: 'custom',
    path: '/wachat/contacts/resolve',
    method: 'POST',
    scope: 'contacts:write',
    tier: 'FREE',
    summary: 'Resolve or create a WhatsApp contact within a project',
    requestBody: { required: true, schema: { $ref: '#/components/schemas/ResolveContactBody' } },
    responses: {
      '2xx': { description: 'Contact resolved', schema: { $ref: '#/components/schemas/ResolveContactResult' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/contacts/resolve', method: 'POST' },
  },

  /* ── Chat ─────────────────────────────────────────────────────────────── */
  {
    module: 'wachat',
    resource: 'chat',
    verb: 'get',
    path: '/wachat/chat/initial',
    method: 'GET',
    scope: 'messages:read',
    tier: 'FREE',
    summary: 'Bootstrap data for the chat inbox',
    responses: {
      '2xx': { description: 'Initial inbox payload', schema: { type: 'object' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/chat/initial', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'chat',
    verb: 'get',
    path: '/wachat/chat/conversation/[contactId]',
    method: 'GET',
    scope: 'messages:read',
    tier: 'FREE',
    summary: 'List messages in a conversation',
    pathParams: [{ name: 'contactId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Conversation page', schema: { type: 'object' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/chat/conversation/{contactId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'chat',
    verb: 'custom',
    path: '/wachat/chat/mark-read/[contactId]',
    method: 'POST',
    scope: 'messages:write',
    tier: 'FREE',
    summary: 'Mark a conversation as read',
    pathParams: [{ name: 'contactId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Marked', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/chat/mark-read/{contactId}', method: 'POST' },
  },
];
