/**
 * Wachat "completion" inbox surface — the finished crates that round out the
 * WhatsApp inbox: canned (quick-reply) messages, opt-out automation,
 * interactive-message templates, A/B broadcast testing, contact de-duplication
 * (merge), and per-number AI auto-reply training.
 *
 * Every endpoint is a `rust-fwd` passthrough to an existing crate route. The
 * public `path` mirrors the Rust `/v1/...` path minus the leading `/v1`
 * (matching the convention in `wachat-extras.ts`). Crate mounts:
 *   - wachat-canned-messages    → /v1/wachat/canned-messages
 *   - wachat-opt-out-settings   → /v1/wachat/opt-out-settings
 *   - wachat-interactive-builder→ /v1/wachat/interactive-builder
 *   - wachat-ab-testing         → /v1/wachat/ab-tests
 *   - wachat-contact-merge      → /v1/wachat/contact-merge
 *   - wachat-ai-training        → /v1/wachat/ai-training
 */

import type { EndpointSpec } from '../types';

const generic2xx = { description: 'OK', schema: { type: 'object' as const } };
const auth = {
  '401': { description: 'Missing or invalid API key' },
  '429': { description: 'Rate limit exceeded' },
};

export const wachatCompletionInboxEndpoints: ReadonlyArray<EndpointSpec> = [
  /* ── Canned messages (quick replies, project-scoped) ──────────────────── */
  {
    module: 'wachat',
    resource: 'canned-messages',
    verb: 'list',
    path: '/wachat/canned-messages/[id]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List canned (quick-reply) messages for a project',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'Project id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/canned-messages/{id}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'canned-messages',
    verb: 'create',
    path: '/wachat/canned-messages/[id]',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Create a canned (quick-reply) message in a project',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'Project id' }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/canned-messages/{id}', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'canned-messages',
    verb: 'delete',
    path: '/wachat/canned-messages/[id]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete a canned (quick-reply) message',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'Project id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/canned-messages/{id}', method: 'DELETE' },
  },
  {
    module: 'wachat',
    resource: 'canned-messages',
    verb: 'get',
    path: '/wachat/canned-messages/[id]/settings',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Read canned-message settings for a project',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'Project id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/canned-messages/{id}/settings', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'canned-messages',
    verb: 'update',
    path: '/wachat/canned-messages/[id]/settings',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update canned-message settings for a project',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'Project id' }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/canned-messages/{id}/settings', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'canned-messages',
    verb: 'update',
    path: '/wachat/canned-messages/[id]/[messageId]',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update a single canned (quick-reply) message',
    pathParams: [
      { name: 'id', schema: { type: 'string' }, description: 'Project id' },
      { name: 'messageId', schema: { type: 'string' }, description: 'Canned message id' },
    ],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/canned-messages/{id}/{messageId}', method: 'PUT' },
  },

  /* ── Opt-out settings (auto opt-out keywords, project-scoped) ─────────── */
  {
    module: 'wachat',
    resource: 'opt-out-settings',
    verb: 'get',
    path: '/wachat/opt-out-settings/projects/[projectId]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Read opt-out settings for a project',
    pathParams: [{ name: 'projectId', schema: { type: 'string' }, description: 'Project id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/opt-out-settings/projects/{projectId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'opt-out-settings',
    verb: 'update',
    path: '/wachat/opt-out-settings/projects/[projectId]',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Upsert opt-out settings for a project',
    pathParams: [{ name: 'projectId', schema: { type: 'string' }, description: 'Project id' }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/opt-out-settings/projects/{projectId}', method: 'POST' },
  },

  /* ── Interactive-message builder (saved interactive templates) ────────── */
  {
    module: 'wachat',
    resource: 'interactive-builder',
    verb: 'list',
    path: '/wachat/interactive-builder/templates',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List saved interactive-message templates for a project',
    queryParams: [{ name: 'projectId', schema: { type: 'string' }, required: true }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/interactive-builder/templates', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'interactive-builder',
    verb: 'create',
    path: '/wachat/interactive-builder/templates',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Save an interactive-message template',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/interactive-builder/templates', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'interactive-builder',
    verb: 'delete',
    path: '/wachat/interactive-builder/templates/[id]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete a saved interactive-message template',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'Template id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/interactive-builder/templates/{id}', method: 'DELETE' },
  },

  /* ── A/B testing (broadcast variant experiments) ──────────────────────── */
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'list',
    path: '/wachat/ab-tests',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List A/B tests (with live result summary) for a project',
    queryParams: [{ name: 'projectId', schema: { type: 'string' }, required: true }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'create',
    path: '/wachat/ab-tests',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Create an A/B test',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'get',
    path: '/wachat/ab-tests/[id]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Get a single A/B test with its variant results',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'A/B test id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests/{id}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'delete',
    path: '/wachat/ab-tests/[id]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete an A/B test',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'A/B test id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests/{id}', method: 'DELETE' },
  },
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'custom',
    path: '/wachat/ab-tests/[id]/variants/[variant]/broadcast',
    method: 'POST',
    scope: 'broadcasts:write',
    tier: 'PRO',
    summary: 'Attach (launch) a broadcast for one A/B test variant',
    pathParams: [
      { name: 'id', schema: { type: 'string' }, description: 'A/B test id' },
      { name: 'variant', schema: { type: 'string' }, description: 'Variant key' },
    ],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests/{id}/variants/{variant}/broadcast', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'custom',
    path: '/wachat/ab-tests/[id]/stop',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Stop a running A/B test',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'A/B test id' }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests/{id}/stop', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'ab-tests',
    verb: 'custom',
    path: '/wachat/ab-tests/[id]/promote-winner',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Promote the winning variant of an A/B test',
    pathParams: [{ name: 'id', schema: { type: 'string' }, description: 'A/B test id' }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ab-tests/{id}/promote-winner', method: 'POST' },
  },

  /* ── Contact merge (de-duplication, sensitive mutation) ───────────────── */
  {
    module: 'wachat',
    resource: 'contact-merge',
    verb: 'custom',
    path: '/wachat/contact-merge',
    method: 'POST',
    scope: 'contacts:write',
    tier: 'PRO',
    summary: 'Merge a secondary WhatsApp contact into a primary one',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/contact-merge', method: 'POST' },
  },

  /* ── AI training (per project + phone-number auto-reply model) ────────── */
  {
    module: 'wachat',
    resource: 'ai-training',
    verb: 'get',
    path: '/wachat/ai-training/model-config/[projectId]/[phoneId]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Read the AI auto-reply model config for a number',
    pathParams: [
      { name: 'projectId', schema: { type: 'string' }, description: 'Project id' },
      { name: 'phoneId', schema: { type: 'string' }, description: 'WhatsApp phone-number id' },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ai-training/model-config/{projectId}/{phoneId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'ai-training',
    verb: 'update',
    path: '/wachat/ai-training/model-config/[projectId]/[phoneId]',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Upsert the AI auto-reply model config for a number',
    pathParams: [
      { name: 'projectId', schema: { type: 'string' }, description: 'Project id' },
      { name: 'phoneId', schema: { type: 'string' }, description: 'WhatsApp phone-number id' },
    ],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ai-training/model-config/{projectId}/{phoneId}', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'ai-training',
    verb: 'list',
    path: '/wachat/ai-training/samples/[projectId]/[phoneId]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List AI training samples for a number',
    pathParams: [
      { name: 'projectId', schema: { type: 'string' }, description: 'Project id' },
      { name: 'phoneId', schema: { type: 'string' }, description: 'WhatsApp phone-number id' },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ai-training/samples/{projectId}/{phoneId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'ai-training',
    verb: 'create',
    path: '/wachat/ai-training/samples/[projectId]/[phoneId]',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Create an AI training sample for a number',
    pathParams: [
      { name: 'projectId', schema: { type: 'string' }, description: 'Project id' },
      { name: 'phoneId', schema: { type: 'string' }, description: 'WhatsApp phone-number id' },
    ],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ai-training/samples/{projectId}/{phoneId}', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'ai-training',
    verb: 'delete',
    path: '/wachat/ai-training/samples/[projectId]/[phoneId]/[sampleId]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete an AI training sample',
    pathParams: [
      { name: 'projectId', schema: { type: 'string' }, description: 'Project id' },
      { name: 'phoneId', schema: { type: 'string' }, description: 'WhatsApp phone-number id' },
      { name: 'sampleId', schema: { type: 'string' }, description: 'Training sample id' },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/ai-training/samples/{projectId}/{phoneId}/{sampleId}', method: 'DELETE' },
  },
];
