/**
 * Wachat completion settings — project-scoped configuration crates that round
 * out the Wachat developer surface.
 *
 * Every endpoint is a `rust-fwd` passthrough to a finished Rust crate, mirroring
 * `wachat-extras.ts`. Public paths drop the leading `/v1`; dynamic segments use
 * the Next.js `[name]` form on the public side and `{name}` on the Rust side.
 *
 * Crates covered:
 *   - wachat-auto-reply-settings → /v1/wachat/auto-reply-settings
 *   - wachat-project-agents      → /v1/wachat/project-agents
 *   - wachat-project-attributes  → /v1/wachat/project-attributes
 *   - wachat-number-routing      → /v1/wachat/number-routing
 *   - wachat-quality-history     → /v1/wachat/quality-history
 *   - wachat-flow-events         → /v1/wachat/flow-events
 */

import type { EndpointSpec } from '../types';

const generic2xx = { description: 'OK', schema: { type: 'object' as const } };
const auth = {
  '401': { description: 'Missing or invalid API key' },
  '429': { description: 'Rate limit exceeded' },
};

export const wachatCompletionSettingsEndpoints: ReadonlyArray<EndpointSpec> = [
  /* ── Auto-reply settings (/v1/wachat/auto-reply-settings) ─────────────── */
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'get',
    path: '/wachat/auto-reply-settings/[projectId]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Get a project\'s auto-reply + opt-in/out settings',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'update',
    path: '/wachat/auto-reply-settings/[projectId]/master-switch',
    method: 'PATCH',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Toggle the project\'s auto-reply master switch',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}/master-switch', method: 'PATCH' },
  },
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'update',
    path: '/wachat/auto-reply-settings/[projectId]/welcome-message',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update the project\'s welcome-message auto-reply',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}/welcome-message', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'update',
    path: '/wachat/auto-reply-settings/[projectId]/inactive-hours',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update the project\'s inactive-hours auto-reply',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}/inactive-hours', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'update',
    path: '/wachat/auto-reply-settings/[projectId]/general',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update the project\'s general auto-reply settings',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}/general', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'update',
    path: '/wachat/auto-reply-settings/[projectId]/ai-assistant',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update the project\'s AI-assistant auto-reply settings',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}/ai-assistant', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'auto-reply-settings',
    verb: 'update',
    path: '/wachat/auto-reply-settings/[projectId]/opt-in-out',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update the project\'s opt-in/opt-out settings',
    pathParams: [{ name: 'projectId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/auto-reply-settings/{projectId}/opt-in-out', method: 'PUT' },
  },

  /* ── Project agents (/v1/wachat/project-agents) ──────────────────────── */
  {
    module: 'wachat',
    resource: 'project-agents',
    verb: 'list',
    path: '/wachat/project-agents/projects/[id]/agents',
    method: 'GET',
    scope: 'projects:read',
    tier: 'FREE',
    summary: 'List the agents assigned to a project',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-agents/projects/{id}/agents', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'project-agents',
    verb: 'custom',
    path: '/wachat/project-agents/projects/[id]/agents/invite',
    method: 'POST',
    scope: 'projects:write',
    tier: 'FREE',
    summary: 'Invite an existing user as a project agent',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-agents/projects/{id}/agents/invite', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'project-agents',
    verb: 'get',
    path: '/wachat/project-agents/projects/[id]/agents/[agentId]/open-tickets',
    method: 'GET',
    scope: 'projects:read',
    tier: 'FREE',
    summary: 'List an agent\'s open tickets within a project',
    pathParams: [
      { name: 'id', schema: { type: 'string' } },
      { name: 'agentId', schema: { type: 'string' } },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-agents/projects/{id}/agents/{agentId}/open-tickets', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'project-agents',
    verb: 'delete',
    path: '/wachat/project-agents/projects/[id]/agents/[agentId]',
    method: 'DELETE',
    scope: 'projects:write',
    tier: 'FREE',
    summary: 'Remove an agent from a project',
    pathParams: [
      { name: 'id', schema: { type: 'string' } },
      { name: 'agentId', schema: { type: 'string' } },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-agents/projects/{id}/agents/{agentId}', method: 'DELETE' },
  },
  {
    module: 'wachat',
    resource: 'project-agents',
    verb: 'update',
    path: '/wachat/project-agents/projects/[id]/agents/[agentId]/skills',
    method: 'PUT',
    scope: 'projects:write',
    tier: 'FREE',
    summary: 'Replace an agent\'s skills within a project',
    pathParams: [
      { name: 'id', schema: { type: 'string' } },
      { name: 'agentId', schema: { type: 'string' } },
    ],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-agents/projects/{id}/agents/{agentId}/skills', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'project-agents',
    verb: 'update',
    path: '/wachat/project-agents/projects/[id]/routing',
    method: 'PATCH',
    scope: 'projects:write',
    tier: 'FREE',
    summary: 'Update a project\'s agent routing strategy',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-agents/projects/{id}/routing', method: 'PATCH' },
  },

  /* ── Project attributes (/v1/wachat/project-attributes) ──────────────── */
  {
    module: 'wachat',
    resource: 'project-attributes',
    verb: 'list',
    path: '/wachat/project-attributes/projects/[id]/attributes',
    method: 'GET',
    scope: 'projects:read',
    tier: 'FREE',
    summary: 'List a project\'s custom user attributes',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-attributes/projects/{id}/attributes', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'project-attributes',
    verb: 'update',
    path: '/wachat/project-attributes/projects/[id]/attributes',
    method: 'PATCH',
    scope: 'projects:write',
    tier: 'FREE',
    summary: 'Replace a project\'s custom user attributes',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/project-attributes/projects/{id}/attributes', method: 'PATCH' },
  },

  /* ── Number routing (/v1/wachat/number-routing) ──────────────────────── */
  {
    module: 'wachat',
    resource: 'number-routing',
    verb: 'list',
    path: '/wachat/number-routing',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List phone-number to team routing bindings',
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/number-routing', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'number-routing',
    verb: 'create',
    path: '/wachat/number-routing',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Create a phone-number to team routing binding',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/number-routing', method: 'POST' },
  },
  {
    module: 'wachat',
    resource: 'number-routing',
    verb: 'update',
    path: '/wachat/number-routing/[id]',
    method: 'PUT',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Update a phone-number to team routing binding',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/number-routing/{id}', method: 'PUT' },
  },
  {
    module: 'wachat',
    resource: 'number-routing',
    verb: 'delete',
    path: '/wachat/number-routing/[id]',
    method: 'DELETE',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Delete a phone-number to team routing binding',
    pathParams: [{ name: 'id', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/number-routing/{id}', method: 'DELETE' },
  },

  /* ── Quality history (/v1/wachat/quality-history) ────────────────────── */
  {
    module: 'wachat',
    resource: 'quality-history',
    verb: 'list',
    path: '/wachat/quality-history/[phoneNumberId]',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'List quality-rating snapshots for a phone number',
    pathParams: [{ name: 'phoneNumberId', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/quality-history/{phoneNumberId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'quality-history',
    verb: 'custom',
    path: '/wachat/quality-history/[phoneNumberId]/snapshot',
    method: 'POST',
    scope: 'wachat:write',
    tier: 'FREE',
    summary: 'Record a quality-rating snapshot for a phone number',
    pathParams: [{ name: 'phoneNumberId', schema: { type: 'string' } }],
    requestBody: { required: true, schema: { type: 'object' } },
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/quality-history/{phoneNumberId}/snapshot', method: 'POST' },
  },

  /* ── Flow events (/v1/wachat/flow-events) ────────────────────────────── */
  {
    module: 'wachat',
    resource: 'flow-events',
    verb: 'list',
    path: '/wachat/flow-events',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Aggregate flow-trigger metrics for a project',
    queryParams: [
      { name: 'projectId', required: true, schema: { type: 'string' } },
    ],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/flow-events', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'flow-events',
    verb: 'get',
    path: '/wachat/flow-events/[flowId]/metrics',
    method: 'GET',
    scope: 'wachat:read',
    tier: 'FREE',
    summary: 'Trigger metrics for a single flow',
    pathParams: [{ name: 'flowId', schema: { type: 'string' } }],
    responses: { '2xx': generic2xx, ...auth },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/flow-events/{flowId}/metrics', method: 'GET' },
  },
];
