/**
 * WhatsApp template CRUD. Forwards to the `wachat-templates` crate.
 */

import type { EndpointSpec } from '../types';

export const wachatTemplatesEndpoints: ReadonlyArray<EndpointSpec> = [
  {
    module: 'wachat',
    resource: 'templates',
    verb: 'list',
    path: '/wachat/templates',
    method: 'GET',
    scope: 'templates:read',
    tier: 'FREE',
    summary: 'List WhatsApp templates',
    queryParams: [
      { name: 'projectId', schema: { type: 'string' }, description: 'Filter by project' },
      { name: 'status', schema: { type: 'string' } },
    ],
    responses: {
      '2xx': { description: 'A page of templates', schema: { type: 'object' } },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/templates/list', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'templates',
    verb: 'create',
    path: '/wachat/templates',
    method: 'POST',
    scope: 'templates:write',
    tier: 'FREE',
    summary: 'Create a template (submits for Meta review)',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Created', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '400': { description: 'Validation failed' },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/templates/create', method: 'POST' },
    emits: ['wachat.template.submitted'],
  },
  {
    module: 'wachat',
    resource: 'templates',
    verb: 'get',
    path: '/wachat/templates/[templateId]',
    method: 'GET',
    scope: 'templates:read',
    tier: 'FREE',
    summary: 'Fetch one template',
    pathParams: [{ name: 'templateId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Template', schema: { type: 'object' } },
      '401': { description: 'Missing or invalid API key' },
      '404': { description: 'Not found' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/templates/{templateId}', method: 'GET' },
  },
  {
    module: 'wachat',
    resource: 'templates',
    verb: 'delete',
    path: '/wachat/templates/[templateId]',
    method: 'DELETE',
    scope: 'templates:write',
    tier: 'FREE',
    summary: 'Delete a template',
    pathParams: [{ name: 'templateId', schema: { type: 'string' } }],
    responses: {
      '2xx': { description: 'Deleted', schema: { $ref: '#/components/schemas/Acknowledged' } },
      '401': { description: 'Missing or invalid API key' },
      '404': { description: 'Not found' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/templates/{templateId}', method: 'DELETE' },
    emits: ['wachat.template.deleted'],
  },
  {
    module: 'wachat',
    resource: 'templates',
    verb: 'custom',
    path: '/wachat/templates/send',
    method: 'POST',
    scope: 'messages:write',
    tier: 'FREE',
    summary: 'Send a template message',
    requestBody: { required: true, schema: { type: 'object' } },
    responses: {
      '2xx': { description: 'Sent', schema: { $ref: '#/components/schemas/SendAck' } },
      '400': { description: 'Validation failed' },
      '401': { description: 'Missing or invalid API key' },
      '429': { description: 'Rate limit exceeded' },
    },
    delegate: { kind: 'rust-fwd', path: '/v1/wachat/templates/send', method: 'POST' },
    emits: ['wachat.message.sent'],
    credits: 1,
  },
];
