// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// List notes on a ticket  (scope: crm:support:read, tier: FREE)
export const GET = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/crm/tickets/${encodeURIComponent(String((params as Record<string, string>).ticketId ?? ''))}/notes${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'GET',
    },
  );
  return NextResponse.json(data);
}, { scope: 'crm:support:read' });

// Add a note to a ticket  (scope: crm:support:write, tier: FREE)
export const POST = withApiV1(async (req, { ctx, params }) => {
  let body: unknown = undefined;
  try { body = await req.json(); } catch { body = undefined; }
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/crm/tickets/${encodeURIComponent(String((params as Record<string, string>).ticketId ?? ''))}/notes${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'POST',
      body: body === undefined ? undefined : JSON.stringify(body),
    },
  );
  return NextResponse.json(data);
}, { scope: 'crm:support:write' });
