// PORT-NOTE: Ported from Twenty twenty-server. TypeORM Relation<>, SyncableEntity,
// and complex generic constraints are removed. The runtime value is identical.

import { type ALL_MANY_TO_ONE_METADATA_FOREIGN_KEY } from '@/lib/sabcrm/server/src/engine/metadata-modules/flat-entity/constant/all-many-to-one-metadata-foreign-key.constant';
import { type ALL_ONE_TO_MANY_METADATA_RELATIONS } from '@/lib/sabcrm/server/src/engine/metadata-modules/flat-entity/constant/all-one-to-many-metadata-relations.constant';

// Re-export so consumers can reference both maps in one import if needed.
export type { ALL_MANY_TO_ONE_METADATA_FOREIGN_KEY, ALL_ONE_TO_MANY_METADATA_RELATIONS };

export const ALL_MANY_TO_ONE_METADATA_RELATIONS = {
  agent: { workspace: null, application: null },
  skill: { workspace: null, application: null },
  commandMenuItem: {
    workspace: null,
    application: null,
    availabilityObjectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'availabilityObjectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'availabilityObjectMetadataUniversalIdentifier',
    },
    frontComponent: {
      metadataName: 'frontComponent',
      foreignKey: 'frontComponentId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'frontComponentUniversalIdentifier',
    },
    pageLayout: {
      metadataName: 'pageLayout',
      foreignKey: 'pageLayoutId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'pageLayoutUniversalIdentifier',
    },
  },
  navigationMenuItem: {
    workspace: null,
    userWorkspace: null,
    application: null,
    targetObjectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'targetObjectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'targetObjectMetadataUniversalIdentifier',
    },
    folder: {
      metadataName: 'navigationMenuItem',
      foreignKey: 'folderId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'folderUniversalIdentifier',
    },
    view: {
      metadataName: 'view',
      foreignKey: 'viewId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'viewUniversalIdentifier',
    },
    pageLayout: {
      metadataName: 'pageLayout',
      foreignKey: 'pageLayoutId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'pageLayoutUniversalIdentifier',
    },
  },
  fieldMetadata: {
    object: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: 'fields',
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    workspace: null,
    application: null,
    relationTargetFieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'relationTargetFieldMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'relationTargetFieldMetadataUniversalIdentifier',
    },
    relationTargetObjectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'relationTargetObjectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'relationTargetObjectMetadataUniversalIdentifier',
    },
  },
  objectMetadata: { workspace: null, application: null },
  view: {
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: 'views',
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    workspace: null,
    createdBy: null,
    application: null,
    calendarFieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'calendarFieldMetadataId',
      inverseOneToManyProperty: 'calendarViews',
      isNullable: true,
      universalForeignKey: 'calendarFieldMetadataUniversalIdentifier',
    },
    kanbanAggregateOperationFieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'kanbanAggregateOperationFieldMetadataId',
      inverseOneToManyProperty: 'kanbanAggregateOperationViews',
      isNullable: true,
      universalForeignKey: 'kanbanAggregateOperationFieldMetadataUniversalIdentifier',
    },
    mainGroupByFieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'mainGroupByFieldMetadataId',
      inverseOneToManyProperty: 'mainGroupByFieldMetadataViews',
      isNullable: true,
      universalForeignKey: 'mainGroupByFieldMetadataUniversalIdentifier',
    },
  },
  viewField: {
    fieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'fieldMetadataId',
      inverseOneToManyProperty: 'viewFields',
      isNullable: false,
      universalForeignKey: 'fieldMetadataUniversalIdentifier',
    },
    view: {
      metadataName: 'view',
      foreignKey: 'viewId',
      inverseOneToManyProperty: 'viewFields',
      isNullable: false,
      universalForeignKey: 'viewUniversalIdentifier',
    },
    viewFieldGroup: {
      metadataName: 'viewFieldGroup',
      foreignKey: 'viewFieldGroupId',
      inverseOneToManyProperty: 'viewFields',
      isNullable: true,
      universalForeignKey: 'viewFieldGroupUniversalIdentifier',
    },
    workspace: null,
    application: null,
  },
  viewFieldGroup: {
    view: {
      metadataName: 'view',
      foreignKey: 'viewId',
      inverseOneToManyProperty: 'viewFieldGroups',
      isNullable: false,
      universalForeignKey: 'viewUniversalIdentifier',
    },
    workspace: null,
    application: null,
  },
  viewFilter: {
    fieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'fieldMetadataId',
      inverseOneToManyProperty: 'viewFilters',
      isNullable: false,
      universalForeignKey: 'fieldMetadataUniversalIdentifier',
    },
    view: {
      metadataName: 'view',
      foreignKey: 'viewId',
      inverseOneToManyProperty: 'viewFilters',
      isNullable: false,
      universalForeignKey: 'viewUniversalIdentifier',
    },
    relationTargetFieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'relationTargetFieldMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'relationTargetFieldMetadataUniversalIdentifier',
    },
    viewFilterGroup: {
      metadataName: 'viewFilterGroup',
      foreignKey: 'viewFilterGroupId',
      inverseOneToManyProperty: 'viewFilters',
      isNullable: true,
      universalForeignKey: 'viewFilterGroupUniversalIdentifier',
    },
    workspace: null,
    application: null,
  },
  viewGroup: {
    view: {
      metadataName: 'view',
      foreignKey: 'viewId',
      inverseOneToManyProperty: 'viewGroups',
      isNullable: false,
      universalForeignKey: 'viewUniversalIdentifier',
    },
    workspace: null,
    application: null,
  },
  index: {
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: 'indexMetadatas',
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    workspace: null,
    application: null,
  },
  logicFunction: { workspace: null, application: null },
  role: { workspace: null, application: null },
  roleTarget: {
    role: {
      metadataName: 'role',
      foreignKey: 'roleId',
      inverseOneToManyProperty: 'roleTargets',
      isNullable: false,
      universalForeignKey: 'roleUniversalIdentifier',
    },
    apiKey: null,
    workspace: null,
    application: null,
  },
  rolePermissionFlag: {
    workspace: null,
    application: null,
    role: {
      metadataName: 'role',
      foreignKey: 'roleId',
      inverseOneToManyProperty: 'rolePermissionFlags',
      isNullable: false,
      universalForeignKey: 'roleUniversalIdentifier',
    },
    permissionFlag: {
      metadataName: 'permissionFlag',
      foreignKey: 'permissionFlagId',
      inverseOneToManyProperty: 'rolePermissionFlags',
      isNullable: false,
      universalForeignKey: 'permissionFlagUniversalIdentifier',
    },
  },
  permissionFlag: { workspace: null, application: null },
  objectPermission: {
    workspace: null,
    application: null,
    role: {
      metadataName: 'role',
      foreignKey: 'roleId',
      inverseOneToManyProperty: 'objectPermissions',
      isNullable: false,
      universalForeignKey: 'roleUniversalIdentifier',
    },
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: 'objectPermissions',
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
  },
  fieldPermission: {
    workspace: null,
    application: null,
    role: {
      metadataName: 'role',
      foreignKey: 'roleId',
      inverseOneToManyProperty: 'fieldPermissions',
      isNullable: false,
      universalForeignKey: 'roleUniversalIdentifier',
    },
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: 'fieldPermissions',
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    fieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'fieldMetadataId',
      inverseOneToManyProperty: 'fieldPermissions',
      isNullable: false,
      universalForeignKey: 'fieldMetadataUniversalIdentifier',
    },
  },
  pageLayout: {
    workspace: null,
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    application: null,
    defaultTabToFocusOnMobileAndSidePanel: {
      metadataName: 'pageLayoutTab',
      foreignKey: 'defaultTabToFocusOnMobileAndSidePanelId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'defaultTabToFocusOnMobileAndSidePanelUniversalIdentifier',
    },
  },
  pageLayoutTab: {
    workspace: null,
    pageLayout: {
      metadataName: 'pageLayout',
      foreignKey: 'pageLayoutId',
      inverseOneToManyProperty: 'tabs',
      isNullable: false,
      universalForeignKey: 'pageLayoutUniversalIdentifier',
    },
    application: null,
  },
  pageLayoutWidget: {
    workspace: null,
    pageLayoutTab: {
      metadataName: 'pageLayoutTab',
      foreignKey: 'pageLayoutTabId',
      inverseOneToManyProperty: 'widgets',
      isNullable: false,
      universalForeignKey: 'pageLayoutTabUniversalIdentifier',
    },
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    application: null,
  },
  rowLevelPermissionPredicate: {
    workspace: null,
    role: {
      metadataName: 'role',
      foreignKey: 'roleId',
      inverseOneToManyProperty: 'rowLevelPermissionPredicates',
      isNullable: false,
      universalForeignKey: 'roleUniversalIdentifier',
    },
    fieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'fieldMetadataId',
      inverseOneToManyProperty: null,
      isNullable: false,
      universalForeignKey: 'fieldMetadataUniversalIdentifier',
    },
    workspaceMemberFieldMetadata: {
      metadataName: 'fieldMetadata',
      foreignKey: 'workspaceMemberFieldMetadataId',
      inverseOneToManyProperty: null,
      isNullable: true,
      universalForeignKey: 'workspaceMemberFieldMetadataUniversalIdentifier',
    },
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    rowLevelPermissionPredicateGroup: {
      metadataName: 'rowLevelPermissionPredicateGroup',
      foreignKey: 'rowLevelPermissionPredicateGroupId',
      inverseOneToManyProperty: 'rowLevelPermissionPredicates',
      isNullable: true,
      universalForeignKey: 'rowLevelPermissionPredicateGroupUniversalIdentifier',
    },
    application: null,
  },
  rowLevelPermissionPredicateGroup: {
    objectMetadata: {
      metadataName: 'objectMetadata',
      foreignKey: 'objectMetadataId',
      inverseOneToManyProperty: null,
      isNullable: false,
      universalForeignKey: 'objectMetadataUniversalIdentifier',
    },
    role: {
      metadataName: 'role',
      foreignKey: 'roleId',
      inverseOneToManyProperty: 'rowLevelPermissionPredicateGroups',
      isNullable: false,
      universalForeignKey: 'roleUniversalIdentifier',
    },
    parentRowLevelPermissionPredicateGroup: {
      metadataName: 'rowLevelPermissionPredicateGroup',
      foreignKey: 'parentRowLevelPermissionPredicateGroupId',
      inverseOneToManyProperty: 'childRowLevelPermissionPredicateGroups',
      isNullable: true,
      universalForeignKey: 'parentRowLevelPermissionPredicateGroupUniversalIdentifier',
    },
    workspace: null,
    application: null,
  },
  viewFilterGroup: {
    application: null,
    parentViewFilterGroup: {
      metadataName: 'viewFilterGroup',
      foreignKey: 'parentViewFilterGroupId',
      inverseOneToManyProperty: 'childViewFilterGroups',
      isNullable: true,
      universalForeignKey: 'parentViewFilterGroupUniversalIdentifier',
    },
    view: {
      metadataName: 'view',
      foreignKey: 'viewId',
      inverseOneToManyProperty: 'viewFilterGroups',
      isNullable: false,
      universalForeignKey: 'viewUniversalIdentifier',
    },
    workspace: null,
  },
  frontComponent: { workspace: null, application: null },
  webhook: { workspace: null, application: null },
  applicationVariable: { workspace: null, application: null },
  viewSort: {
    application: null,
    workspace: null,
    fieldMetadata: {
      foreignKey: 'fieldMetadataId',
      universalForeignKey: 'fieldMetadataUniversalIdentifier',
      inverseOneToManyProperty: null,
      isNullable: false,
      metadataName: 'fieldMetadata',
    },
    view: {
      foreignKey: 'viewId',
      universalForeignKey: 'viewUniversalIdentifier',
      inverseOneToManyProperty: 'viewSorts',
      isNullable: false,
      metadataName: 'view',
    },
  },
  connectionProvider: { workspace: null, application: null },
} as const;
