"""Generate docs/inventory/rust-stubs.json from the SabFlow Rust node sources.

Re-run after promoting any stub to a full implementation:

    python3 scripts/sabflow/gen-rust-stub-inventory.py

Output: docs/inventory/rust-stubs.json
"""

import datetime
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
NODES = os.path.join(ROOT, "rust/crates/sabflow-nodes/src/nodes")
OUT = os.path.join(ROOT, "docs/inventory/rust-stubs.json")

# ── Parse the stub list out of register_stubs() in mod.rs ───────────────────
src = open(os.path.join(NODES, "mod.rs")).read()
stub_pat = re.compile(
    r'\(\s*"([a-zA-Z][a-zA-Z0-9]*)"\s*,\s*"([^"]*)"\s*,\s*NodeCategory::([A-Za-z]+)\s*,\s*"([^"]*)"\s*\)'
)
stubs_raw = [
    {
        "name": m.group(1),
        "displayName": m.group(2),
        "category": m.group(3),
        "description": m.group(4),
    }
    for m in stub_pat.finditer(src)
]

# ── Parse implemented nodes from the per-node files ────────────────────────
desc_call = re.compile(
    r'NodeDescriptor::new\(\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*"([^"]*)"\s*,\s*NodeCategory::([A-Za-z]+)',
    re.DOTALL,
)
struct_pat = re.compile(
    r'name:\s*"([a-zA-Z][a-zA-Z0-9]*)"\.to_string\(\)'
    r".*?display_name:\s*\"([^\"]+)\"\.to_string\(\)"
    r".*?description:\s*\"([^\"]*)\"\.to_string\(\)"
    r".*?category:\s*NodeCategory::([A-Za-z]+)",
    re.DOTALL,
)

impl = []
for fn in sorted(os.listdir(NODES)):
    if not fn.endswith(".rs") or fn in ("mod.rs", "stub.rs"):
        continue
    p = os.path.join(NODES, fn)
    t = open(p).read()
    m = desc_call.search(t) or struct_pat.search(t)
    if m:
        impl.append(
            {
                "name": m.group(1),
                "displayName": m.group(2),
                "description": m.group(3),
                "category": m.group(4),
                "file": "rust/crates/sabflow-nodes/src/nodes/" + fn,
            }
        )

impl_by_name = {i["name"]: i for i in impl}
stub_names = {s["name"] for s in stubs_raw}
all_names = sorted(set(impl_by_name.keys()) | stub_names)

nodes = []
for name in all_names:
    full = f"n8n-nodes-base.{name}"
    if name in impl_by_name:
        rec = impl_by_name[name]
        nodes.append(
            {
                "n8nType": full,
                "name": name,
                "displayName": rec["displayName"],
                "category": rec["category"],
                "description": rec["description"],
                "isStub": False,
                "implFile": rec["file"],
            }
        )
    else:
        rec = next(s for s in stubs_raw if s["name"] == name)
        nodes.append(
            {
                "n8nType": full,
                "name": name,
                "displayName": rec["displayName"],
                "category": rec["category"],
                "description": rec["description"],
                "isStub": True,
                "implFile": None,
            }
        )

stub_count = sum(1 for n in nodes if n["isStub"])
impl_count = sum(1 for n in nodes if not n["isStub"])

reference = next(
    (n for n in nodes if n["n8nType"] == "n8n-nodes-base.httpRequest"), None
)
assert reference is not None, "httpRequest missing from inventory"
assert reference["isStub"] is False, "httpRequest must be isStub: false post-C.2.10"

inventory = {
    "$schema": "https://sabflow.dev/schemas/rust-stubs-inventory.v1.json",
    "generatedAt": datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    ),
    "generator": "scripts/sabflow/gen-rust-stub-inventory.py",
    "summary": {
        "totalNodes": len(nodes),
        "implementedCount": impl_count,
        "stubCount": stub_count,
        "referenceNode": "n8n-nodes-base.httpRequest",
        "phase": "C.3.9",
    },
    "notes": [
        "Source of truth for which n8n nodes the SabFlow Rust crate ships as full implementations vs. registry-only stubs.",
        "Generated by parsing rust/crates/sabflow-nodes/src/nodes/. Re-run scripts/sabflow/gen-rust-stub-inventory.py after promoting a stub.",
        "`isStub: false` means the node has its own module under src/nodes/ and is wired into register_implemented in mod.rs.",
    ],
    "nodes": nodes,
}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    json.dump(inventory, f, indent=2)
    f.write("\n")

print(f"wrote {OUT}")
print(f"  totalNodes:       {len(nodes)}")
print(f"  implementedCount: {impl_count}")
print(f"  stubCount:        {stub_count}")
print(f"  reference:        {reference['n8nType']} (isStub={reference['isStub']})")
