// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { getAccount } from '@/lib/api-platform/handlers/identity';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Return the tenant account profile  (scope: me:read, tier: FREE)
export const GET = withApiV1(getAccount, { scope: 'me:read' });
