// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Update the project's inactive-hours auto-reply  (scope: wachat:write, tier: FREE)
export const PUT = withApiV1(async (req, { ctx, params }) => {
  let body: unknown = undefined;
  try { body = await req.json(); } catch { body = undefined; }
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/wachat/auto-reply-settings/${encodeURIComponent(String((params as Record<string, string>).projectId ?? ''))}/inactive-hours${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'PUT',
      body: body === undefined ? undefined : JSON.stringify(body),
    },
  );
  return NextResponse.json(data);
}, { scope: 'wachat:write' });
