/**
 * SabSheet function-parity audit.
 *
 * Diffs the engine's implemented function list (from `sabsheet-engine`'s `function_names()`,
 * dumped via the `dump_fns` example) against HyperFormula's *documented* function-name list
 * (factual identifiers parsed from their public docs page — no implementation code is read).
 * Writes `docs/sabsheet/FUNCTION-PARITY.md`.
 *
 * Run: npx tsx scripts/sabsheet/function-parity.ts [--ours <file>] [--offline <hf-md-file>]
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const HF_DOC_URL =
  "https://raw.githubusercontent.com/handsontable/hyperformula/master/docs/guide/built-in-functions.md";

/** Categories whose functions require dynamic arrays / spill (not in our engine yet). */
const SPILL_CATEGORIES = new Set(["Array manipulation"]);
const SPILL_FUNCTIONS = new Set([
  "ARRAYFORMULA", "FILTER", "ARRAY_CONSTRAIN", "SEQUENCE", "TRANSPOSE",
  "MMULT", "SPLIT", "MAXPOOL", "MEDIANPOOL", // matrix/array results
]);
/** HyperFormula-internal pseudo-functions (operator representations) — not spreadsheet functions. */
const HF_INTERNAL = /^HF\./;

/** Tier by category: 1 = everyday, 2 = analytical, 3 = niche tail. */
function tierOf(category: string): 1 | 2 | 3 {
  const c = category.toLowerCase();
  if (/date|text|logical|lookup|math|information|operator/.test(c)) return 1;
  if (/statistical|financial/.test(c)) return 2;
  return 3;
}

function arg(flag: string): string | null {
  const i = process.argv.indexOf(flag);
  return i >= 0 ? process.argv[i + 1] ?? null : null;
}

async function main() {
  const root = path.resolve(__dirname, "../..");

  // 1. Our implemented names.
  const oursFile = arg("--ours");
  let oursRaw: string;
  if (oursFile) {
    oursRaw = readFileSync(oursFile, "utf8");
  } else {
    oursRaw = execSync("cargo run -q -p sabsheet-engine --example dump_fns", {
      cwd: path.join(root, "rust"),
      encoding: "utf8",
      maxBuffer: 10 * 1024 * 1024,
    });
  }
  const ours = new Set(
    oursRaw
      .split("\n")
      .map((s) => s.trim().toUpperCase())
      .filter(Boolean),
  );

  // 2. HyperFormula's documented list (names + categories only).
  const offline = arg("--offline");
  const md = offline ? readFileSync(offline, "utf8") : await (await fetch(HF_DOC_URL)).text();

  type Entry = { name: string; category: string };
  const entries: Entry[] = [];
  let category = "Uncategorized";
  for (const line of md.split("\n")) {
    const h = /^##\s+(.+)$/.exec(line);
    if (h) {
      category = h[1].trim();
      continue;
    }
    const row = /^\|\s*([A-Z][A-Z0-9._]*)\s*\|/.exec(line);
    if (row && row[1] !== "FUNCTION") {
      entries.push({ name: row[1], category });
    }
  }
  if (entries.length < 200) {
    throw new Error(`parsed only ${entries.length} documented functions — page format changed?`);
  }

  // 3. Diff per category.
  const byCategory = new Map<string, Entry[]>();
  for (const e of entries) {
    const list = byCategory.get(e.category) ?? [];
    list.push(e);
    byCategory.set(e.category, list);
  }

  let implemented = 0;
  let missing = 0;
  let blocked = 0;
  let internal = 0;
  const missingByTier: Record<1 | 2 | 3, string[]> = { 1: [], 2: [], 3: [] };

  const lines: string[] = [];
  lines.push("# SabSheet — Function parity audit");
  lines.push("");
  lines.push(
    `Generated by \`scripts/sabsheet/function-parity.ts\` on ${new Date().toISOString().slice(0, 10)}. ` +
      `Reference list: HyperFormula's public docs (function names only — implementations are written ` +
      `clean-room from Microsoft's public function documentation).`,
  );
  lines.push("");

  for (const [cat, list] of byCategory) {
    const tier = tierOf(cat);
    lines.push(`## ${cat} (Tier ${tier})`);
    lines.push("");
    lines.push("| Function | Status |");
    lines.push("| --- | --- |");
    for (const e of list.sort((a, b) => a.name.localeCompare(b.name))) {
      let status: string;
      if (ours.has(e.name)) {
        status = "✓ implemented";
        implemented++;
      } else if (HF_INTERNAL.test(e.name)) {
        status = "— n/a (HyperFormula-internal operator pseudo-function)";
        internal++;
      } else if (SPILL_CATEGORIES.has(cat) || SPILL_FUNCTIONS.has(e.name)) {
        status = "⛔ blocked on spill (dynamic arrays)";
        blocked++;
      } else {
        status = "✗ missing";
        missing++;
        missingByTier[tier].push(e.name);
      }
      lines.push(`| ${e.name} | ${status} |`);
    }
    lines.push("");
  }

  // Ours-only extras (we implement more than they document in some areas).
  const documented = new Set(entries.map((e) => e.name));
  const extras = [...ours].filter((n) => !documented.has(n)).sort();

  const summary = [
    "## Summary",
    "",
    `- Documented (HyperFormula): **${entries.length}**`,
    `- Implemented here: **${implemented}** · Missing: **${missing}** · Blocked on spill: **${blocked}** · n/a internal: **${internal}**`,
    `- Implemented here but not in their list: **${extras.length}** (${extras.slice(0, 12).join(", ")}${extras.length > 12 ? ", …" : ""})`,
    "",
    `### Missing — Tier 1 (${missingByTier[1].length})`,
    missingByTier[1].join(", ") || "(none)",
    "",
    `### Missing — Tier 2 (${missingByTier[2].length})`,
    missingByTier[2].join(", ") || "(none)",
    "",
    `### Missing — Tier 3 (${missingByTier[3].length})`,
    missingByTier[3].join(", ") || "(none)",
    "",
  ];
  lines.splice(4, 0, ...summary);

  const out = path.join(root, "docs/sabsheet/FUNCTION-PARITY.md");
  mkdirSync(path.dirname(out), { recursive: true });
  writeFileSync(out, lines.join("\n"));
  console.log(
    `documented=${entries.length} implemented=${implemented} missing=${missing} blocked=${blocked} internal=${internal} → ${path.relative(root, out)}`,
  );
  console.log(`Tier1 missing: ${missingByTier[1].join(", ")}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
