// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { revokeKey } from '@/lib/api-platform/handlers/identity';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Revoke an API key  (scope: keys:write, tier: FREE)
export const DELETE = withApiV1(revokeKey, { scope: 'keys:write' });
