/**
 * Shared utilities for the API codegen.
 */

import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

/** Marker placed in every generated file. CI lint refuses route files that
 *  live under `src/app/api/v1/**` and lack this header. */
export const GENERATED_HEADER =
  '// @generated by tools/api-codegen — DO NOT EDIT BY HAND.\n' +
  '// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.\n';

/** Absolute repo root, derived from this file's location. */
export const REPO_ROOT = resolve(new URL('../..', import.meta.url).pathname);

/**
 * Write a file under the repo, creating parent directories as needed. Skips
 * the write when the on-disk content already matches — keeps `pnpm api:gen`
 * idempotent and Next.js dev mode happy (no spurious recompiles).
 */
export function writeIfChanged(relPath: string, content: string): { wrote: boolean } {
  const abs = resolve(REPO_ROOT, relPath);
  if (existsSync(abs)) {
    const prior = readFileSync(abs, 'utf8');
    if (prior === content) return { wrote: false };
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, 'utf8');
  return { wrote: true };
}

/**
 * Convert a Next.js dynamic-segment path (`/contacts/[id]/merge`) into the
 * OpenAPI form (`/contacts/{id}/merge`).
 */
export function toOpenApiPath(nextPath: string): string {
  return nextPath.replace(/\[([^\]]+)\]/g, '{$1}');
}

/**
 * Convert a Next.js path into the on-disk folder path under `src/app/api/v1`.
 * Returns a path *relative* to the v1 root.
 */
export function pathToFolder(nextPath: string): string {
  // `/me` → `me`, `/contacts/[id]/merge` → `contacts/[id]/merge`
  return nextPath.replace(/^\/+/, '').replace(/\/+$/, '');
}
