// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { sendText } from './_handlers';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Send a WhatsApp text message  (scope: messages:write, tier: FREE)
export const POST = withApiV1(sendText, { scope: 'messages:write' });
