/**
 * Registry for the trigger picker panel — the n8n-style
 * "What triggers this workflow?" rail that shows on an empty canvas.
 *
 * Each option carries:
 *   • `eventType` — the fundamental SabFlowEvent.type that drives engine
 *     subscription (manual / start / schedule / webhook / error). All app
 *     events default to `webhook` since they originate from external systems.
 *   • `appEvent`  — the specific SabNode product event slug, persisted on
 *     the SabFlowEvent so the engine can route to the right handler.
 *   • `category`  — UI grouping for the picker (matches n8n's section headers).
 */
import type { ComponentType, SVGProps } from 'react';
import {
  LuMousePointerClick,
  LuClock,
  LuGlobe,
  LuPlay,
  LuTriangleAlert,
  LuMessageCircle,
  LuMessageSquare,
  LuFileCheck,
  LuFileX,
  LuMegaphone,
  LuBan,
  LuCircleCheck,
  LuShieldAlert,
  LuPower,
  LuSignal,
  LuPhone,
  LuPhoneIncoming,
  LuPhoneOutgoing,
  LuPhoneMissed,
  LuPhoneCall,
  LuPhoneOff,
  LuSettings,
  LuUserPlus,
  LuUser,
  LuTag,
  LuUserCheck,
  LuMerge,
  LuUpload,
  LuBuilding,
  LuStickyNote,
  LuBriefcase,
  LuTrendingUp,
  LuTrendingDown,
  LuPercent,
  LuDollarSign,
  LuTarget,
  LuFlag,
  LuArrowRightLeft,
  LuHistory,
  LuFileText,
  LuSend,
  LuCheck,
  LuCircleDollarSign,
  LuCalendarClock,
  LuReceipt,
  LuFileSpreadsheet,
  LuPackage,
  LuPackageOpen,
  LuPackageX,
  LuTags,
  LuWarehouse,
  LuListChecks,
  LuListTodo,
  LuClipboardCheck,
  LuClipboardList,
  LuZap,
  LuPlay as LuTriggerPlay,
  LuPlay as LuPlayCircle,
  LuPause as LuPauseCircle,
  LuRefreshCw,
  LuFileCode,
  LuFacebook,
  LuInstagram,
  LuPlug,
  LuPlugZap,
  LuLink,
  LuMail,
  LuMailOpen,
  LuMousePointer,
  LuSmartphone,
  LuCircleCheck as LuCheckCircle,
  LuCreditCard,
  LuCircleX,
  LuShoppingCart,
  LuTruck,
  LuShoppingBag,
  LuChartLine,
  LuArrowUp,
  LuArrowDown,
  LuSearch,
} from 'react-icons/lu';

import type { EventType } from '@/lib/sabflow/types';

type IconComponent = ComponentType<SVGProps<SVGSVGElement> & { className?: string }>;

export type TriggerCategory =
  | 'general'
  | 'whatsapp'
  | 'calls'
  | 'crm-contacts'
  | 'crm-deals'
  | 'crm-leads'
  | 'crm-sales'
  | 'crm-products'
  | 'crm-tasks'
  | 'broadcasts'
  | 'templates'
  | 'social'
  | 'email-sms'
  | 'payments'
  | 'orders'
  | 'seo'
  | 'integrations';

export type TriggerOption = {
  /** Stable slug stored on the persisted SabFlowEvent. */
  appEvent: string;
  /** Engine subscription mechanism. */
  eventType: EventType;
  category: TriggerCategory;
  label: string;
  description: string;
  icon: IconComponent;
  color: string;
};

export const TRIGGER_CATEGORY_META: Record<
  TriggerCategory,
  { label: string; color: string; order: number }
> = {
  general:        { label: 'Generic',                color: '#6b7280', order: 1 },
  whatsapp:       { label: 'WhatsApp (Wachat)',      color: '#25d366', order: 2 },
  calls:          { label: 'Calls',                  color: '#0ea5e9', order: 3 },
  'crm-contacts': { label: 'CRM · Contacts',         color: '#3b82f6', order: 4 },
  'crm-deals':    { label: 'CRM · Deals',            color: '#6366f1', order: 5 },
  'crm-leads':    { label: 'CRM · Leads',            color: '#8b5cf6', order: 6 },
  'crm-sales':    { label: 'CRM · Invoices & Payments', color: '#10b981', order: 7 },
  'crm-products': { label: 'CRM · Products & Inventory', color: '#f59e0b', order: 8 },
  'crm-tasks':    { label: 'CRM · Tasks',            color: '#a855f7', order: 9 },
  broadcasts:     { label: 'Broadcasts',             color: '#ec4899', order: 10 },
  templates:      { label: 'Templates',              color: '#f97316', order: 11 },
  social:         { label: 'Facebook & Instagram',   color: '#1877f2', order: 12 },
  'email-sms':    { label: 'Email & SMS',            color: '#0ea5e9', order: 13 },
  payments:       { label: 'Payments',               color: '#22c55e', order: 14 },
  orders:         { label: 'Orders & Commerce',      color: '#fb923c', order: 15 },
  seo:            { label: 'SEO & Analytics',        color: '#14b8a6', order: 16 },
  integrations:   { label: 'Integrations',           color: '#94a3b8', order: 17 },
};

export const TRIGGER_OPTIONS: TriggerOption[] = [
  // ── General ─────────────────────────────────────────────────────────────
  { appEvent: 'manual_trigger', eventType: 'manual', category: 'general',
    label: 'Trigger manually',
    description: 'Runs the flow on clicking a button. Good for getting started quickly.',
    icon: LuMousePointerClick as IconComponent, color: '#f76808' },
  { appEvent: 'flow_start', eventType: 'start', category: 'general',
    label: 'When the flow starts',
    description: 'Default entry point — runs whenever a new visitor enters the flow.',
    icon: LuPlay as IconComponent, color: '#10b981' },
  { appEvent: 'on_schedule', eventType: 'schedule', category: 'general',
    label: 'On a schedule',
    description: 'Runs the flow every day, hour, or custom interval.',
    icon: LuClock as IconComponent, color: '#3b82f6' },
  { appEvent: 'on_webhook', eventType: 'webhook', category: 'general',
    label: 'On webhook call',
    description: 'Runs the flow on receiving an HTTP request.',
    icon: LuGlobe as IconComponent, color: '#8b5cf6' },
  { appEvent: 'on_error', eventType: 'error', category: 'general',
    label: 'On error',
    description: 'Runs the flow when another flow throws an error.',
    icon: LuTriangleAlert as IconComponent, color: '#ef4444' },

  // ── WhatsApp / Wachat ───────────────────────────────────────────────────
  { appEvent: 'whatsapp_message_received', eventType: 'webhook', category: 'whatsapp',
    label: 'New WhatsApp message',
    description: 'A contact sends an inbound message on any connected number.',
    icon: LuMessageCircle as IconComponent, color: '#25d366' },
  { appEvent: 'whatsapp_message_read', eventType: 'webhook', category: 'whatsapp',
    label: 'Message read',
    description: 'A user opens and reads a message you sent.',
    icon: LuMailOpen as IconComponent, color: '#34d399' },
  { appEvent: 'whatsapp_message_failed', eventType: 'webhook', category: 'whatsapp',
    label: 'Message delivery failed',
    description: 'A sent message bounces or fails to reach the recipient.',
    icon: LuCircleX as IconComponent, color: '#ef4444' },
  { appEvent: 'whatsapp_template_approved', eventType: 'webhook', category: 'whatsapp',
    label: 'Template approved',
    description: 'A submitted WhatsApp template is approved by Meta.',
    icon: LuFileCheck as IconComponent, color: '#10b981' },
  { appEvent: 'whatsapp_template_rejected', eventType: 'webhook', category: 'whatsapp',
    label: 'Template rejected',
    description: 'Meta rejects a submitted template with a reason.',
    icon: LuFileX as IconComponent, color: '#ef4444' },
  { appEvent: 'whatsapp_contact_opted_in', eventType: 'webhook', category: 'whatsapp',
    label: 'Contact opted in',
    description: 'A user sends RESUME or re-subscribes to your business.',
    icon: LuCircleCheck as IconComponent, color: '#22c55e' },
  { appEvent: 'whatsapp_contact_opted_out', eventType: 'webhook', category: 'whatsapp',
    label: 'Contact opted out',
    description: 'A user sends STOP or unsubscribes from your business.',
    icon: LuBan as IconComponent, color: '#f43f5e' },
  { appEvent: 'whatsapp_phone_quality_updated', eventType: 'webhook', category: 'whatsapp',
    label: 'Phone number quality changed',
    description: 'WABA quality rating drops or improves for a number.',
    icon: LuSignal as IconComponent, color: '#facc15' },
  { appEvent: 'whatsapp_phone_verified', eventType: 'webhook', category: 'whatsapp',
    label: 'Phone number verified',
    description: 'Display name verification is approved by Meta.',
    icon: LuShieldAlert as IconComponent, color: '#10b981' },
  { appEvent: 'whatsapp_account_violation', eventType: 'webhook', category: 'whatsapp',
    label: 'Account violation detected',
    description: 'WABA receives a restriction or policy warning.',
    icon: LuShieldAlert as IconComponent, color: '#ef4444' },
  { appEvent: 'whatsapp_account_disabled', eventType: 'webhook', category: 'whatsapp',
    label: 'Account disabled',
    description: 'WhatsApp Business account is banned or disabled.',
    icon: LuPower as IconComponent, color: '#dc2626' },

  // ── Calls / Voice ───────────────────────────────────────────────────────
  { appEvent: 'call_incoming', eventType: 'webhook', category: 'calls',
    label: 'Incoming call',
    description: 'A contact initiates a WhatsApp voice call to your business.',
    icon: LuPhoneIncoming as IconComponent, color: '#0ea5e9' },
  { appEvent: 'call_outgoing_started', eventType: 'webhook', category: 'calls',
    label: 'Outgoing call started',
    description: 'Your business places a call to a contact.',
    icon: LuPhoneOutgoing as IconComponent, color: '#3b82f6' },
  { appEvent: 'call_answered', eventType: 'webhook', category: 'calls',
    label: 'Call answered',
    description: 'An incoming call is picked up by an agent.',
    icon: LuPhoneCall as IconComponent, color: '#22c55e' },
  { appEvent: 'call_missed', eventType: 'webhook', category: 'calls',
    label: 'Missed call',
    description: 'An incoming call is not answered before the caller hangs up.',
    icon: LuPhoneMissed as IconComponent, color: '#ef4444' },
  { appEvent: 'call_completed', eventType: 'webhook', category: 'calls',
    label: 'Call completed',
    description: 'A call ends normally with both parties connected.',
    icon: LuPhone as IconComponent, color: '#10b981' },
  { appEvent: 'call_terminated', eventType: 'webhook', category: 'calls',
    label: 'Call terminated',
    description: 'A call ends for any reason — answered or missed.',
    icon: LuPhoneOff as IconComponent, color: '#94a3b8' },
  { appEvent: 'calling_settings_updated', eventType: 'webhook', category: 'calls',
    label: 'Calling settings updated',
    description: 'Call hours, restrictions, or SIP config changed.',
    icon: LuSettings as IconComponent, color: '#a3a3a3' },

  // ── CRM · Contacts & Accounts ───────────────────────────────────────────
  { appEvent: 'contact_created', eventType: 'webhook', category: 'crm-contacts',
    label: 'New contact created',
    description: 'A contact record is added to the CRM database.',
    icon: LuUserPlus as IconComponent, color: '#3b82f6' },
  { appEvent: 'contact_updated', eventType: 'webhook', category: 'crm-contacts',
    label: 'Contact updated',
    description: 'Name, phone, email, or tags on a contact change.',
    icon: LuUser as IconComponent, color: '#60a5fa' },
  { appEvent: 'contact_tagged', eventType: 'webhook', category: 'crm-contacts',
    label: 'Contact tagged',
    description: 'A contact is assigned a new tag or label.',
    icon: LuTag as IconComponent, color: '#a855f7' },
  { appEvent: 'contact_assigned', eventType: 'webhook', category: 'crm-contacts',
    label: 'Contact assigned',
    description: 'Ownership of a contact transfers to a different team member.',
    icon: LuUserCheck as IconComponent, color: '#0ea5e9' },
  { appEvent: 'contact_merged', eventType: 'webhook', category: 'crm-contacts',
    label: 'Contacts merged',
    description: 'Two duplicate contact records are consolidated into one.',
    icon: LuMerge as IconComponent, color: '#8b5cf6' },
  { appEvent: 'contact_imported', eventType: 'webhook', category: 'crm-contacts',
    label: 'Contacts imported',
    description: 'A CSV or file-based contact import completes.',
    icon: LuUpload as IconComponent, color: '#06b6d4' },
  { appEvent: 'account_created', eventType: 'webhook', category: 'crm-contacts',
    label: 'New account created',
    description: 'A company or organisation account is added to the CRM.',
    icon: LuBuilding as IconComponent, color: '#3b82f6' },
  { appEvent: 'account_updated', eventType: 'webhook', category: 'crm-contacts',
    label: 'Account updated',
    description: 'Account details (name, industry, size) are modified.',
    icon: LuBuilding as IconComponent, color: '#60a5fa' },
  { appEvent: 'contact_note_added', eventType: 'webhook', category: 'crm-contacts',
    label: 'Note added to contact',
    description: 'A team member leaves a note on a contact record.',
    icon: LuStickyNote as IconComponent, color: '#fbbf24' },

  // ── CRM · Deals ─────────────────────────────────────────────────────────
  { appEvent: 'deal_created', eventType: 'webhook', category: 'crm-deals',
    label: 'New deal created',
    description: 'A sales opportunity is added to a pipeline.',
    icon: LuBriefcase as IconComponent, color: '#6366f1' },
  { appEvent: 'deal_moved', eventType: 'webhook', category: 'crm-deals',
    label: 'Deal moved to stage',
    description: 'A deal transitions between pipeline stages.',
    icon: LuArrowRightLeft as IconComponent, color: '#a855f7' },
  { appEvent: 'deal_closed_won', eventType: 'webhook', category: 'crm-deals',
    label: 'Deal closed — won',
    description: 'A deal is marked as completed and won.',
    icon: LuTrendingUp as IconComponent, color: '#10b981' },
  { appEvent: 'deal_closed_lost', eventType: 'webhook', category: 'crm-deals',
    label: 'Deal closed — lost',
    description: 'A deal is marked as completed and lost.',
    icon: LuTrendingDown as IconComponent, color: '#ef4444' },
  { appEvent: 'deal_assigned', eventType: 'webhook', category: 'crm-deals',
    label: 'Deal assigned',
    description: 'Deal ownership transfers to a team member.',
    icon: LuUserCheck as IconComponent, color: '#0ea5e9' },
  { appEvent: 'deal_probability_updated', eventType: 'webhook', category: 'crm-deals',
    label: 'Deal probability updated',
    description: 'Win probability percentage on a deal changes.',
    icon: LuPercent as IconComponent, color: '#fbbf24' },
  { appEvent: 'deal_value_updated', eventType: 'webhook', category: 'crm-deals',
    label: 'Deal value changed',
    description: 'Deal amount or currency is modified.',
    icon: LuDollarSign as IconComponent, color: '#10b981' },

  // ── CRM · Leads ─────────────────────────────────────────────────────────
  { appEvent: 'lead_created', eventType: 'webhook', category: 'crm-leads',
    label: 'New lead created',
    description: 'A lead record is added to the pipeline.',
    icon: LuTarget as IconComponent, color: '#8b5cf6' },
  { appEvent: 'lead_status_changed', eventType: 'webhook', category: 'crm-leads',
    label: 'Lead status changed',
    description: 'A lead moves through pipeline stages (new → contacted → qualified).',
    icon: LuFlag as IconComponent, color: '#a855f7' },
  { appEvent: 'lead_assigned', eventType: 'webhook', category: 'crm-leads',
    label: 'Lead assigned',
    description: 'A lead is delegated to a sales representative.',
    icon: LuUserCheck as IconComponent, color: '#0ea5e9' },
  { appEvent: 'lead_converted', eventType: 'webhook', category: 'crm-leads',
    label: 'Lead converted',
    description: 'A lead progresses to a sales opportunity.',
    icon: LuArrowRightLeft as IconComponent, color: '#10b981' },
  { appEvent: 'lead_source_tracked', eventType: 'webhook', category: 'crm-leads',
    label: 'Lead source recorded',
    description: 'Lead attribution is tracked (campaign, form, referral, etc.).',
    icon: LuHistory as IconComponent, color: '#f59e0b' },
  { appEvent: 'lead_follow_up_due', eventType: 'schedule', category: 'crm-leads',
    label: 'Lead follow-up due',
    description: 'The next scheduled follow-up time arrives.',
    icon: LuCalendarClock as IconComponent, color: '#fbbf24' },

  // ── CRM · Invoices & Payments ───────────────────────────────────────────
  { appEvent: 'invoice_created', eventType: 'webhook', category: 'crm-sales',
    label: 'Invoice created',
    description: 'A sales invoice is generated for an account.',
    icon: LuFileText as IconComponent, color: '#10b981' },
  { appEvent: 'invoice_sent', eventType: 'webhook', category: 'crm-sales',
    label: 'Invoice sent',
    description: 'An invoice is delivered to a customer (email or WhatsApp).',
    icon: LuSend as IconComponent, color: '#22c55e' },
  { appEvent: 'invoice_marked_paid', eventType: 'webhook', category: 'crm-sales',
    label: 'Invoice marked paid',
    description: 'An invoice payment is received and recorded.',
    icon: LuCheck as IconComponent, color: '#10b981' },
  { appEvent: 'invoice_payment_received', eventType: 'webhook', category: 'crm-sales',
    label: 'Payment received',
    description: 'A payment is processed against an outstanding invoice.',
    icon: LuCircleDollarSign as IconComponent, color: '#22c55e' },
  { appEvent: 'invoice_overdue', eventType: 'schedule', category: 'crm-sales',
    label: 'Invoice overdue',
    description: 'An invoice due date passes without payment.',
    icon: LuCalendarClock as IconComponent, color: '#ef4444' },
  { appEvent: 'payment_receipt_created', eventType: 'webhook', category: 'crm-sales',
    label: 'Payment receipt created',
    description: 'A receipt is generated after payment collection.',
    icon: LuReceipt as IconComponent, color: '#10b981' },
  { appEvent: 'quotation_created', eventType: 'webhook', category: 'crm-sales',
    label: 'Quotation created',
    description: 'A quote is generated for a prospect.',
    icon: LuFileSpreadsheet as IconComponent, color: '#3b82f6' },
  { appEvent: 'quotation_sent', eventType: 'webhook', category: 'crm-sales',
    label: 'Quotation sent',
    description: 'A quote is delivered and shared with a customer.',
    icon: LuSend as IconComponent, color: '#0ea5e9' },

  // ── CRM · Products & Inventory ──────────────────────────────────────────
  { appEvent: 'product_created', eventType: 'webhook', category: 'crm-products',
    label: 'Product added',
    description: 'A new SKU is added to the product catalog.',
    icon: LuPackage as IconComponent, color: '#f59e0b' },
  { appEvent: 'product_updated', eventType: 'webhook', category: 'crm-products',
    label: 'Product updated',
    description: 'Price, description, or stock level on a product changes.',
    icon: LuPackageOpen as IconComponent, color: '#fbbf24' },
  { appEvent: 'product_stock_low', eventType: 'webhook', category: 'crm-products',
    label: 'Product stock low',
    description: 'Inventory count drops below the configured minimum level.',
    icon: LuPackageOpen as IconComponent, color: '#f97316' },
  { appEvent: 'product_stock_out', eventType: 'webhook', category: 'crm-products',
    label: 'Product out of stock',
    description: 'Inventory for a product reaches zero.',
    icon: LuPackageX as IconComponent, color: '#ef4444' },
  { appEvent: 'product_price_changed', eventType: 'webhook', category: 'crm-products',
    label: 'Product price changed',
    description: 'Unit price or cost on a product is updated.',
    icon: LuTags as IconComponent, color: '#fbbf24' },
  { appEvent: 'warehouse_stock_updated', eventType: 'webhook', category: 'crm-products',
    label: 'Warehouse stock updated',
    description: 'Stock quantity changes at a specific warehouse location.',
    icon: LuWarehouse as IconComponent, color: '#a855f7' },

  // ── CRM · Tasks ─────────────────────────────────────────────────────────
  { appEvent: 'task_created', eventType: 'webhook', category: 'crm-tasks',
    label: 'Task created',
    description: 'An activity or task is assigned to a team member or contact.',
    icon: LuListTodo as IconComponent, color: '#a855f7' },
  { appEvent: 'task_assigned', eventType: 'webhook', category: 'crm-tasks',
    label: 'Task assigned',
    description: 'A task delegation changes owner.',
    icon: LuClipboardList as IconComponent, color: '#8b5cf6' },
  { appEvent: 'task_completed', eventType: 'webhook', category: 'crm-tasks',
    label: 'Task completed',
    description: 'A task is marked as done.',
    icon: LuClipboardCheck as IconComponent, color: '#10b981' },
  { appEvent: 'task_due', eventType: 'schedule', category: 'crm-tasks',
    label: 'Task due',
    description: 'A task deadline is reached.',
    icon: LuCalendarClock as IconComponent, color: '#f59e0b' },
  { appEvent: 'crm_automation_triggered', eventType: 'webhook', category: 'crm-tasks',
    label: 'CRM automation triggered',
    description: 'A rule-based CRM automation executes (assignment, scoring, etc.).',
    icon: LuZap as IconComponent, color: '#f97316' },

  // ── Broadcasts ──────────────────────────────────────────────────────────
  { appEvent: 'broadcast_created', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast created',
    description: 'A new bulk message campaign is added.',
    icon: LuMegaphone as IconComponent, color: '#ec4899' },
  { appEvent: 'broadcast_scheduled', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast scheduled',
    description: 'A campaign is queued for a scheduled send.',
    icon: LuCalendarClock as IconComponent, color: '#f472b6' },
  { appEvent: 'broadcast_sent', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast sent',
    description: 'A campaign begins delivery to recipients.',
    icon: LuTriggerPlay as IconComponent, color: '#a855f7' },
  { appEvent: 'broadcast_completed', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast completed',
    description: 'All messages in a campaign are delivered (or retries exhausted).',
    icon: LuPlayCircle as IconComponent, color: '#10b981' },
  { appEvent: 'broadcast_paused', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast paused',
    description: 'Campaign delivery is halted mid-send.',
    icon: LuPauseCircle as IconComponent, color: '#facc15' },
  { appEvent: 'broadcast_resumed', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast resumed',
    description: 'A previously paused campaign resumes delivery.',
    icon: LuRefreshCw as IconComponent, color: '#0ea5e9' },
  { appEvent: 'broadcast_failed', eventType: 'webhook', category: 'broadcasts',
    label: 'Broadcast failed',
    description: 'A campaign cannot complete due to an error.',
    icon: LuTriangleAlert as IconComponent, color: '#ef4444' },

  // ── Templates ───────────────────────────────────────────────────────────
  { appEvent: 'template_submitted', eventType: 'webhook', category: 'templates',
    label: 'Template submitted',
    description: 'A new template is sent to Meta for review.',
    icon: LuFileCode as IconComponent, color: '#f97316' },
  { appEvent: 'template_quality_updated', eventType: 'webhook', category: 'templates',
    label: 'Template quality changed',
    description: 'A template’s performance score or rating updates.',
    icon: LuSignal as IconComponent, color: '#fbbf24' },
  { appEvent: 'template_edited', eventType: 'webhook', category: 'templates',
    label: 'Template edited',
    description: 'Template content or components are modified.',
    icon: LuFileText as IconComponent, color: '#f59e0b' },

  // ── Facebook & Instagram ────────────────────────────────────────────────
  { appEvent: 'facebook_message_received', eventType: 'webhook', category: 'social',
    label: 'Facebook message received',
    description: 'An inbound message arrives on a connected Facebook page.',
    icon: LuFacebook as IconComponent, color: '#1877f2' },
  { appEvent: 'instagram_message_received', eventType: 'webhook', category: 'social',
    label: 'Instagram message received',
    description: 'An inbound DM arrives on an Instagram business account.',
    icon: LuInstagram as IconComponent, color: '#e1306c' },
  { appEvent: 'facebook_broadcast_sent', eventType: 'webhook', category: 'social',
    label: 'Facebook broadcast sent',
    description: 'A Messenger bulk message is sent to recipients.',
    icon: LuMegaphone as IconComponent, color: '#1877f2' },
  { appEvent: 'facebook_webhook_update', eventType: 'webhook', category: 'social',
    label: 'Facebook webhook update',
    description: 'Custom Facebook webhook data is received.',
    icon: LuPlugZap as IconComponent, color: '#3b82f6' },

  // ── Email & SMS ─────────────────────────────────────────────────────────
  { appEvent: 'email_sent', eventType: 'webhook', category: 'email-sms',
    label: 'Email sent',
    description: 'An email message is dispatched to a recipient.',
    icon: LuMail as IconComponent, color: '#0ea5e9' },
  { appEvent: 'email_opened', eventType: 'webhook', category: 'email-sms',
    label: 'Email opened',
    description: 'A recipient opens a sent email (tracking required).',
    icon: LuMailOpen as IconComponent, color: '#3b82f6' },
  { appEvent: 'email_clicked', eventType: 'webhook', category: 'email-sms',
    label: 'Email link clicked',
    description: 'A recipient clicks a tracked link inside an email.',
    icon: LuMousePointer as IconComponent, color: '#8b5cf6' },
  { appEvent: 'sms_message_sent', eventType: 'webhook', category: 'email-sms',
    label: 'SMS message sent',
    description: 'An SMS delivery is initiated.',
    icon: LuSmartphone as IconComponent, color: '#06b6d4' },
  { appEvent: 'sms_delivery_confirmed', eventType: 'webhook', category: 'email-sms',
    label: 'SMS delivery confirmed',
    description: 'An SMS reaches the recipient phone.',
    icon: LuCheckCircle as IconComponent, color: '#10b981' },

  // ── Payments (WhatsApp Pay) ─────────────────────────────────────────────
  { appEvent: 'payment_received', eventType: 'webhook', category: 'payments',
    label: 'Payment received',
    description: 'A customer completes a payment through WhatsApp Pay.',
    icon: LuCreditCard as IconComponent, color: '#22c55e' },
  { appEvent: 'payment_failed', eventType: 'webhook', category: 'payments',
    label: 'Payment failed',
    description: 'A payment transaction is declined or cancelled.',
    icon: LuCircleX as IconComponent, color: '#ef4444' },
  { appEvent: 'payment_configuration_updated', eventType: 'webhook', category: 'payments',
    label: 'Payment configuration updated',
    description: 'Payment settings on a connected number change.',
    icon: LuSettings as IconComponent, color: '#a3a3a3' },

  // ── Orders & Commerce ───────────────────────────────────────────────────
  { appEvent: 'order_created', eventType: 'webhook', category: 'orders',
    label: 'New order created',
    description: 'A customer places a new order via the commerce platform.',
    icon: LuShoppingCart as IconComponent, color: '#fb923c' },
  { appEvent: 'order_updated', eventType: 'webhook', category: 'orders',
    label: 'Order updated',
    description: 'An order’s status or details change.',
    icon: LuShoppingBag as IconComponent, color: '#f97316' },
  { appEvent: 'order_shipped', eventType: 'webhook', category: 'orders',
    label: 'Order shipped',
    description: 'Fulfilment is completed and tracking is available.',
    icon: LuTruck as IconComponent, color: '#22c55e' },
  { appEvent: 'catalog_product_event', eventType: 'webhook', category: 'orders',
    label: 'Catalog product event',
    description: 'Price or inventory changes for a product in the catalog.',
    icon: LuTags as IconComponent, color: '#fbbf24' },

  // ── SEO & Analytics ─────────────────────────────────────────────────────
  { appEvent: 'seo_audit_completed', eventType: 'webhook', category: 'seo',
    label: 'SEO audit completed',
    description: 'A website SEO analysis finishes and a report is generated.',
    icon: LuChartLine as IconComponent, color: '#14b8a6' },
  { appEvent: 'ranking_improved', eventType: 'webhook', category: 'seo',
    label: 'Keyword ranking improved',
    description: 'A tracked keyword position improves in SERP.',
    icon: LuArrowUp as IconComponent, color: '#10b981' },
  { appEvent: 'ranking_dropped', eventType: 'webhook', category: 'seo',
    label: 'Keyword ranking dropped',
    description: 'A tracked keyword position declines in SERP.',
    icon: LuArrowDown as IconComponent, color: '#ef4444' },
  { appEvent: 'indexing_issue_detected', eventType: 'webhook', category: 'seo',
    label: 'Indexing issue detected',
    description: 'A page crawl or index error is discovered by the SEO module.',
    icon: LuSearch as IconComponent, color: '#f59e0b' },

  // ── Integrations ────────────────────────────────────────────────────────
  { appEvent: 'webhook_received', eventType: 'webhook', category: 'integrations',
    label: 'Custom webhook received',
    description: 'A custom HTTP POST hits the workflow webhook endpoint.',
    icon: LuPlugZap as IconComponent, color: '#94a3b8' },
  { appEvent: 'integration_connected', eventType: 'webhook', category: 'integrations',
    label: 'Integration connected',
    description: 'A third-party OAuth or API integration is authenticated.',
    icon: LuPlug as IconComponent, color: '#22c55e' },
  { appEvent: 'integration_disconnected', eventType: 'webhook', category: 'integrations',
    label: 'Integration disconnected',
    description: 'API credentials are revoked or expire on an integration.',
    icon: LuLink as IconComponent, color: '#ef4444' },
  { appEvent: 'whatsapp_flow_triggered', eventType: 'webhook', category: 'integrations',
    label: 'WhatsApp Flow triggered',
    description: 'A Meta Interactive Form (Flow) is initiated by a user.',
    icon: LuMessageSquare as IconComponent, color: '#25d366' },
];
