// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Remove a attachment from a account  (scope: crm:accounts:write, tier: FREE)
export const DELETE = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/crm/accounts/${encodeURIComponent(String((params as Record<string, string>).accountId ?? ''))}/attachments/${encodeURIComponent(String((params as Record<string, string>).attachmentId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'DELETE',
    },
  );
  return NextResponse.json(data);
}, { scope: 'crm:accounts:write' });
