import {
  Search, Mail, Ticket, Receipt, Share2, Users2, Zap, Palette, File,
  Database, FormInput, MessageSquare, Headphones, Users, Wrench,
  Activity, Cloud, BarChart2, Calendar, Github, GitBranch, FileText,
} from 'lucide-react';

export const iconBatch05: Record<string, { icon: any; iconColor: string }> = {
  // E
  'ecwid': { icon: Zap, iconColor: 'text-gray-500' },
  'ecwid-enhanced': { icon: Zap, iconColor: 'text-gray-500' },
  'egoi': { icon: Zap, iconColor: 'text-gray-500' },
  'eightx8': { icon: Zap, iconColor: 'text-gray-500' },
  'elastic': { icon: Search, iconColor: 'text-teal-500' },
  'elastic-apm': { icon: Search, iconColor: 'text-teal-500' },
  'elasticsearch': { icon: Search, iconColor: 'text-teal-500' },
  'elasticsearch-enhanced': { icon: Search, iconColor: 'text-teal-500' },
  'elevenlabs': { icon: Zap, iconColor: 'text-gray-500' },
  'elevenlabs-enhanced': { icon: Zap, iconColor: 'text-gray-500' },
  'eloqua': { icon: Zap, iconColor: 'text-gray-500' },
  'email': { icon: Mail, iconColor: 'text-blue-500' },
  'emma': { icon: Zap, iconColor: 'text-gray-500' },
  'erpnext': { icon: Zap, iconColor: 'text-gray-500' },
  'etsy': { icon: Zap, iconColor: 'text-gray-500' },
  'eventbrite': { icon: Ticket, iconColor: 'text-orange-500' },
  'everhour': { icon: Zap, iconColor: 'text-gray-500' },
  'exotel': { icon: Zap, iconColor: 'text-gray-500' },
  'expensify-enhanced': { icon: Receipt, iconColor: 'text-green-500' },

  // F
  'facebook-ads': { icon: Share2, iconColor: 'text-blue-600' },
  'facebook-pages': { icon: Share2, iconColor: 'text-blue-600' },
  'factorial': { icon: Users2, iconColor: 'text-pink-500' },
  'fastly': { icon: Zap, iconColor: 'text-red-500' },
  'fauna': { icon: Zap, iconColor: 'text-gray-500' },
  'feishu': { icon: Zap, iconColor: 'text-gray-500' },
  'figma': { icon: Palette, iconColor: 'text-purple-500' },
  'figma-enhanced': { icon: Palette, iconColor: 'text-purple-500' },
  'file-uploader': { icon: File, iconColor: 'text-gray-500' },
  'filestack': { icon: File, iconColor: 'text-gray-500' },
  'fillout': { icon: Zap, iconColor: 'text-gray-500' },
  'finicity': { icon: Zap, iconColor: 'text-gray-500' },
  'firebase': { icon: Database, iconColor: 'text-orange-500' },
  'firebase-enhanced': { icon: Database, iconColor: 'text-orange-500' },
  'fireworks-ai': { icon: Zap, iconColor: 'text-gray-500' },
  'five9': { icon: Zap, iconColor: 'text-gray-500' },
  'fixerio': { icon: Zap, iconColor: 'text-gray-500' },
  'fivetran-enhanced': { icon: Zap, iconColor: 'text-gray-500' },
  'flock': { icon: Zap, iconColor: 'text-gray-500' },
  'flowise': { icon: Zap, iconColor: 'text-gray-500' },
  'flowdash': { icon: Zap, iconColor: 'text-gray-500' },
  'flutterwave': { icon: Zap, iconColor: 'text-gray-500' },
  'fly-io': { icon: Zap, iconColor: 'text-gray-500' },
  'folk-crm': { icon: Zap, iconColor: 'text-gray-500' },
  'fonnte': { icon: Zap, iconColor: 'text-gray-500' },
  'formio': { icon: Zap, iconColor: 'text-gray-500' },
  'formstack': { icon: FormInput, iconColor: 'text-blue-500' },
  'formstack-documents': { icon: FormInput, iconColor: 'text-blue-500' },
  'framer': { icon: Zap, iconColor: 'text-gray-500' },
  'freshbooks': { icon: Receipt, iconColor: 'text-teal-500' },
  'freshbooks-enhanced': { icon: Receipt, iconColor: 'text-teal-500' },
  'freshchat': { icon: MessageSquare, iconColor: 'text-green-500' },
  'freshdesk': { icon: Headphones, iconColor: 'text-teal-500' },
  'freshdesk-enhanced': { icon: Headphones, iconColor: 'text-teal-500' },
  'freshping': { icon: Zap, iconColor: 'text-gray-500' },
  'freshsales': { icon: Users, iconColor: 'text-teal-500' },
  'freshservice': { icon: Wrench, iconColor: 'text-teal-500' },
  'freshworks': { icon: Zap, iconColor: 'text-gray-500' },
  'front': { icon: Mail, iconColor: 'text-pink-500' },
  'frontegg': { icon: Zap, iconColor: 'text-gray-500' },
  'fullcontact': { icon: Zap, iconColor: 'text-gray-500' },
  'fullstory': { icon: Activity, iconColor: 'text-blue-500' },
  'fusionauth': { icon: Zap, iconColor: 'text-gray-500' },

  // G
  'g2': { icon: Zap, iconColor: 'text-gray-500' },
  'gainsight': { icon: Zap, iconColor: 'text-gray-500' },
  'gemini': { icon: Zap, iconColor: 'text-gray-500' },
  'genesys-cloud': { icon: Zap, iconColor: 'text-gray-500' },
  'getaccept': { icon: Zap, iconColor: 'text-gray-500' },
  'getresponse': { icon: Zap, iconColor: 'text-gray-500' },
  'ghost': { icon: FileText, iconColor: 'text-gray-700' },
  'ghost-admin': { icon: FileText, iconColor: 'text-gray-700' },
  'ghost-cms': { icon: FileText, iconColor: 'text-gray-700' },
  'ghost-enhanced': { icon: FileText, iconColor: 'text-gray-700' },
  'giphy': { icon: Zap, iconColor: 'text-gray-500' },
  'gitea': { icon: Zap, iconColor: 'text-gray-500' },
  'github': { icon: Github, iconColor: 'text-gray-800' },
  'github-actions': { icon: Github, iconColor: 'text-gray-800' },
  'github-enhanced': { icon: Github, iconColor: 'text-gray-800' },
  'gitlab': { icon: GitBranch, iconColor: 'text-orange-500' },
  'gitlab-enhanced': { icon: GitBranch, iconColor: 'text-orange-500' },
  'gladly': { icon: Zap, iconColor: 'text-gray-500' },
  'glide': { icon: Zap, iconColor: 'text-gray-500' },
  'gmail': { icon: Zap, iconColor: 'text-gray-500' },
  'gmail-enhanced': { icon: Zap, iconColor: 'text-gray-500' },
  'gocardless': { icon: Zap, iconColor: 'text-gray-500' },
  'gong': { icon: Zap, iconColor: 'text-gray-500' },
  'google-ads': { icon: Zap, iconColor: 'text-gray-500' },
  'google-ads-enhanced': { icon: Zap, iconColor: 'text-gray-500' },
  'google-analytics-enhanced': { icon: BarChart2, iconColor: 'text-orange-500' },
  'google-analytics4': { icon: BarChart2, iconColor: 'text-orange-500' },
  'google-bigquery': { icon: Zap, iconColor: 'text-gray-500' },
  'google-calendar': { icon: Calendar, iconColor: 'text-blue-500' },
  'google-calendar-enhanced': { icon: Calendar, iconColor: 'text-blue-500' },
  'google-chat': { icon: Zap, iconColor: 'text-gray-500' },
  'google-classroom': { icon: Zap, iconColor: 'text-gray-500' },
  'google-cloud-dataflow': { icon: Cloud, iconColor: 'text-blue-500' },
  'google-cloud-functions': { icon: Cloud, iconColor: 'text-blue-500' },
  'google-cloud-storage': { icon: Cloud, iconColor: 'text-blue-500' },
};
