import {
  Radio, FileText, Users, Mail, Zap, Calendar, BarChart2, Layout,
  PenLine, Users2, CreditCard, Phone, Workflow, Grid3x3, Shield,
  Package, Search, TrendingUp, ShoppingCart, Terminal, Bot, Server,
  Webhook, Globe, Activity,
} from 'lucide-react';

export const iconBatch01: Record<string, { icon: any; iconColor: string }> = {
  'ably': { icon: Radio, iconColor: 'text-purple-500' },
  'abstract': { icon: FileText, iconColor: 'text-gray-500' },
  'abstract-api': { icon: FileText, iconColor: 'text-gray-500' },
  'actionnetwork': { icon: Users, iconColor: 'text-orange-500' },
  'activecampaign': { icon: Mail, iconColor: 'text-blue-500' },
  'activecampaign-enhanced': { icon: Mail, iconColor: 'text-blue-500' },
  'activepieces': { icon: Zap, iconColor: 'text-orange-500' },
  'acuity': { icon: Calendar, iconColor: 'text-blue-500' },
  'acuity-enhanced': { icon: Calendar, iconColor: 'text-blue-500' },
  'acuity-scheduling': { icon: Calendar, iconColor: 'text-blue-500' },
  'acumatica': { icon: BarChart2, iconColor: 'text-blue-600' },
  'adalo': { icon: Layout, iconColor: 'text-purple-500' },
  'adobe-pdf': { icon: FileText, iconColor: 'text-red-500' },
  'adobe-sign': { icon: PenLine, iconColor: 'text-red-500' },
  'adobe-sign-enhanced': { icon: PenLine, iconColor: 'text-red-500' },
  'adp': { icon: Users2, iconColor: 'text-red-500' },
  'adp-api': { icon: Users2, iconColor: 'text-red-500' },
  'adyen': { icon: CreditCard, iconColor: 'text-blue-600' },
  'adyen-enhanced': { icon: CreditCard, iconColor: 'text-blue-600' },
  'affinity': { icon: Users, iconColor: 'text-blue-500' },
  'affinity-crm': { icon: Users, iconColor: 'text-blue-500' },
  'agilecrm': { icon: Users, iconColor: 'text-teal-500' },
  'aircall': { icon: Phone, iconColor: 'text-green-500' },
  'airflow-enhanced': { icon: Workflow, iconColor: 'text-indigo-500' },
  'airtable': { icon: Grid3x3, iconColor: 'text-teal-500' },
  'airtable-enhanced': { icon: Grid3x3, iconColor: 'text-teal-500' },
  'akamai': { icon: Shield, iconColor: 'text-blue-600' },
  'akeneo': { icon: Package, iconColor: 'text-blue-500' },
  'algolia': { icon: Search, iconColor: 'text-blue-500' },
  'algolia-enhanced': { icon: Search, iconColor: 'text-blue-500' },
  'alphaVantage': { icon: TrendingUp, iconColor: 'text-green-500' },
  'amazon-connect': { icon: Phone, iconColor: 'text-orange-500' },
  'amazon-ses-v2': { icon: Mail, iconColor: 'text-orange-500' },
  'amazon-sp-api': { icon: ShoppingCart, iconColor: 'text-orange-500' },
  'amplitude': { icon: BarChart2, iconColor: 'text-blue-500' },
  'amplitude-enhanced': { icon: BarChart2, iconColor: 'text-blue-500' },
  'ansible-awx': { icon: Terminal, iconColor: 'text-red-500' },
  'anthropic': { icon: Bot, iconColor: 'text-violet-500' },
  'anthropic-claude': { icon: Bot, iconColor: 'text-violet-500' },
  'anthropic-enhanced': { icon: Bot, iconColor: 'text-violet-500' },
  'anytype': { icon: FileText, iconColor: 'text-gray-600' },
  'apache-cassandra': { icon: Server, iconColor: 'text-red-500' },
  'apache-pulsar': { icon: Server, iconColor: 'text-red-500' },
  'apache-superset': { icon: Server, iconColor: 'text-red-500' },
  'api': { icon: Webhook, iconColor: 'text-orange-500' },
  'api-file-processor': { icon: Webhook, iconColor: 'text-orange-500' },
  'apify': { icon: Globe, iconColor: 'text-green-500' },
  'apitemio': { icon: Webhook, iconColor: 'text-blue-500' },
  'apollo': { icon: Users, iconColor: 'text-blue-600' },
  'apollo-enhanced': { icon: Users, iconColor: 'text-blue-600' },
  'appdynamics': { icon: Activity, iconColor: 'text-blue-600' },
  'appointy': { icon: Calendar, iconColor: 'text-blue-500' },
  'appsflyer': { icon: BarChart2, iconColor: 'text-blue-600' },
  'appsheet': { icon: Layout, iconColor: 'text-blue-500' },
  'appsmith': { icon: Layout, iconColor: 'text-blue-500' },
};
