import {
  Cloud, HardDrive, Users2, FolderOpen, ShoppingCart, Database,
  GitBranch, Link, Box, CreditCard, Mail, Globe, Bug, Layout,
  Calendar, Users, BarChart2, MessageSquare, CheckSquare, Shield,
  Code2, Zap, Layers,
} from 'lucide-react';

export const iconBatch03: Record<string, { icon: any; iconColor: string }> = {
  // azure-* (positions 111–121)
  'azure-ad': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-blob': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-cognitive': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-data-factory': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-devops-enhanced': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-devops': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-functions': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-iot': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-openai': { icon: Cloud, iconColor: 'text-blue-600' },
  'azure-service-bus': { icon: Cloud, iconColor: 'text-blue-600' },
  'azuredevops': { icon: Cloud, iconColor: 'text-blue-600' },

  // b* (positions 122–165)
  'bamboo-ci': { icon: Zap, iconColor: 'text-gray-500' },
  'bamboohr-enhanced': { icon: Users2, iconColor: 'text-teal-500' },
  'bamboohr': { icon: Users2, iconColor: 'text-teal-500' },
  'bandsintown': { icon: Zap, iconColor: 'text-gray-500' },
  'bandwidth': { icon: Zap, iconColor: 'text-gray-500' },
  'bannerbear': { icon: Zap, iconColor: 'text-gray-500' },
  'basecamp-enhanced': { icon: FolderOpen, iconColor: 'text-orange-500' },
  'basecamp': { icon: FolderOpen, iconColor: 'text-orange-500' },
  'baserow': { icon: Zap, iconColor: 'text-gray-500' },
  'beeminder': { icon: Zap, iconColor: 'text-gray-500' },
  'benchmark-email': { icon: Zap, iconColor: 'text-gray-500' },
  'betterstack': { icon: Zap, iconColor: 'text-gray-500' },
  'betteruptime': { icon: Zap, iconColor: 'text-gray-500' },
  'bevy': { icon: Zap, iconColor: 'text-gray-500' },
  'bexio': { icon: Zap, iconColor: 'text-gray-500' },
  'bigcommerce-enhanced': { icon: ShoppingCart, iconColor: 'text-blue-500' },
  'bigcommerce': { icon: ShoppingCart, iconColor: 'text-blue-500' },
  'bigquery-enhanced': { icon: Database, iconColor: 'text-blue-500' },
  'bitbucket-enhanced': { icon: GitBranch, iconColor: 'text-blue-500' },
  'bitbucket': { icon: GitBranch, iconColor: 'text-blue-500' },
  'bitly': { icon: Link, iconColor: 'text-orange-500' },
  'bluejeans': { icon: Zap, iconColor: 'text-gray-500' },
  'bluesky': { icon: Zap, iconColor: 'text-gray-500' },
  'bonsai': { icon: Zap, iconColor: 'text-gray-500' },
  'bookafy': { icon: Zap, iconColor: 'text-gray-500' },
  'box-enhanced': { icon: Box, iconColor: 'text-blue-500' },
  'box': { icon: Box, iconColor: 'text-blue-500' },
  'braintree-enhanced': { icon: CreditCard, iconColor: 'text-purple-500' },
  'braintree': { icon: CreditCard, iconColor: 'text-purple-500' },
  'braze-enhanced': { icon: Zap, iconColor: 'text-gray-500' },
  'braze': { icon: Zap, iconColor: 'text-gray-500' },
  'breezy-hr': { icon: Zap, iconColor: 'text-gray-500' },
  'brevo-enhanced': { icon: Mail, iconColor: 'text-blue-500' },
  'brevo': { icon: Mail, iconColor: 'text-blue-500' },
  'brex': { icon: Zap, iconColor: 'text-gray-500' },
  'brightcove': { icon: Zap, iconColor: 'text-gray-500' },
  'brightdata': { icon: Zap, iconColor: 'text-gray-500' },
  'browserless': { icon: Zap, iconColor: 'text-gray-500' },
  'bubble': { icon: Zap, iconColor: 'text-gray-500' },
  'buddy-ci': { icon: Zap, iconColor: 'text-gray-500' },
  'budibase': { icon: Zap, iconColor: 'text-gray-500' },
  'bugsnag': { icon: Bug, iconColor: 'text-purple-500' },
  'buildkite': { icon: Zap, iconColor: 'text-gray-500' },
  'bunnycdn': { icon: Zap, iconColor: 'text-gray-500' },
};
