import {
  Database, GitBranch, Braces, CheckSquare, Mic,
  Users, Shield, CreditCard, Mail, Receipt, Cloud, Activity, Bot,
  Brain, Server, Container, Boxes, Network, Zap, Workflow, Cpu, Key,
} from 'lucide-react';

export const iconBatch02: Record<string, { icon: any; iconColor: string }> = {
  'appwrite': { icon: Database, iconColor: 'text-pink-500' },
  'argocd': { icon: GitBranch, iconColor: 'text-orange-500' },
  'array-function': { icon: Braces, iconColor: 'text-gray-500' },
  'asana': { icon: CheckSquare, iconColor: 'text-pink-500' },
  'asana-enhanced': { icon: CheckSquare, iconColor: 'text-pink-500' },
  'assemblyai': { icon: Mic, iconColor: 'text-purple-500' },
  'assemblyai-enhanced': { icon: Mic, iconColor: 'text-purple-500' },
  'attio': { icon: Users, iconColor: 'text-violet-500' },
  'auth0': { icon: Shield, iconColor: 'text-orange-500' },
  'auth0-enhanced': { icon: Shield, iconColor: 'text-orange-500' },
  'auth0-management': { icon: Shield, iconColor: 'text-orange-500' },
  'authorize-net': { icon: CreditCard, iconColor: 'text-blue-500' },
  'autopilot': { icon: Mail, iconColor: 'text-blue-500' },
  'avalara': { icon: Receipt, iconColor: 'text-blue-500' },
  'aweber': { icon: Mail, iconColor: 'text-blue-600' },
  'aws-amplify': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-appsync': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-bedrock': { icon: Bot, iconColor: 'text-orange-500' },
  'aws-cloudformation': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-cloudwatch': { icon: Activity, iconColor: 'text-orange-500' },
  'awscloudwatch': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-codepipeline': { icon: GitBranch, iconColor: 'text-orange-500' },
  'aws-cognito': { icon: Shield, iconColor: 'text-orange-500' },
  'aws-comprehend': { icon: Brain, iconColor: 'text-orange-500' },
  'aws-dynamodb': { icon: Database, iconColor: 'text-orange-500' },
  'awsdynamodb': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-ec2': { icon: Server, iconColor: 'text-orange-500' },
  'aws-ecs': { icon: Container, iconColor: 'text-orange-500' },
  'aws-eks': { icon: Boxes, iconColor: 'text-orange-500' },
  'aws-elb': { icon: Network, iconColor: 'text-orange-500' },
  'aws-eventbridge': { icon: Zap, iconColor: 'text-orange-500' },
  'aws-glue': { icon: Workflow, iconColor: 'text-orange-500' },
  'aws-iam': { icon: Shield, iconColor: 'text-orange-500' },
  'aws-iot': { icon: Cpu, iconColor: 'text-orange-500' },
  'aws-kms': { icon: Key, iconColor: 'text-orange-500' },
  'awslambda': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-lambda-enhanced': { icon: Zap, iconColor: 'text-orange-500' },
  'aws-lightsail': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-polly': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-rds': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-rekognition': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-route53': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-s3': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-s3-enhanced': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-sagemaker': { icon: Cloud, iconColor: 'text-orange-500' },
  'awsses': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-ses-enhanced': { icon: Cloud, iconColor: 'text-orange-500' },
  'awssns': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-sns-enhanced': { icon: Cloud, iconColor: 'text-orange-500' },
  'awssqs': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-sqs-enhanced': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-step-functions': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-textract': { icon: Cloud, iconColor: 'text-orange-500' },
  'aws-transcribe': { icon: Cloud, iconColor: 'text-orange-500' },
  'azure-active-directory': { icon: Cloud, iconColor: 'text-orange-500' },
};
