#!/usr/bin/env -S npx tsx
/**
 * scaffold-forge-block.ts — generate the boilerplate for a new forge block.
 *
 * Usage:
 *   npx tsx scripts/scaffold-forge-block.ts <slug> "Display Name"
 *
 * Examples:
 *   npx tsx scripts/scaffold-forge-block.ts hubspot         "HubSpot"
 *   npx tsx scripts/scaffold-forge-block.ts vapi            "Vapi.ai"
 *
 * Writes `src/lib/sabflow/forge/blocks/<slug>.ts` with a working skeleton —
 * the action throws "TODO" so it's safe to register but obvious it isn't
 * implemented yet.  Prints the line you need to add to
 * `src/lib/sabflow/forge/index.ts` to complete the wiring.
 */

import { writeFile, access } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import process from 'node:process';

const slugArg = process.argv[2];
const nameArg = process.argv[3];

if (!slugArg || !nameArg) {
  console.error(
    'Usage: npx tsx scripts/scaffold-forge-block.ts <slug> "<Display Name>"',
  );
  process.exit(1);
}

const slug = slugArg.toLowerCase().replace(/[^a-z0-9_-]/g, '');
if (!slug) {
  console.error('Slug must contain at least one [a-z0-9_-] character.');
  process.exit(1);
}

const displayName = nameArg.trim();
const credentialType = slug.replace(/-/g, '_');
const blockId = `forge_${credentialType}`;
const filename = `${slug}.ts`;
const outPath = resolve(
  process.cwd(),
  'src/lib/sabflow/forge/blocks',
  filename,
);

(async () => {
  try {
    await access(outPath);
    console.error(`Refusing to overwrite existing file: ${outPath}`);
    process.exit(1);
  } catch {
    /* file does not exist — proceed */
  }

  const content = `/**
 * Forge block: ${displayName}.
 *
 * Generated by scripts/scaffold-forge-block.ts — fill in the TODOs.
 * Reference: docs/INTEGRATION_GUIDE.md
 */

import { registerForgeBlock } from '../registry';
import type {
  ForgeActionContext,
  ForgeActionResult,
  ForgeBlock,
} from '../types';

const str = (v: unknown): string =>
  typeof v === 'string' ? v : v == null ? '' : String(v);

async function defaultAction(
  ctx: ForgeActionContext,
): Promise<ForgeActionResult> {
  // TODO: pull credential + options
  const apiKey = ctx.credential?.apiKey;
  if (!apiKey) {
    throw new Error('${displayName}: select a credential (API key)');
  }
  const target = str(ctx.options.target);
  if (!target) throw new Error('${displayName}: target is required');

  // TODO: replace with the real provider call
  throw new Error(
    '${displayName}: action not implemented yet — edit forge/blocks/${filename}',
  );
}

const block: ForgeBlock = {
  id: '${blockId}',
  name: '${displayName}',
  description: 'TODO: one-line description of ${displayName}.',
  iconName: 'LuPlug',
  category: 'Integration',
  auth: {
    type: 'apiKey',
    credentialType: '${credentialType}' as never,
  },
  actions: [
    {
      id: 'do_thing',
      label: 'Do thing',
      description: 'TODO: single-sentence description of the action.',
      fields: [
        {
          id: 'target',
          label: 'Target',
          type: 'text',
          required: true,
          placeholder: 'TODO',
        },
        {
          id: 'outputVariable',
          label: 'Save response to variable',
          type: 'text',
        },
      ],
      run: defaultAction,
    },
  ],
};

registerForgeBlock(block);
export default block;
`;

  await writeFile(outPath, content, 'utf-8');
  console.log(`✓ Wrote ${outPath}`);
  console.log('');
  console.log('Next:');
  console.log(`  1. Add this line to src/lib/sabflow/forge/index.ts:`);
  console.log(`       import './blocks/${slug.replace(/\\.ts$/, '')}';`);
  console.log(`  2. Implement the TODO in defaultAction()`);
  console.log(`  3. Add '${credentialType}' to CREDENTIAL_TYPES in src/lib/sabflow/credentials/types.ts`);
  console.log(`  4. Run \`npx tsc --noEmit -p tsconfig.json\` to confirm`);
})().catch((err) => {
  console.error('scaffold-forge-block failed:', err);
  process.exit(1);
});

// `join` is imported but unused on success paths; reference it so tsc-strict
// configurations don't flag a dead import.
void join;
