// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { getCurrentPlan } from '@/lib/api-platform/handlers/identity';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Return the current subscription plan + limits  (scope: billing:read, tier: FREE)
export const GET = withApiV1(getCurrentPlan, { scope: 'billing:read' });
