// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Bulk delete carts  (scope: shop:write, tier: FREE)
export const DELETE = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/shop/carts/bulk${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'DELETE',
    },
  );
  return NextResponse.json(data);
}, { scope: 'shop:write' });

// Bulk update carts  (scope: shop:write, tier: FREE)
export const PATCH = withApiV1(async (req, { ctx, params }) => {
  let body: unknown = undefined;
  try { body = await req.json(); } catch { body = undefined; }
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/shop/carts/bulk${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'PATCH',
      body: body === undefined ? undefined : JSON.stringify(body),
    },
  );
  return NextResponse.json(data);
}, { scope: 'shop:write' });

// Bulk create carts  (scope: shop:write, tier: FREE)
export const POST = withApiV1(async (req, { ctx, params }) => {
  let body: unknown = undefined;
  try { body = await req.json(); } catch { body = undefined; }
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/shop/carts/bulk${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'POST',
      body: body === undefined ? undefined : JSON.stringify(body),
    },
  );
  return NextResponse.json(data);
}, { scope: 'shop:write' });
