// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { NextResponse } from 'next/server';
import { withApiV1 } from '@/lib/api-platform';
import { rustFetchAsUser } from '@/lib/api-platform/rust-as-user';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// Delete chats  (scope: sabwa:write, tier: FREE)
export const DELETE = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/sabwa/chats/${encodeURIComponent(String((params as Record<string, string>).chatId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'DELETE',
    },
  );
  return NextResponse.json(data);
}, { scope: 'sabwa:write' });

// Get chats  (scope: sabwa:read, tier: FREE)
export const GET = withApiV1(async (req, { ctx, params }) => {
  void params;
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/sabwa/chats/${encodeURIComponent(String((params as Record<string, string>).chatId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'GET',
    },
  );
  return NextResponse.json(data);
}, { scope: 'sabwa:read' });

// Update chats  (scope: sabwa:write, tier: FREE)
export const PATCH = withApiV1(async (req, { ctx, params }) => {
  let body: unknown = undefined;
  try { body = await req.json(); } catch { body = undefined; }
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/sabwa/chats/${encodeURIComponent(String((params as Record<string, string>).chatId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'PATCH',
      body: body === undefined ? undefined : JSON.stringify(body),
    },
  );
  return NextResponse.json(data);
}, { scope: 'sabwa:write' });

// Replace chats  (scope: sabwa:write, tier: FREE)
export const PUT = withApiV1(async (req, { ctx, params }) => {
  let body: unknown = undefined;
  try { body = await req.json(); } catch { body = undefined; }
  const url = new URL(req.url);
  const qs = url.searchParams.toString();
  const path = `/v1/sabwa/chats/${encodeURIComponent(String((params as Record<string, string>).chatId ?? ''))}${qs ? `?${qs}` : ''}`;
  const data = await rustFetchAsUser<unknown>(
    ctx.tenantId,
    path,
    {
      method: 'PUT',
      body: body === undefined ? undefined : JSON.stringify(body),
    },
  );
  return NextResponse.json(data);
}, { scope: 'sabwa:write' });
