// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */

/** All OAuth / API-key scopes recognised by the platform. */
export type OAuthScope =
  | '*'
  | 'ads:read'
  | 'ads:write'
  | 'billing:read'
  | 'broadcasts:read'
  | 'broadcasts:write'
  | 'builder:read'
  | 'builder:write'
  | 'calls:read'
  | 'calls:write'
  | 'contacts:read'
  | 'contacts:write'
  | 'crm:accounting:read'
  | 'crm:accounting:write'
  | 'crm:accounts:read'
  | 'crm:accounts:write'
  | 'crm:analytics:read'
  | 'crm:analytics:write'
  | 'crm:contacts:read'
  | 'crm:contacts:write'
  | 'crm:content:read'
  | 'crm:content:write'
  | 'crm:deals:read'
  | 'crm:deals:write'
  | 'crm:hr:read'
  | 'crm:hr:write'
  | 'crm:inventory:read'
  | 'crm:inventory:write'
  | 'crm:leads:read'
  | 'crm:leads:write'
  | 'crm:marketing:read'
  | 'crm:marketing:write'
  | 'crm:pipelines:read'
  | 'crm:pipelines:write'
  | 'crm:portal:read'
  | 'crm:portal:write'
  | 'crm:projects:read'
  | 'crm:projects:write'
  | 'crm:purchases:read'
  | 'crm:purchases:write'
  | 'crm:sales:read'
  | 'crm:sales:write'
  | 'crm:settings:read'
  | 'crm:settings:write'
  | 'crm:support:read'
  | 'crm:support:write'
  | 'email:read'
  | 'email:send'
  | 'email:write'
  | 'embed:read'
  | 'embed:write'
  | 'facebook:read'
  | 'facebook:write'
  | 'instagram:read'
  | 'instagram:write'
  | 'integrations:read'
  | 'integrations:write'
  | 'keys:read'
  | 'keys:write'
  | 'me:read'
  | 'messages:read'
  | 'messages:write'
  | 'meta:read'
  | 'meta:write'
  | 'notifications:read'
  | 'notifications:send'
  | 'notifications:write'
  | 'oauth:apps:read'
  | 'oauth:apps:write'
  | 'portfolio:read'
  | 'portfolio:write'
  | 'projects:read'
  | 'projects:write'
  | 'qr:read'
  | 'qr:write'
  | 'sabchat:read'
  | 'sabchat:write'
  | 'sabcrm:read'
  | 'sabcrm:write'
  | 'sabfiles:read'
  | 'sabfiles:write'
  | 'sabwa:read'
  | 'sabwa:write'
  | 'seo:read'
  | 'seo:write'
  | 'shop:read'
  | 'shop:write'
  | 'telegram:read'
  | 'telegram:write'
  | 'templates:read'
  | 'templates:write'
  | 'urls:read'
  | 'urls:write'
  | 'wachat:read'
  | 'wachat:write'
  | 'webhooks:read'
  | 'webhooks:write';

export const ALL_SCOPES: ReadonlyArray<OAuthScope> = [
  '*',
  'ads:read',
  'ads:write',
  'billing:read',
  'broadcasts:read',
  'broadcasts:write',
  'builder:read',
  'builder:write',
  'calls:read',
  'calls:write',
  'contacts:read',
  'contacts:write',
  'crm:accounting:read',
  'crm:accounting:write',
  'crm:accounts:read',
  'crm:accounts:write',
  'crm:analytics:read',
  'crm:analytics:write',
  'crm:contacts:read',
  'crm:contacts:write',
  'crm:content:read',
  'crm:content:write',
  'crm:deals:read',
  'crm:deals:write',
  'crm:hr:read',
  'crm:hr:write',
  'crm:inventory:read',
  'crm:inventory:write',
  'crm:leads:read',
  'crm:leads:write',
  'crm:marketing:read',
  'crm:marketing:write',
  'crm:pipelines:read',
  'crm:pipelines:write',
  'crm:portal:read',
  'crm:portal:write',
  'crm:projects:read',
  'crm:projects:write',
  'crm:purchases:read',
  'crm:purchases:write',
  'crm:sales:read',
  'crm:sales:write',
  'crm:settings:read',
  'crm:settings:write',
  'crm:support:read',
  'crm:support:write',
  'email:read',
  'email:send',
  'email:write',
  'embed:read',
  'embed:write',
  'facebook:read',
  'facebook:write',
  'instagram:read',
  'instagram:write',
  'integrations:read',
  'integrations:write',
  'keys:read',
  'keys:write',
  'me:read',
  'messages:read',
  'messages:write',
  'meta:read',
  'meta:write',
  'notifications:read',
  'notifications:send',
  'notifications:write',
  'oauth:apps:read',
  'oauth:apps:write',
  'portfolio:read',
  'portfolio:write',
  'projects:read',
  'projects:write',
  'qr:read',
  'qr:write',
  'sabchat:read',
  'sabchat:write',
  'sabcrm:read',
  'sabcrm:write',
  'sabfiles:read',
  'sabfiles:write',
  'sabwa:read',
  'sabwa:write',
  'seo:read',
  'seo:write',
  'shop:read',
  'shop:write',
  'telegram:read',
  'telegram:write',
  'templates:read',
  'templates:write',
  'urls:read',
  'urls:write',
  'wachat:read',
  'wachat:write',
  'webhooks:read',
  'webhooks:write',
] as const;
