// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.

/* eslint-disable */
import { withApiV1 } from '@/lib/api-platform';
import { createKey, listKeys } from '@/lib/api-platform/handlers/identity';

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';

// List the calling tenant’s API keys  (scope: keys:read, tier: FREE)
export const GET = withApiV1(listKeys, { scope: 'keys:read' });

// Generate a new API key  (scope: keys:write, tier: FREE)
export const POST = withApiV1(createKey, { scope: 'keys:write' });
