/**
 * Types extracted from hrm-task-reports.actions.ts
 * to avoid Turbopack 'use server' export restrictions.
 */

export interface HrmTaskReport {
  _id: string;
  userId: string;           // tenant owner
  roadmapId: string;
  phaseId: string;
  taskId: string;           // roadmap task id
  taskTitle: string;
  workerId: string;         // employee _id who completed it
  workerName: string;       // denormalized
  assignerId: string;       // employee _id who created the task/roadmap
  assignerName: string;     // denormalized
  completedAt: string;      // ISO
  notes?: string;           // worker can add notes on completion
  acknowledgedAt?: string;  // when manager acknowledged
  acknowledgedBy?: string;  // manager employee _id
  autoGenerated: true;
}
