'use server';

/**
 * HRM Task Reports — server actions.
 *
 * Auto-reports are written to `hrm_task_reports` when a worker marks a
 * roadmap task as "done" via `updateTaskStatus` in hrm-roadmaps.actions.ts.
 *
 * Tenant isolation: every read/write filters by `userId == session.user._id`.
 * Worker/manager resolution: looks up the logged-in user's employee profile
 * by email within the tenant (`crm_employees`).
 */

import { ObjectId } from 'mongodb';
import { connectToDatabase } from '@/lib/mongodb';
import { getSession } from '@/app/actions/user.actions';
import { getErrorMessage } from '@/lib/utils';
import type { CrmEmployee } from '@/lib/definitions';
import { revalidatePath } from 'next/cache';

// ─── Collection name ──────────────────────────────────────────────────────────

const COLLECTION = 'hrm_task_reports';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface HrmTaskReport {
  _id: string;
  userId: string;           // tenant owner
  roadmapId: string;
  phaseId: string;
  taskId: string;           // roadmap task id
  taskTitle: string;
  workerId: string;         // employee _id who completed it
  workerName: string;       // denormalized
  assignerId: string;       // employee _id who created the task/roadmap
  assignerName: string;     // denormalized
  completedAt: string;      // ISO
  notes?: string;           // worker can add notes on completion
  acknowledgedAt?: string;  // when manager acknowledged
  acknowledgedBy?: string;  // manager employee _id
  autoGenerated: true;
}

// Shape stored in Mongo (uses ObjectId for userId/workerId/assignerId).
export interface HrmTaskReportDoc {
  _id: ObjectId;
  userId: ObjectId;
  roadmapId: string;
  phaseId: string;
  taskId: string;
  taskTitle: string;
  workerId: string;
  workerName: string;
  assignerId: string;
  assignerName: string;
  completedAt: string;
  notes?: string;
  acknowledgedAt?: string;
  acknowledgedBy?: string;
  autoGenerated: true;
  createdAt: string;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Serialises a Mongo doc to the plain-JSON HrmTaskReport shape. */
function toReport(doc: HrmTaskReportDoc): HrmTaskReport {
  return {
    _id: String(doc._id),
    userId: String(doc.userId),
    roadmapId: doc.roadmapId,
    phaseId: doc.phaseId,
    taskId: doc.taskId,
    taskTitle: doc.taskTitle,
    workerId: doc.workerId,
    workerName: doc.workerName,
    assignerId: doc.assignerId,
    assignerName: doc.assignerName,
    completedAt: doc.completedAt,
    notes: doc.notes,
    acknowledgedAt: doc.acknowledgedAt,
    acknowledgedBy: doc.acknowledgedBy,
    autoGenerated: true,
  };
}

/** Finds the calling user's employee record by session email. */
async function resolveMyEmployee(
  db: Awaited<ReturnType<typeof connectToDatabase>>['db'],
  userId: ObjectId,
  email: string,
): Promise<(CrmEmployee & { _id: ObjectId }) | null> {
  const doc = await db
    .collection<CrmEmployee>('crm_employees')
    .findOne({ userId, email });
  return doc ?? null;
}

/** Resolves a display name for a given employee ObjectId string. */
async function resolveEmployeeName(
  db: Awaited<ReturnType<typeof connectToDatabase>>['db'],
  userId: ObjectId,
  employeeId: string,
): Promise<string> {
  if (!employeeId || !ObjectId.isValid(employeeId)) return 'Unknown';
  const doc = await db
    .collection<CrmEmployee>('crm_employees')
    .findOne(
      { _id: new ObjectId(employeeId), userId },
      { projection: { firstName: 1, lastName: 1 } },
    );
  if (!doc) return 'Unknown';
  return `${doc.firstName ?? ''} ${doc.lastName ?? ''}`.trim() || 'Unknown';
}

// ─── Create (called internally by updateTaskStatus) ───────────────────────────

/**
 * Writes an auto-generated task completion report to `hrm_task_reports`.
 * Called by `updateTaskStatus` in hrm-roadmaps.actions.ts when status → "done".
 *
 * The caller supplies denormalized names so no extra Mongo round-trips are
 * needed at query time.
 */
export async function createTaskReport(
  data: Omit<HrmTaskReport, '_id' | 'userId' | 'autoGenerated'>,
): Promise<{ success: boolean; id?: string; error?: string }> {
  const session = await getSession();
  if (!session?.user) return { success: false, error: 'Not authenticated' };

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));
    const now = new Date().toISOString();

    const doc: Omit<HrmTaskReportDoc, '_id'> = {
      userId,
      roadmapId: data.roadmapId,
      phaseId: data.phaseId,
      taskId: data.taskId,
      taskTitle: data.taskTitle,
      workerId: data.workerId,
      workerName: data.workerName,
      assignerId: data.assignerId,
      assignerName: data.assignerName,
      completedAt: data.completedAt,
      notes: data.notes,
      autoGenerated: true,
      createdAt: now,
    };

    const result = await db.collection(COLLECTION).insertOne(doc as never);
    revalidatePath('/dashboard/hrm/portal/reports');
    return { success: true, id: result.insertedId.toString() };
  } catch (e) {
    console.error('[createTaskReport] failed:', e);
    return { success: false, error: getErrorMessage(e) };
  }
}

// ─── Manager inbox ────────────────────────────────────────────────────────────

/**
 * Returns reports where the logged-in employee is the assigner (creator/manager).
 * Optionally filtered by acknowledged state and date range.
 */
export async function getMyTaskReports(filter?: {
  acknowledged?: boolean;
  from?: string;
  to?: string;
}): Promise<HrmTaskReport[]> {
  const session = await getSession();
  if (!session?.user) return [];

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));

    const me = await resolveMyEmployee(db, userId, session.user.email ?? '');
    if (!me) return [];

    const query: Record<string, unknown> = {
      userId,
      assignerId: String(me._id),
    };

    if (filter?.acknowledged === true) {
      query.acknowledgedAt = { $exists: true, $ne: null };
    } else if (filter?.acknowledged === false) {
      query.$or = [
        { acknowledgedAt: { $exists: false } },
        { acknowledgedAt: null },
      ];
    }

    if (filter?.from || filter?.to) {
      const range: Record<string, string> = {};
      if (filter.from) range.$gte = filter.from;
      if (filter.to) range.$lte = filter.to;
      query.completedAt = range;
    }

    const docs = await db
      .collection<HrmTaskReportDoc>(COLLECTION)
      .find(query)
      .sort({ completedAt: -1 })
      .toArray();

    return JSON.parse(JSON.stringify(docs.map(toReport))) as HrmTaskReport[];
  } catch (e) {
    console.error('[getMyTaskReports] failed:', e);
    return [];
  }
}

// ─── Worker history ───────────────────────────────────────────────────────────

/**
 * Returns reports where the logged-in employee is the worker (completer).
 * Read-only history view.
 */
export async function getMyCompletionHistory(filter?: {
  from?: string;
  to?: string;
}): Promise<HrmTaskReport[]> {
  const session = await getSession();
  if (!session?.user) return [];

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));

    const me = await resolveMyEmployee(db, userId, session.user.email ?? '');
    if (!me) return [];

    const query: Record<string, unknown> = {
      userId,
      workerId: String(me._id),
    };

    if (filter?.from || filter?.to) {
      const range: Record<string, string> = {};
      if (filter.from) range.$gte = filter.from;
      if (filter.to) range.$lte = filter.to;
      query.completedAt = range;
    }

    const docs = await db
      .collection<HrmTaskReportDoc>(COLLECTION)
      .find(query)
      .sort({ completedAt: -1 })
      .toArray();

    return JSON.parse(JSON.stringify(docs.map(toReport))) as HrmTaskReport[];
  } catch (e) {
    console.error('[getMyCompletionHistory] failed:', e);
    return [];
  }
}

// ─── Acknowledge ──────────────────────────────────────────────────────────────

/** Marks a single report as acknowledged by the calling manager. */
export async function acknowledgeReport(
  reportId: string,
): Promise<{ success: boolean; error?: string }> {
  if (!reportId || !ObjectId.isValid(reportId)) {
    return { success: false, error: 'Invalid report id.' };
  }

  const session = await getSession();
  if (!session?.user) return { success: false, error: 'Not authenticated' };

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));

    const me = await resolveMyEmployee(db, userId, session.user.email ?? '');
    if (!me) return { success: false, error: 'Employee profile not found.' };

    const result = await db.collection(COLLECTION).updateOne(
      {
        _id: new ObjectId(reportId),
        userId,
        assignerId: String(me._id),
      },
      {
        $set: {
          acknowledgedAt: new Date().toISOString(),
          acknowledgedBy: String(me._id),
        },
      },
    );

    if (result.matchedCount === 0) {
      return { success: false, error: 'Report not found or permission denied.' };
    }

    revalidatePath('/dashboard/hrm/portal/reports');
    return { success: true };
  } catch (e) {
    console.error('[acknowledgeReport] failed:', e);
    return { success: false, error: getErrorMessage(e) };
  }
}

/** Bulk-acknowledges multiple reports by the calling manager. */
export async function bulkAcknowledgeReports(
  ids: string[],
): Promise<{ success: boolean; count: number; error?: string }> {
  if (!ids.length) return { success: true, count: 0 };

  const validIds = ids.filter((id) => ObjectId.isValid(id));
  if (!validIds.length) return { success: false, count: 0, error: 'No valid ids.' };

  const session = await getSession();
  if (!session?.user) return { success: false, count: 0, error: 'Not authenticated' };

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));

    const me = await resolveMyEmployee(db, userId, session.user.email ?? '');
    if (!me) return { success: false, count: 0, error: 'Employee profile not found.' };

    const now = new Date().toISOString();
    const result = await db.collection(COLLECTION).updateMany(
      {
        _id: { $in: validIds.map((id) => new ObjectId(id)) },
        userId,
        assignerId: String(me._id),
        $or: [{ acknowledgedAt: { $exists: false } }, { acknowledgedAt: null }],
      },
      {
        $set: {
          acknowledgedAt: now,
          acknowledgedBy: String(me._id),
        },
      },
    );

    revalidatePath('/dashboard/hrm/portal/reports');
    return { success: true, count: result.modifiedCount };
  } catch (e) {
    console.error('[bulkAcknowledgeReports] failed:', e);
    return { success: false, count: 0, error: getErrorMessage(e) };
  }
}

// ─── KPIs ─────────────────────────────────────────────────────────────────────

/** Returns manager-perspective KPI cards for the Reports Inbox. */
export async function getReportKpis(): Promise<
  { label: string; value: number; hint?: string }[]
> {
  const session = await getSession();
  if (!session?.user) return [];

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));

    const me = await resolveMyEmployee(db, userId, session.user.email ?? '');
    if (!me) return [];

    const myId = String(me._id);

    const now = new Date();
    const startOfWeek = new Date(now);
    const day = startOfWeek.getDay(); // 0 = Sun
    startOfWeek.setDate(startOfWeek.getDate() - (day === 0 ? 6 : day - 1));
    startOfWeek.setHours(0, 0, 0, 0);
    const weekIso = startOfWeek.toISOString();

    const [total, unacknowledged, acknowledged, thisWeek] = await Promise.all([
      db.collection(COLLECTION).countDocuments({ userId, assignerId: myId }),
      db.collection(COLLECTION).countDocuments({
        userId,
        assignerId: myId,
        $or: [{ acknowledgedAt: { $exists: false } }, { acknowledgedAt: null }],
      }),
      db.collection(COLLECTION).countDocuments({
        userId,
        assignerId: myId,
        acknowledgedAt: { $exists: true, $ne: null },
      }),
      db.collection(COLLECTION).countDocuments({
        userId,
        assignerId: myId,
        completedAt: { $gte: weekIso },
      }),
    ]);

    return [
      { label: 'Total Reports', value: total },
      { label: 'Unacknowledged', value: unacknowledged, hint: 'Needs your attention' },
      { label: 'Acknowledged', value: acknowledged },
      { label: 'This Week', value: thisWeek, hint: 'Reports received this week' },
    ];
  } catch (e) {
    console.error('[getReportKpis] failed:', e);
    return [];
  }
}

// ─── Export data ──────────────────────────────────────────────────────────────

/**
 * Returns all reports in a date range for CSV export.
 * Scoped by the caller's assignerId (manager view).
 */
export async function getReportsForExport(
  from?: string,
  to?: string,
): Promise<HrmTaskReport[]> {
  const session = await getSession();
  if (!session?.user) return [];

  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(String(session.user._id));

    const me = await resolveMyEmployee(db, userId, session.user.email ?? '');
    if (!me) return [];

    const query: Record<string, unknown> = {
      userId,
      assignerId: String(me._id),
    };

    if (from || to) {
      const range: Record<string, string> = {};
      if (from) range.$gte = from;
      if (to) range.$lte = to;
      query.completedAt = range;
    }

    const docs = await db
      .collection<HrmTaskReportDoc>(COLLECTION)
      .find(query)
      .sort({ completedAt: -1 })
      .limit(5000)
      .toArray();

    return JSON.parse(JSON.stringify(docs.map(toReport))) as HrmTaskReport[];
  } catch (e) {
    console.error('[getReportsForExport] failed:', e);
    return [];
  }
}

// ─── Utility (used by hrm-roadmaps to denormalize names) ─────────────────────

/**
 * Resolves a display name for a given employee id string within a tenant.
 * Re-exported so hrm-roadmaps.actions.ts can call it without duplicating logic.
 */
export async function resolveEmployeeNameById(
  tenantUserId: string,
  employeeId: string,
): Promise<string> {
  try {
    const { db } = await connectToDatabase();
    const userId = new ObjectId(tenantUserId);
    return resolveEmployeeName(db, userId, employeeId);
  } catch {
    return 'Unknown';
  }
}
