// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.
/* eslint-disable */

export const dynamic = 'force-static';

const modules: Array<{ name: string; count: number }> = [{"name":"ad-manager","count":188},{"name":"broadcasts","count":6},{"name":"builder","count":564},{"name":"calling","count":96},{"name":"contacts","count":2},{"name":"crm","count":6675},{"name":"email","count":237},{"name":"embed","count":141},{"name":"facebook","count":522},{"name":"identity","count":11},{"name":"instagram","count":281},{"name":"integrations","count":141},{"name":"messages","count":1},{"name":"meta","count":141},{"name":"notifications","count":142},{"name":"oauth","count":3},{"name":"portfolio","count":235},{"name":"qr-codes","count":47},{"name":"reports","count":65},{"name":"sabchat","count":188},{"name":"sabfiles","count":47},{"name":"sabwa","count":146},{"name":"seo","count":223},{"name":"shop","count":846},{"name":"sms","count":1},{"name":"telegram","count":714},{"name":"url-shortener","count":47},{"name":"usage","count":4},{"name":"wachat","count":117},{"name":"webhooks","count":8}];
const total = 11839;

export default function Page() {
  return (
    <div className="max-w-5xl mx-auto px-6 py-8 text-zinc-100">
      <header className="mb-8">
        <h1 className="text-3xl font-bold">API Reference</h1>
        <p className="text-sm text-zinc-400 mt-1">
          {total.toLocaleString()} endpoints across {modules.length} module group{modules.length === 1 ? '' : 's'}.
          Each endpoint has its own page with code samples in 15+ languages and a live test runner.
        </p>
      </header>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
        {modules.map((m) => (
          <a
            key={m.name}
            href={'/api/docs/modules/' + m.name}
            className="block p-4 rounded-md border border-zinc-800 bg-zinc-900/40 hover:bg-zinc-900 hover:border-amber-500/40 transition"
          >
            <div className="font-semibold capitalize">{m.name}</div>
            <div className="text-xs text-zinc-400 mt-1">{m.count.toLocaleString()} endpoint{m.count === 1 ? '' : 's'}</div>
          </a>
        ))}
      </div>
    </div>
  );
}
