// @generated by tools/api-codegen — DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.
/* eslint-disable */

export const dynamic = 'force-static';

const modules: Array<{ name: string; count: number }> = [{"name":"ad-manager","count":188},{"name":"broadcasts","count":6},{"name":"builder","count":564},{"name":"calling","count":96},{"name":"contacts","count":2},{"name":"crm","count":6675},{"name":"email","count":237},{"name":"embed","count":141},{"name":"facebook","count":522},{"name":"identity","count":11},{"name":"instagram","count":281},{"name":"integrations","count":141},{"name":"messages","count":1},{"name":"meta","count":139},{"name":"notifications","count":142},{"name":"oauth","count":3},{"name":"portfolio","count":235},{"name":"qr-codes","count":47},{"name":"reports","count":65},{"name":"sabchat","count":188},{"name":"sabfiles","count":45},{"name":"sabwa","count":146},{"name":"seo","count":223},{"name":"shop","count":846},{"name":"telegram","count":714},{"name":"url-shortener","count":47},{"name":"usage","count":4},{"name":"wachat","count":117},{"name":"webhooks","count":8}];
const total = 11834;

export default function Page() {
  return (
    <div className="zoruui min-h-screen bg-zoru-bg text-zoru-ink">
      <div className="max-w-5xl mx-auto px-6 py-8">
        <header className="mb-8">
          <h1 className="text-3xl font-semibold tracking-tight text-zoru-ink">API Reference</h1>
          <p className="text-sm text-zoru-ink-muted mt-2">
            {total.toLocaleString()} endpoints across {modules.length} module group{modules.length === 1 ? '' : 's'}.
            Each endpoint has its own page with code samples in 15+ languages and a live test runner.
          </p>
        </header>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {modules.map((m) => (
            <a
              key={m.name}
              href={'/api/docs/modules/' + m.name}
              className="block p-4 rounded-[var(--zoru-radius)] border border-zoru-line bg-zoru-surface text-zoru-ink shadow-[var(--zoru-shadow-sm)] transition-[border-color,box-shadow,background-color] hover:bg-zoru-surface-2 hover:border-zoru-line-strong hover:shadow-[var(--zoru-shadow-md)]"
            >
              <div className="text-[14px] font-medium capitalize text-zoru-ink">{m.name}</div>
              <div className="text-[12.5px] text-zoru-ink-muted mt-1">{m.count.toLocaleString()} endpoint{m.count === 1 ? '' : 's'}</div>
            </a>
          ))}
        </div>
      </div>
    </div>
  );
}
