// @generated by tools/api-codegen - DO NOT EDIT BY HAND.
// To change this file, edit the manifest in tools/api-manifest/ and run `pnpm api:gen`.
/* eslint-disable */
'use client';

import Link from 'next/link';

import {
  PageHeader,
  PageHeaderHeading,
  PageTitle,
  PageDescription,
  Card,
  CardTitle,
  CardDescription,
} from '@/components/sabcrm/20ui';

const modules: Array<{ name: string; count: number }> = [{"name":"ad-manager","count":188},{"name":"broadcasts","count":6},{"name":"builder","count":564},{"name":"calling","count":96},{"name":"contacts","count":2},{"name":"crm","count":6675},{"name":"email","count":237},{"name":"embed","count":141},{"name":"facebook","count":522},{"name":"identity","count":11},{"name":"instagram","count":281},{"name":"integrations","count":141},{"name":"messages","count":1},{"name":"meta","count":139},{"name":"notifications","count":142},{"name":"oauth","count":3},{"name":"portfolio","count":235},{"name":"qr-codes","count":47},{"name":"reports","count":65},{"name":"sabchat","count":188},{"name":"sabfiles","count":45},{"name":"sabwa","count":146},{"name":"seo","count":223},{"name":"shop","count":846},{"name":"telegram","count":714},{"name":"url-shortener","count":47},{"name":"usage","count":4},{"name":"wachat","count":117},{"name":"webhooks","count":8}];
const total = 11834;

export default function Page() {
  return (
    <div className="ui20 min-h-screen bg-[var(--st-bg)] text-[var(--st-text)]">
      <div className="max-w-5xl mx-auto px-6 py-8">
        <PageHeader className="mb-8">
          <PageHeaderHeading>
            <PageTitle>API Reference</PageTitle>
            <PageDescription>
              {total.toLocaleString()} endpoints across {modules.length} module group{modules.length === 1 ? '' : 's'}.
              Each endpoint has its own page with code samples in 15+ languages and a live test runner.
            </PageDescription>
          </PageHeaderHeading>
        </PageHeader>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {modules.map((m) => (
            <Link
              key={m.name}
              href={'/api/docs/modules/' + m.name}
              className="block no-underline focus:outline-none"
            >
              <Card variant="interactive" padding="md" className="h-full">
                <CardTitle className="capitalize">{m.name}</CardTitle>
                <CardDescription>
                  {m.count.toLocaleString()} endpoint{m.count === 1 ? '' : 's'}
                </CardDescription>
              </Card>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
