/**
 * SabCRM — Standard object schema.
 *
 * Faithful port of Twenty's standard objects (Companies, People, Opportunities,
 * Notes, Tasks, Activities) into SabNode's native CRM `ObjectMetadata` shape.
 *
 * This module is pure, dependency-free metadata. It is safe to import from both
 * client and server code. Persisted custom objects/fields are merged on top of
 * these defaults in `objects.server.ts`.
 */

import type { ObjectMetadata } from './types';

/**
 * The six standard CRM objects shipped with every project.
 *
 * Field/relation definitions mirror Twenty's standard data model so that imports,
 * views and relations behave the same way they do in upstream Twenty.
 */
export const STANDARD_OBJECTS: ObjectMetadata[] = [
  {
    slug: 'companies',
    labelSingular: 'Company',
    labelPlural: 'Companies',
    icon: 'building-2',
    standard: true,
    views: ['table', 'board'],
    fields: [
      {
        key: 'name',
        label: 'Name',
        type: 'TEXT',
        icon: 'building-2',
        required: true,
        inTable: true,
        isLabel: true,
        description: "The company's legal name",
      },
      {
        key: 'domainName',
        label: 'Domain Name',
        type: 'LINK',
        icon: 'globe',
        inTable: true,
        description: "Company's official website domain",
      },
      {
        key: 'address',
        label: 'Address',
        type: 'TEXT',
        icon: 'map-pin',
        inTable: false,
        description: "Company's physical address",
      },
      {
        key: 'employees',
        label: 'Employees',
        type: 'NUMBER',
        icon: 'users',
        inTable: true,
        description: 'Number of employees',
      },
      {
        key: 'linkedinLink',
        label: 'LinkedIn',
        type: 'LINK',
        icon: 'linkedin',
        inTable: false,
        description: 'LinkedIn company profile URL',
      },
      {
        key: 'xLink',
        label: 'X (Twitter)',
        type: 'LINK',
        icon: 'twitter',
        inTable: false,
        description: 'X (formerly Twitter) company handle',
      },
      {
        key: 'annualRecurringRevenue',
        label: 'Annual Recurring Revenue',
        type: 'CURRENCY',
        icon: 'dollar-sign',
        inTable: true,
        description: 'ARR in USD',
      },
      {
        key: 'idealCustomerProfile',
        label: 'Ideal Customer Profile',
        type: 'BOOLEAN',
        icon: 'target',
        inTable: true,
        description: 'Whether this is an ideal customer profile',
      },
      {
        key: 'accountOwner',
        label: 'Account Owner',
        type: 'RELATION',
        icon: 'user-check',
        inTable: true,
        description: 'Primary account owner/team member',
        relation: {
          targetObject: 'workspaceMembers',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'people',
        label: 'People',
        type: 'RELATION',
        icon: 'contact',
        inTable: false,
        description: 'People associated with this company',
        relation: {
          targetObject: 'people',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
      {
        key: 'opportunities',
        label: 'Opportunities',
        type: 'RELATION',
        icon: 'briefcase',
        inTable: false,
        description: 'Sales opportunities with this company',
        relation: {
          targetObject: 'opportunities',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
    ],
  },
  {
    slug: 'people',
    labelSingular: 'Person',
    labelPlural: 'People',
    icon: 'users',
    standard: true,
    views: ['table', 'board'],
    fields: [
      {
        key: 'firstName',
        label: 'First Name',
        type: 'TEXT',
        icon: 'user',
        required: true,
        inTable: true,
      },
      {
        key: 'lastName',
        label: 'Last Name',
        type: 'TEXT',
        icon: 'user',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'email',
        label: 'Email',
        type: 'EMAIL',
        icon: 'mail',
        inTable: true,
      },
      {
        key: 'phone',
        label: 'Phone',
        type: 'PHONE',
        icon: 'phone',
        inTable: true,
      },
      {
        key: 'jobTitle',
        label: 'Job Title',
        type: 'TEXT',
        icon: 'briefcase',
        inTable: true,
      },
      {
        key: 'city',
        label: 'City',
        type: 'TEXT',
        icon: 'map-pin',
        inTable: false,
      },
      {
        key: 'linkedinLink',
        label: 'LinkedIn',
        type: 'LINK',
        icon: 'linkedin',
        inTable: false,
      },
      {
        key: 'xLink',
        label: 'X (Twitter)',
        type: 'LINK',
        icon: 'twitter',
        inTable: false,
      },
      {
        key: 'avatar',
        label: 'Avatar',
        type: 'FILE',
        icon: 'image',
        inTable: false,
      },
      {
        key: 'company',
        label: 'Company',
        type: 'RELATION',
        icon: 'building',
        inTable: true,
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
    ],
  },
  {
    slug: 'opportunities',
    labelSingular: 'Opportunity',
    labelPlural: 'Opportunities',
    icon: 'briefcase',
    standard: true,
    views: ['table', 'board'],
    fields: [
      {
        key: 'name',
        label: 'Name',
        type: 'TEXT',
        icon: 'type',
        description: 'The name or title of the opportunity',
        required: true,
        inTable: true,
        isLabel: true,
        system: false,
      },
      {
        key: 'amount',
        label: 'Amount',
        type: 'CURRENCY',
        icon: 'dollar-sign',
        description: 'Expected deal value',
        inTable: true,
        system: false,
      },
      {
        key: 'closeDate',
        label: 'Close Date',
        type: 'DATE_TIME',
        icon: 'calendar',
        description: 'Expected closing date for the deal',
        inTable: true,
        system: false,
      },
      {
        key: 'stage',
        label: 'Stage',
        type: 'SELECT',
        icon: 'list',
        description: 'Current stage in the sales pipeline',
        required: true,
        inTable: true,
        system: false,
        options: [
          { value: 'NEW', label: 'New', color: '--zoru-sky' },
          { value: 'SCREENING', label: 'Screening', color: '--zoru-blue' },
          { value: 'MEETING', label: 'Meeting', color: '--zoru-purple' },
          { value: 'PROPOSAL', label: 'Proposal', color: '--zoru-orange' },
          { value: 'CUSTOMER', label: 'Customer', color: '--zoru-green' },
        ],
        defaultValue: 'NEW',
      },
      {
        key: 'pointOfContact',
        label: 'Point of Contact',
        type: 'RELATION',
        icon: 'user',
        description: 'Primary contact person for this opportunity',
        inTable: true,
        system: false,
        relation: {
          targetObject: 'people',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'company',
        label: 'Company',
        type: 'RELATION',
        icon: 'building-2',
        description: 'Company this opportunity is associated with',
        required: true,
        inTable: true,
        system: false,
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
    ],
    board: { groupByField: 'stage' },
  },
  {
    slug: 'notes',
    labelSingular: 'Note',
    labelPlural: 'Notes',
    icon: 'note',
    standard: true,
    views: ['table'],
    fields: [
      {
        key: 'title',
        label: 'Title',
        type: 'TEXT',
        icon: 'heading2',
        description: 'The title or subject of the note',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'body',
        label: 'Body',
        type: 'TEXT',
        icon: 'file-text',
        description: 'The main content of the note (rich text)',
        required: false,
        inTable: false,
      },
      {
        key: 'createdBy',
        label: 'Created By',
        type: 'TEXT',
        icon: 'user',
        description: 'User who created the note',
        required: false,
        inTable: true,
        system: true,
      },
      {
        key: 'targetCompanies',
        label: 'Companies',
        type: 'RELATION',
        icon: 'building2',
        description: 'Companies this note is related to',
        required: false,
        inTable: false,
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'targetPeople',
        label: 'People',
        type: 'RELATION',
        icon: 'user',
        description: 'People this note is related to',
        required: false,
        inTable: false,
        relation: {
          targetObject: 'people',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'targetOpportunities',
        label: 'Opportunities',
        type: 'RELATION',
        icon: 'zap',
        description: 'Opportunities this note is related to',
        required: false,
        inTable: false,
        relation: {
          targetObject: 'opportunities',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
    ],
  },
  {
    slug: 'tasks',
    labelSingular: 'Task',
    labelPlural: 'Tasks',
    icon: 'check-circle-2',
    standard: true,
    views: ['table', 'board'],
    fields: [
      {
        key: 'title',
        label: 'Title',
        type: 'TEXT',
        icon: 'heading-2',
        description: 'Task title',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'body',
        label: 'Body',
        type: 'TEXT',
        icon: 'align-left',
        description: 'Detailed description of the task',
        inTable: false,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'SELECT',
        icon: 'circle-dot',
        description: 'Current status of the task',
        required: true,
        inTable: true,
        defaultValue: 'TODO',
        options: [
          { value: 'TODO', label: 'To Do', color: '--zoru-brand-lighter' },
          { value: 'IN_PROGRESS', label: 'In Progress', color: '--zoru-warning-lighter' },
          { value: 'DONE', label: 'Done', color: '--zoru-success-lighter' },
        ],
      },
      {
        key: 'dueAt',
        label: 'Due Date',
        type: 'DATE_TIME',
        icon: 'calendar',
        description: 'When the task is due',
        inTable: true,
      },
      {
        key: 'assignee',
        label: 'Assignee',
        type: 'RELATION',
        icon: 'user',
        description: 'Person responsible for this task',
        inTable: true,
        relation: {
          targetObject: 'people',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
    ],
    board: { groupByField: 'status' },
  },
  {
    slug: 'activities',
    labelSingular: 'Activity',
    labelPlural: 'Activities',
    icon: 'activity-square',
    standard: true,
    views: ['table', 'board'],
    fields: [
      {
        key: 'type',
        label: 'Type',
        type: 'SELECT',
        icon: 'list',
        description: 'Category of activity',
        required: true,
        inTable: true,
        options: [
          { value: 'NOTE', label: 'Note', color: '--zoru-blue-50' },
          { value: 'TASK', label: 'Task', color: '--zoru-purple-50' },
          { value: 'CALL', label: 'Call', color: '--zoru-green-50' },
          { value: 'MEETING', label: 'Meeting', color: '--zoru-orange-50' },
          { value: 'EMAIL', label: 'Email', color: '--zoru-pink-50' },
        ],
      },
      {
        key: 'title',
        label: 'Title',
        type: 'TEXT',
        icon: 'heading-2',
        description: 'Subject or brief description of the activity',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'body',
        label: 'Body',
        type: 'TEXT',
        icon: 'file-text',
        description: 'Detailed description or notes for the activity',
        inTable: false,
      },
      {
        key: 'happenedAt',
        label: 'Happened At',
        type: 'DATE_TIME',
        icon: 'clock',
        description: 'When the activity occurred or is scheduled',
        required: true,
        inTable: true,
      },
      {
        key: 'targetObject',
        label: 'Target Object',
        type: 'TEXT',
        icon: 'target',
        description:
          'Slug of the object this activity relates to (e.g., companies, people, opportunities)',
        inTable: false,
      },
      {
        key: 'targetRecordId',
        label: 'Target Record',
        type: 'TEXT',
        icon: 'link-2',
        description: 'ID of the specific record this activity relates to',
        inTable: false,
      },
    ],
    board: { groupByField: 'type' },
  },
];

/** Set of standard object slugs for quick membership checks. */
export const STANDARD_OBJECT_SLUGS: ReadonlySet<string> = new Set(
  STANDARD_OBJECTS.map((o) => o.slug),
);

/**
 * Look up a standard object definition by slug.
 * Returns `undefined` for unknown / custom slugs.
 */
export function getStandardObject(slug: string): ObjectMetadata | undefined {
  return STANDARD_OBJECTS.find((o) => o.slug === slug);
}
