/**
 * SabCRM — Standard object schema.
 *
 * Faithful port of Twenty's standard objects (Companies, People, Opportunities,
 * Notes, Tasks, Activities) into SabNode's native CRM `ObjectMetadata` shape.
 *
 * This module is pure, dependency-free metadata. It is safe to import from both
 * client and server code. Persisted custom objects/fields are merged on top of
 * these defaults in `objects.server.ts`.
 */

import type { ObjectMetadata } from './types';

/**
 * The six standard CRM objects shipped with every project.
 *
 * Field/relation definitions mirror Twenty's standard data model so that imports,
 * views and relations behave the same way they do in upstream Twenty.
 */
export const STANDARD_OBJECTS: ObjectMetadata[] = [
  {
    slug: 'companies',
    labelSingular: 'Company',
    labelPlural: 'Companies',
    icon: 'building-2',
    standard: true,
    views: ['table', 'board'],
    // Twenty default "All Companies" table columns, in order:
    // name, domainName, createdBy, accountOwner, createdAt, employees,
    // linkedinLink, address.
    fields: [
      {
        key: 'name',
        label: 'Name',
        type: 'TEXT',
        icon: 'building-2',
        required: true,
        inTable: true,
        isLabel: true,
        description: 'The company name',
      },
      {
        key: 'domainName',
        label: 'Domain Name',
        type: 'LINKS',
        icon: 'globe',
        inTable: true,
        description: "Company's domain name",
      },
      {
        key: 'createdBy',
        label: 'Created by',
        type: 'ACTOR',
        icon: 'user',
        inTable: true,
        system: true,
        description: 'The creator of the record',
      },
      {
        key: 'accountOwner',
        label: 'Account Owner',
        type: 'RELATION',
        icon: 'user-check',
        inTable: true,
        description: 'Your team member responsible for managing the company account',
        relation: {
          targetObject: 'workspaceMembers',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'createdAt',
        label: 'Creation date',
        type: 'DATE_TIME',
        icon: 'calendar',
        inTable: true,
        system: true,
        description: 'Creation date',
      },
      {
        key: 'updatedAt',
        label: 'Last update',
        type: 'DATE_TIME',
        icon: 'calendar-clock',
        inTable: false,
        system: true,
        description: 'Last time the record was changed',
      },
      {
        key: 'updatedBy',
        label: 'Updated by',
        type: 'ACTOR',
        icon: 'user-circle',
        inTable: false,
        system: true,
        description: 'The workspace member who last updated the record',
      },
      {
        key: 'employees',
        label: 'Employees',
        type: 'NUMBER',
        icon: 'users',
        inTable: true,
        description: 'Number of employees in the company',
      },
      {
        key: 'linkedinLink',
        label: 'Linkedin',
        type: 'LINKS',
        icon: 'linkedin',
        inTable: true,
        description: "The company Linkedin account",
      },
      {
        key: 'address',
        label: 'Address',
        type: 'ADDRESS',
        icon: 'map-pin',
        inTable: true,
        description: "Address of the company",
      },
      {
        key: 'xLink',
        label: 'X',
        type: 'LINKS',
        icon: 'twitter',
        inTable: false,
        description: "The company Twitter/X account",
      },
      {
        key: 'annualRecurringRevenue',
        label: 'ARR',
        type: 'CURRENCY',
        icon: 'dollar-sign',
        inTable: false,
        description:
          'Annual Recurring Revenue: The actual or estimated annual revenue of the company',
      },
      {
        key: 'idealCustomerProfile',
        label: 'ICP',
        type: 'BOOLEAN',
        icon: 'target',
        inTable: false,
        description:
          'Ideal Customer Profile: Indicates whether the company is the most suitable and valuable customer for you',
      },
      {
        key: 'people',
        label: 'People',
        type: 'RELATION',
        icon: 'contact',
        inTable: false,
        description: 'People linked to the company.',
        relation: {
          targetObject: 'people',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
      {
        key: 'opportunities',
        label: 'Leads',
        type: 'RELATION',
        icon: 'target-arrow',
        inTable: false,
        description: 'Opportunities linked to the company.',
        relation: {
          targetObject: 'leads',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
      {
        key: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        icon: 'paperclip',
        inTable: false,
        system: true,
        description: 'Attachments linked to the company',
        relation: {
          targetObject: 'attachments',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
    ],
  },
  {
    slug: 'people',
    labelSingular: 'Person',
    labelPlural: 'People',
    icon: 'users',
    standard: true,
    views: ['table', 'board'],
    // Twenty default "All People" table columns, in order:
    // name (first+last), emails, createdBy, company, phones, createdAt,
    // city, jobTitle, linkedinLink, xLink.
    fields: [
      {
        key: 'firstName',
        label: 'First Name',
        type: 'TEXT',
        icon: 'user',
        required: true,
        inTable: true,
        description: "Contact's first name",
      },
      {
        key: 'lastName',
        label: 'Last Name',
        type: 'TEXT',
        icon: 'user',
        required: true,
        inTable: true,
        isLabel: true,
        description: "Contact's last name",
      },
      {
        key: 'email',
        label: 'Emails',
        type: 'EMAILS',
        icon: 'mail',
        inTable: true,
        description: "Contact's Emails",
      },
      {
        key: 'createdBy',
        label: 'Created by',
        type: 'ACTOR',
        icon: 'user',
        inTable: true,
        system: true,
        description: 'The creator of the record',
      },
      {
        key: 'company',
        label: 'Company',
        type: 'RELATION',
        icon: 'building',
        inTable: true,
        description: "Contact's company",
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'phone',
        label: 'Phones',
        type: 'PHONES',
        icon: 'phone',
        inTable: true,
        description: "Contact's phone numbers",
      },
      {
        key: 'createdAt',
        label: 'Creation date',
        type: 'DATE_TIME',
        icon: 'calendar',
        inTable: true,
        system: true,
        description: 'Creation date',
      },
      {
        key: 'city',
        label: 'City',
        type: 'TEXT',
        icon: 'map-pin',
        inTable: true,
        description: "Contact's city",
      },
      {
        key: 'jobTitle',
        label: 'Job Title',
        type: 'TEXT',
        icon: 'briefcase',
        inTable: true,
        description: "Contact's job title",
      },
      {
        key: 'linkedinLink',
        label: 'Linkedin',
        type: 'LINKS',
        icon: 'linkedin',
        inTable: true,
        description: "Contact's Linkedin account",
      },
      {
        key: 'xLink',
        label: 'X',
        type: 'LINKS',
        icon: 'twitter',
        inTable: true,
        description: "Contact's X/Twitter account",
      },
      {
        key: 'avatarUrl',
        label: 'Avatar',
        type: 'FILE',
        icon: 'image',
        inTable: false,
        system: true,
        description: "Contact's avatar",
      },
      {
        key: 'updatedAt',
        label: 'Last update',
        type: 'DATE_TIME',
        icon: 'calendar-clock',
        inTable: false,
        system: true,
        description: 'Last time the record was changed',
      },
      {
        key: 'updatedBy',
        label: 'Updated by',
        type: 'ACTOR',
        icon: 'user-circle',
        inTable: false,
        system: true,
        description: 'The workspace member who last updated the record',
      },
      {
        key: 'pointOfContactForOpportunities',
        label: 'Leads',
        type: 'RELATION',
        icon: 'target-arrow',
        inTable: false,
        description:
          'List of opportunities for which that person is the point of contact',
        relation: {
          targetObject: 'leads',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
      {
        key: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        icon: 'paperclip',
        inTable: false,
        system: true,
        description: 'Attachments linked to the contact.',
        relation: {
          targetObject: 'attachments',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
    ],
  },
  {
    slug: 'leads',
    labelSingular: 'Lead',
    labelPlural: 'Leads',
    icon: 'target-arrow',
    standard: true,
    views: ['table', 'board'],
    // Twenty default table columns, in order: name, amount, createdBy,
    // closeDate, company, pointOfContact. `stage` drives the kanban board.
    fields: [
      {
        key: 'name',
        label: 'Name',
        type: 'TEXT',
        icon: 'target-arrow',
        description: 'The opportunity name',
        required: true,
        inTable: true,
        isLabel: true,
        system: false,
      },
      {
        key: 'amount',
        label: 'Amount',
        type: 'CURRENCY',
        icon: 'dollar-sign',
        description: 'Opportunity amount',
        inTable: true,
        system: false,
      },
      {
        key: 'createdBy',
        label: 'Created by',
        type: 'ACTOR',
        icon: 'user',
        description: 'The creator of the record',
        inTable: true,
        system: true,
      },
      {
        key: 'closeDate',
        label: 'Close date',
        type: 'DATE_TIME',
        icon: 'calendar',
        description: 'Opportunity close date',
        inTable: true,
        system: false,
      },
      {
        key: 'company',
        label: 'Company',
        type: 'RELATION',
        icon: 'building-2',
        description: 'Opportunity company',
        inTable: true,
        system: false,
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'pointOfContact',
        label: 'Point of Contact',
        type: 'RELATION',
        icon: 'user',
        description: 'Opportunity point of contact',
        inTable: true,
        system: false,
        relation: {
          targetObject: 'people',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'stage',
        label: 'Stage',
        type: 'SELECT',
        icon: 'progress-check',
        description: 'Opportunity stage',
        required: true,
        inTable: false,
        system: false,
        // Twenty's exact stage options, values, labels, positions and colors.
        options: [
          { value: 'NEW', label: 'New', color: 'red' },
          { value: 'SCREENING', label: 'Screening', color: 'purple' },
          { value: 'MEETING', label: 'Meeting', color: 'sky' },
          { value: 'PROPOSAL', label: 'Proposal', color: 'turquoise' },
          { value: 'CUSTOMER', label: 'Customer', color: 'yellow' },
        ],
        defaultValue: 'NEW',
      },
      {
        key: 'owner',
        label: 'Owner',
        type: 'RELATION',
        icon: 'user-circle',
        description: 'Opportunity owner',
        inTable: false,
        system: false,
        relation: {
          targetObject: 'workspaceMembers',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'updatedAt',
        label: 'Last update',
        type: 'DATE_TIME',
        icon: 'calendar-clock',
        description: 'Last time the record was changed',
        inTable: false,
        system: true,
      },
      {
        key: 'updatedBy',
        label: 'Updated by',
        type: 'ACTOR',
        icon: 'user-circle',
        description: 'The workspace member who last updated the record',
        inTable: false,
        system: true,
      },
      {
        key: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        icon: 'paperclip',
        description: 'Attachments linked to the opportunity',
        inTable: false,
        system: true,
        relation: {
          targetObject: 'attachments',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
    ],
    board: { groupByField: 'stage' },
  },
  {
    slug: 'notes',
    labelSingular: 'Note',
    labelPlural: 'Notes',
    icon: 'note',
    standard: true,
    views: ['table'],
    // Twenty default "All Notes" table columns, in order:
    // title, noteTargets, body (bodyV2), createdBy, createdAt.
    fields: [
      {
        key: 'title',
        label: 'Title',
        type: 'TEXT',
        icon: 'heading2',
        description: 'Note title',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'targetPeople',
        label: 'Relations',
        type: 'RELATION',
        icon: 'arrow-up-right',
        description: 'Note targets',
        required: false,
        inTable: true,
        relation: {
          targetObject: 'people',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'body',
        label: 'Body',
        type: 'RICH_TEXT_V2',
        icon: 'file-text',
        description: 'Note body',
        required: false,
        inTable: true,
      },
      {
        key: 'createdBy',
        label: 'Created by',
        type: 'ACTOR',
        icon: 'user',
        description: 'The creator of the record',
        required: false,
        inTable: true,
        system: true,
      },
      {
        key: 'createdAt',
        label: 'Creation date',
        type: 'DATE_TIME',
        icon: 'calendar',
        description: 'Creation date',
        required: false,
        inTable: true,
        system: true,
      },
      {
        key: 'targetCompanies',
        label: 'Companies',
        type: 'RELATION',
        icon: 'building2',
        description: 'Companies this note is related to',
        required: false,
        inTable: false,
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'targetOpportunities',
        label: 'Leads',
        type: 'RELATION',
        icon: 'target-arrow',
        description: 'Opportunities this note is related to',
        required: false,
        inTable: false,
        relation: {
          targetObject: 'leads',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'updatedAt',
        label: 'Last update',
        type: 'DATE_TIME',
        icon: 'calendar-clock',
        description: 'Last time the record was changed',
        required: false,
        inTable: false,
        system: true,
      },
      {
        key: 'updatedBy',
        label: 'Updated by',
        type: 'ACTOR',
        icon: 'user-circle',
        description: 'The workspace member who last updated the record',
        required: false,
        inTable: false,
        system: true,
      },
      {
        key: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        icon: 'paperclip',
        description: 'Note attachments',
        required: false,
        inTable: false,
        system: true,
        relation: {
          targetObject: 'attachments',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
    ],
  },
  {
    slug: 'tasks',
    labelSingular: 'Task',
    labelPlural: 'Tasks',
    icon: 'checkbox',
    standard: true,
    views: ['table', 'board'],
    // Twenty default "All Tasks" table columns, in order: title, status,
    // taskTargets (relations), createdBy, dueAt, assignee, body, createdAt.
    // Kanban board groups by `status`.
    fields: [
      {
        key: 'title',
        label: 'Title',
        type: 'TEXT',
        icon: 'heading-2',
        description: 'Task title',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'status',
        label: 'Status',
        type: 'SELECT',
        icon: 'circle-dot',
        description: 'Task status',
        required: false,
        inTable: true,
        defaultValue: 'TODO',
        // Twenty's exact status options, values, labels and colors.
        options: [
          { value: 'TODO', label: 'To do', color: 'sky' },
          { value: 'IN_PROGRESS', label: 'In progress', color: 'purple' },
          { value: 'DONE', label: 'Done', color: 'green' },
        ],
      },
      {
        key: 'targetPeople',
        label: 'Relations',
        type: 'RELATION',
        icon: 'arrow-up-right',
        description: 'Task targets',
        required: false,
        inTable: true,
        relation: {
          targetObject: 'people',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'assignee',
        label: 'Assignee',
        type: 'RELATION',
        icon: 'user-circle',
        description: 'Task assignee',
        inTable: true,
        relation: {
          targetObject: 'workspaceMembers',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'createdBy',
        label: 'Created by',
        type: 'ACTOR',
        icon: 'user',
        description: 'The creator of the record',
        inTable: true,
        system: true,
      },
      {
        key: 'dueAt',
        label: 'Due Date',
        type: 'DATE_TIME',
        icon: 'calendar',
        description: 'Task due date',
        inTable: true,
      },
      {
        key: 'body',
        label: 'Body',
        type: 'RICH_TEXT_V2',
        icon: 'align-left',
        description: 'Task body',
        inTable: true,
      },
      {
        key: 'createdAt',
        label: 'Creation date',
        type: 'DATE_TIME',
        icon: 'calendar',
        description: 'Creation date',
        inTable: true,
        system: true,
      },
      {
        key: 'targetCompanies',
        label: 'Companies',
        type: 'RELATION',
        icon: 'building2',
        description: 'Companies this task is related to',
        inTable: false,
        relation: {
          targetObject: 'companies',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'targetOpportunities',
        label: 'Leads',
        type: 'RELATION',
        icon: 'target-arrow',
        description: 'Opportunities this task is related to',
        inTable: false,
        relation: {
          targetObject: 'leads',
          kind: 'MANY_TO_ONE',
          labelField: 'name',
        },
      },
      {
        key: 'updatedAt',
        label: 'Last update',
        type: 'DATE_TIME',
        icon: 'calendar-clock',
        description: 'Last time the record was changed',
        inTable: false,
        system: true,
      },
      {
        key: 'updatedBy',
        label: 'Updated by',
        type: 'ACTOR',
        icon: 'user-circle',
        description: 'The workspace member who last updated the record',
        inTable: false,
        system: true,
      },
      {
        key: 'attachments',
        label: 'Attachments',
        type: 'RELATION',
        icon: 'paperclip',
        description: 'Task attachments',
        inTable: false,
        system: true,
        relation: {
          targetObject: 'attachments',
          kind: 'ONE_TO_MANY',
          labelField: 'name',
        },
      },
    ],
    board: { groupByField: 'status' },
  },
  {
    slug: 'activities',
    labelSingular: 'Activity',
    labelPlural: 'Activities',
    icon: 'activity-square',
    standard: true,
    views: ['table', 'board'],
    fields: [
      {
        key: 'type',
        label: 'Type',
        type: 'SELECT',
        icon: 'list',
        description: 'Category of activity',
        required: true,
        inTable: true,
        options: [
          { value: 'NOTE', label: 'Note', color: '--zoru-blue-50' },
          { value: 'TASK', label: 'Task', color: '--zoru-purple-50' },
          { value: 'CALL', label: 'Call', color: '--zoru-green-50' },
          { value: 'MEETING', label: 'Meeting', color: '--zoru-orange-50' },
          { value: 'EMAIL', label: 'Email', color: '--zoru-pink-50' },
        ],
      },
      {
        key: 'title',
        label: 'Title',
        type: 'TEXT',
        icon: 'heading-2',
        description: 'Subject or brief description of the activity',
        required: true,
        inTable: true,
        isLabel: true,
      },
      {
        key: 'body',
        label: 'Body',
        type: 'TEXT',
        icon: 'file-text',
        description: 'Detailed description or notes for the activity',
        inTable: false,
      },
      {
        key: 'happenedAt',
        label: 'Happened At',
        type: 'DATE_TIME',
        icon: 'clock',
        description: 'When the activity occurred or is scheduled',
        required: true,
        inTable: true,
      },
      {
        key: 'targetObject',
        label: 'Target Object',
        type: 'TEXT',
        icon: 'target',
        description:
          'Slug of the object this activity relates to (e.g., companies, people, opportunities)',
        inTable: false,
      },
      {
        key: 'targetRecordId',
        label: 'Target Record',
        type: 'TEXT',
        icon: 'link-2',
        description: 'ID of the specific record this activity relates to',
        inTable: false,
      },
    ],
    board: { groupByField: 'type' },
  },
];

/** Set of standard object slugs for quick membership checks. */
export const STANDARD_OBJECT_SLUGS: ReadonlySet<string> = new Set(
  STANDARD_OBJECTS.map((o) => o.slug),
);

/**
 * Look up a standard object definition by slug.
 * Returns `undefined` for unknown / custom slugs.
 */
export function getStandardObject(slug: string): ObjectMetadata | undefined {
  return STANDARD_OBJECTS.find((o) => o.slug === slug);
}
